"""The draft of the written decision the evidence gate closes on.

MV5's exit is "a written go / stop / pivot / kill decision, with the raw ledger
slice attached, measured against `docs/evidence-gate.md`". The instrument can
write half of that document: the outcome the preregistered rule returns, every
measure with its status, the missing data and exclusions FR-M46-15 publishes,
and the digests binding the report and the ledger slice to it.

It must not write the other half. The path chosen, why it departs from the
computed outcome if it does, and who decided are a person's to write. So the
draft leaves those sections empty, and says in its first lines that it is not a
decision until someone writes one.

Zero model calls (FR-M36-07).
"""

from __future__ import annotations

from typing import Any


def _cell(value: Any) -> str:
    text = "" if value is None else str(value)
    return text.replace("|", "\\|").replace("\n", " ")


def _value(measure: dict[str, Any]) -> str:
    value = measure.get("value")
    if value is None:
        return "—"
    if isinstance(value, float):
        return f"{value:.3f}"
    return _cell(value)


def _threshold(threshold: dict[str, Any]) -> str:
    return _cell("; ".join(f"{k} {v}" for k, v in threshold.items() if k != "measure"))


def decision_draft(report: dict[str, Any], attachments: dict[str, str], generated_at: str) -> str:
    """Markdown for `DECISION-DRAFT.md`. ``attachments`` maps file name to sha256."""
    study = report["study"]
    registration = report["preregistration"]
    recommendation = report["recommendation"]
    stories = report["stories"]
    measures = report["measures"]
    arms = stories["byArm"]

    lines = [
        f"# Evidence gate decision — {study.get('studyId') or 'unnamed study'}",
        "",
        f"> **A draft, not a decision.** Generated by `python -m meridian_core.cli evidence-gate` "
        f"at {generated_at}. The computed half is filled in. The decision below is written by a "
        "person, and until it is, there is no decision.",
        "",
        "## Computed under the preregistered rule",
        "",
        f"- **Outcome under `{registration['document']}` §4:** `{recommendation['verdict']}`",
        f"- **Preregistration:** `{registration['state']}` — registered "
        f"`{registration.get('registeredDigest')}`, applied `{registration['thresholdsDigest']}`",
    ]
    if recommendation.get("invalidated"):
        lines.append(
            "- **This result is invalidated under §5 and must be published as invalidated.**"
        )
    lines += [
        f"- **Stories:** {stories['total']} of {stories['required']} "
        f"(arm A {arms['A']} · arm B {arms['B']} · arm C {arms['C']})",
        "",
        "| # | Measure | Status | Value | Threshold | What it says |",
        "|---|---|---|---|---|---|",
    ]
    for measure_id, measure in measures.items():
        lines.append(
            f"| {measure_id} | {_cell(measure['threshold'].get('measure'))} | "
            f"`{measure['status']}` | {_value(measure)} | {_threshold(measure['threshold'])} | "
            f"{_cell(measure['note'])} |"
        )
    lines += ["", "### Why the rule returned this outcome", ""]
    lines += [f"- {_cell(reason)}" for reason in recommendation["reasons"]]

    unmeasured = [m for m, v in measures.items() if v["status"] == "unmeasured"]
    lines += [
        "",
        "## Missing data and exclusions (published under FR-M46-15)",
        "",
        f"- **Unmeasured:** {', '.join(unmeasured) if unmeasured else 'none'}",
        "- **FR-M46-14 fields not recorded:** "
        + (", ".join(study["missingRecordedFields"]) or "none"),
        "- **Allocated to a Meridian arm with no ledger rows:** "
        + (", ".join(stories["allocatedButAbsentFromLedger"]) or "none"),
    ]
    exclusions = study.get("exclusions") or []
    lines.append("- **Exclusions:** " + ("none" if not exclusions else ""))
    lines += [f"  - `{_cell(e['storyId'])}` — {_cell(e['reason'])}" for e in exclusions]

    first_value = report.get("firstValue") or {}
    lines += ["", "## FR-M46-04, beside the rule", ""]
    for key, label in (("onboarding", "Onboarding sessions"), ("reviewTasks", "Review tasks")):
        part = first_value.get(key) or {}
        lines.append(f"- **{label}:** `{part.get('status')}` — {_cell(part.get('note'))}")

    lines += [
        "",
        "## Attachments",
        "",
        "| File | sha256 |",
        "|---|---|",
        *(f"| `{name}` | `{digest}` |" for name, digest in attachments.items()),
        "",
        "The ledger slice verifies without Meridian: "
        "`python verify.py ledger-slice.json`, or `python -m meridian_core.cli verify ledger-slice.json`.",
        "",
        "## The decision — written by a person",
        "",
        "**Path chosen:** GO / STOP / PIVOT / KILL *(delete three)*",
        "",
        "**If this differs from the computed outcome, why.** A departure from §4 is published "
        "as a departure. It is not a re-reading of the thresholds.",
        "",
        "**What was unfavourable.** Published either way (FR-M46-15).",
        "",
        "**The sample a comparative claim would need**, from the variance observed here (§2).",
        "",
        "**Decided by** *(role, not name)* **on** *(date)*.",
        "",
    ]
    return "\n".join(lines)
