# Generated by scripts/generate-bus-types.mjs from shared/schema/. DO NOT EDIT.
# FR-M32-09: the Simulation Core, the production sidecar and the extension
# consume these types; npm run check:contracts fails on drift.
from __future__ import annotations

from typing import Any, Literal, TypedDict
from typing import NotRequired

PROTOCOL_VERSION: Literal[1] = 1

# Standard JSON-RPC 2.0 codes plus the Meridian -320xx range.
PARSE_ERROR: int = -32700
INVALID_REQUEST: int = -32600
METHOD_NOT_FOUND: int = -32601
INVALID_PARAMS: int = -32602
INTERNAL_ERROR: int = -32603
NOT_IMPLEMENTED: int = -32001
PROTOCOL_MISMATCH: int = -32002
TIER_DISABLED: int = -32003
LEDGER_UNAVAILABLE: int = -32004

class HandshakeParams(TypedDict):
    protocolVersion: int  # Must equal PROTOCOL_VERSION or the sidecar refuses with PROTOCOL_MISMATCH.
    client: str  # e.g. meridian-loom-extension
    tiers: NotRequired[list[TierName]]  # FR-M36-05: tiers enabled in this workspace (from the meridian.tiers setting). Absent means the sidecar default: flight-recorder only. The base tier is always enabled regardless.
    workspaceDir: NotRequired[str]  # Absolute workspace path. The ledger lives at <workspaceDir>/.meridian/ledger (FR-M10-01). Absent: ledger RPCs answer LEDGER_UNAVAILABLE until configured.
    ledgerSigningKey: NotRequired[str]  # Base64-encoded 32-byte Ed25519 seed (FR-M10-04), sourced from the extension host's OS-keychain-backed SecretStorage (SEC-06) and provisioned over this handshake. Held in memory only; never persisted to disk or written into the ledger. Absent: the sidecar signs tree heads with an ephemeral key and doctor reports the missing keychain key.

class Capabilities(TypedDict):
    methods: list[str]
    framing: Literal["ndjson"]

class HandshakeResult(TypedDict):
    protocolVersion: int
    coreVersion: str
    pythonVersion: str
    capabilities: Capabilities

class PingParams(TypedDict):
    pass

class PingResult(TypedDict):
    pong: Literal[True]
    seq: int  # Monotonic per-process ping counter.
    uptimeSeconds: float

class ShutdownParams(TypedDict):
    reason: NotRequired[str]

class ShutdownResult(TypedDict):
    ok: Literal[True]

class HealthParams(TypedDict):
    pass

class HealthResult(TypedDict):
    status: Literal["ok", "degraded", "shutting-down"]
    uptimeSeconds: float
    pid: int
    activeLoops: int

# Outcome of one doctor check. warn means usable but degraded or not yet installed; fail means broken and actionable.
DoctorCheckStatus = Literal["pass", "warn", "fail"]

class DoctorCheck(TypedDict):
    id: str  # Stable machine id, e.g. interpreter, sidecar, ledger.
    name: str  # Human-readable check name.
    status: DoctorCheckStatus
    detail: str  # What was found, in one line.
    remediation: NotRequired[str]  # Actionable fix; always present on warn and fail.

class DoctorRunParams(TypedDict):
    checks: NotRequired[list[str]]  # Subset of check ids to run; absent runs the whole registry.
    workspaceDir: NotRequired[str]  # Absolute path of the workspace folder; the git-hooks check needs it.

class DoctorRunResult(TypedDict):
    status: DoctorCheckStatus  # Worst status across all checks: fail > warn > pass.
    checks: list[DoctorCheck]

class AttribBlameParams(TypedDict):
    repoPath: str  # Absolute path of the git repository (any directory inside it is accepted and resolved to the toplevel).
    ref: NotRequired[str]  # Commit-ish to blame; default HEAD.
    paths: NotRequired[list[str]]  # Worktree-relative file filter; absent blames every tracked file.

class AttribBlameLine(TypedDict):
    path: str
    line: int  # 1-based line number in the ref's version of the file.
    commit: str  # Full hex sha of the introducing commit; never a merge commit.
    authorName: str
    authorEmail: str
    authorTime: str  # Author timestamp, ISO 8601 UTC.
    content: str  # Line content without the terminator (CRLF tolerated).

class AttribBlameResult(TypedDict):
    repoPath: str  # Resolved repository toplevel.
    ref: str
    lines: list[AttribBlameLine]

class AttribDiffParams(TypedDict):
    repoPath: str  # Absolute path of the git repository (any directory inside it is accepted and resolved to the toplevel).
    base: NotRequired[str]  # Range start (commit-ish). With compare: base..compare; alone: base vs worktree.
    compare: NotRequired[str]  # Range end (commit-ish); added lines are blame-annotated at this ref.
    staged: NotRequired[bool]  # Diff the index against HEAD (base optionally overrides HEAD).
    paths: NotRequired[list[str]]  # Worktree-relative path filter.

AttribDiffLineKind = Literal["added", "removed", "context"]

class AttribDiffLine(TypedDict):
    kind: AttribDiffLineKind
    oldLine: int | None  # 1-based in the base version; null for pure additions.
    newLine: int | None  # 1-based in the compare version; null for removals.
    content: str
    commit: NotRequired[str | None]  # Introducing commit for range-diff added lines (blame at compare); null for worktree/index changes.
    authorName: NotRequired[str | None]
    authorEmail: NotRequired[str | None]
    authorTime: NotRequired[str | None]

class AttribHunk(TypedDict):
    oldStart: int
    oldCount: int
    newStart: int
    newCount: int
    lines: list[AttribDiffLine]

AttribFileStatus = Literal["added", "modified", "deleted", "renamed"]

class AttribFileDiff(TypedDict):
    path: str  # Compare-side path.
    oldPath: str | None  # Set for renames.
    status: AttribFileStatus
    hunks: list[AttribHunk]

class AttribDiffResult(TypedDict):
    repoPath: str  # Resolved repository toplevel.
    base: str | None
    compare: str | None
    staged: bool
    files: list[AttribFileDiff]

class AttribSymbolParams(TypedDict):
    repoPath: str  # Absolute path of the git repository (any directory inside it is accepted and resolved to the toplevel).
    path: str  # Worktree-relative file path.
    line: int  # 1-based line number.

class AttribSymbolResult(TypedDict):
    path: str
    line: int
    language: str | None  # Registered language id; null when the extension is not registered.
    symbol: str | None  # Qualified enclosing definition, e.g. PaymentController.submit; null when none or degraded.

# An externally observed agent session (Workstream D supplies these; the heuristic only consumes them). Its presence covering an edit window raises the agent attribution weight and lifts the label to telemetry.
class AttribObservedSession(TypedDict):
    sessionId: str
    vendor: str
    agentId: NotRequired[str]
    startedAt: NotRequired[str]  # ISO 8601 or epoch seconds; absent means currently active. A file edited before this time is not covered.

class AttribClassifyParams(TypedDict):
    repoPath: str
    base: NotRequired[str]
    compare: NotRequired[str]
    staged: NotRequired[bool]
    paths: NotRequired[list[str]]
    observedSessions: NotRequired[list[AttribObservedSession]]

# agent | human | mixed | unknown. unknown is a first-class honest answer when no signal fires (G3).
AttribAttribution = Literal["agent", "human", "mixed", "unknown"]

class AttribFileClassification(TypedDict):
    path: str
    linesAdded: int
    linesRemoved: int
    burstLines: int  # Lines added in the same timestamp sweep / commit as this file's edits.
    multiLineInsertRate: float  # Fraction of insertion hunks adding >=5 lines at once.
    editTimestamp: str | None  # Filesystem mtime of the edited file, ISO 8601 UTC; null for deletes.
    attribution: AttribAttribution
    agentWeight: float  # 0.0 human .. 1.0 agent; 0.5 means no evidence.
    observationConfidence: Literal["direct", "telemetry", "inferred"]  # FR-M35-02; heuristic output is never better than telemetry and the floor is inferred.
    rationale: list[str]  # Human-readable signals behind the weight, for UI disclosure.

class AttribClassifyResult(TypedDict):
    repoPath: str
    files: list[AttribFileClassification]

# One ledger entry, §7.2 columns in camelCase. input/output are redacted (SEC-07), encrypted and content-addressed (FR-M10-07); blob_subject selects the per-subject key (FR-M10-14).
class LedgerAppendParams(TypedDict):
    storyId: str
    phase: str
    loopId: str
    loopIteration: int
    actorId: str
    actorVersion: str
    actorKind: str  # orchestrator|role|stack|sub|xai|meta|external
    policyVersion: str
    skillId: NotRequired[str]
    skillVersion: NotRequired[str]
    modelId: NotRequired[str]
    modelVersion: NotRequired[str]
    actionType: str  # plan|prompt|tool_call|diff|test_run|review|scan|gate|approval|policy_update|export
    input: NotRequired[str]  # Full prompt/context; redacted + encrypted into the blob store.
    output: NotRequired[str]  # Resulting output; redacted + encrypted into the blob store.
    toolCalls: NotRequired[list[dict[str, Any]]]
    confidence: NotRequired[float]
    decision: NotRequired[Literal["proposed", "approved", "rejected", "reworked"]]
    humanActor: NotRequired[str]
    humanRole: NotRequired[str]
    reworkReason: NotRequired[str]
    tokensIn: NotRequired[int]
    tokensOut: NotRequired[int]
    costUsd: NotRequired[float]
    latencyMs: NotRequired[int]
    worktreeRef: NotRequired[str]
    repoId: NotRequired[str]
    replayOf: NotRequired[int]
    vendor: NotRequired[str]  # Default 'meridian'; external agents carry their vendor (FR-M35-03).
    observationConfidence: NotRequired[Literal["direct", "telemetry", "inferred"]]  # FR-M35-02 observation confidence; default 'direct'.
    externalSessionId: NotRequired[str]
    runId: NotRequired[str]
    origin: NotRequired[Literal["ui", "command", "omnibar", "chat", "editor", "file", "connector", "api"]]  # FR-M40-02: written with the run's first entry.
    simulated: NotRequired[bool]  # FR-M32-02 simulation marker; absent means false.
    timestamp: NotRequired[str]  # ISO 8601 UTC override (replay/golden corpus); absent = now.
    blobSubject: NotRequired[str]  # Subject for the per-subject blob key; default 'default'.

class LedgerAppendResult(TypedDict):
    sequence: int
    hash: str  # entry_hash hex, chained from the previous (FR-M10-02).
    previousHash: str
    timestamp: str
    treeHead: NotRequired[TreeHead]  # Present when this append emitted a signed tree head (FR-M10-04).

# FR-M10-04 signed tree head: the Merkle root over entries 1..seq, Ed25519-signed; hex-encoded.
class TreeHead(TypedDict):
    seq: int
    rootHash: str
    signedAt: str
    signature: str
    anchorRef: NotRequired[str]

class LedgerQueryParams(TypedDict):
    storyId: NotRequired[str]
    actorId: NotRequired[str]  # Agent id filter.
    vendor: NotRequired[str]
    actionType: NotRequired[str]
    fromSequence: NotRequired[int]
    toSequence: NotRequired[int]
    fromTimestamp: NotRequired[str]  # ISO 8601 UTC lower bound (inclusive).
    toTimestamp: NotRequired[str]  # ISO 8601 UTC upper bound (inclusive).
    limit: NotRequired[int]  # Default 100, clamped to 1000.

# FR-M11-02 stream shape: one ledger entry with chain hashes; blob payloads are referenced by digest/ref, not inlined.
class LedgerEntry(TypedDict):
    sequence: int
    timestamp: str
    storyId: str
    phase: str
    loopId: str
    loopIteration: int
    actorId: str
    actorVersion: str
    actorKind: str
    policyVersion: str
    skillId: NotRequired[str]
    skillVersion: NotRequired[str]
    modelId: NotRequired[str]
    modelVersion: NotRequired[str]
    actionType: str
    toolCallsSummary: NotRequired[int]  # Count of tool calls; the array itself is in the entry detail (FR-M11-03).
    confidence: NotRequired[float]
    decision: NotRequired[str]
    humanActor: NotRequired[str]
    humanRole: NotRequired[str]
    reworkReason: NotRequired[str]
    tokensIn: NotRequired[int]
    tokensOut: NotRequired[int]
    costUsd: NotRequired[float]
    latencyMs: NotRequired[int]
    worktreeRef: NotRequired[str]
    repoId: NotRequired[str]
    replayOf: NotRequired[int]
    vendor: str
    observationConfidence: str
    externalSessionId: NotRequired[str]
    runId: NotRequired[str]
    origin: NotRequired[str]
    simulated: bool
    entryHash: str
    previousHash: str
    hasInputBlob: bool
    hasOutputBlob: bool

class LedgerQueryResult(TypedDict):
    entries: list[LedgerEntry]

class LedgerGetEntryParams(TypedDict):
    sequence: int

# FR-M11-03 detail. input/output carry the decrypted blob text when the sidecar holds the subject key; *Available flags say whether decryption succeeded (false when the key was crypto-shredded).
class LedgerGetEntryResult(TypedDict):
    sequence: int
    timestamp: str
    storyId: str
    phase: str
    loopId: str
    loopIteration: int
    actorId: str
    actorVersion: str
    actorKind: str
    policyVersion: str
    skillId: NotRequired[str]
    skillVersion: NotRequired[str]
    modelId: NotRequired[str]
    modelVersion: NotRequired[str]
    actionType: str
    toolCalls: NotRequired[list[dict[str, Any]]]
    confidence: NotRequired[float]
    decision: NotRequired[str]
    humanActor: NotRequired[str]
    humanRole: NotRequired[str]
    reworkReason: NotRequired[str]
    tokensIn: NotRequired[int]
    tokensOut: NotRequired[int]
    costUsd: NotRequired[float]
    latencyMs: NotRequired[int]
    worktreeRef: NotRequired[str]
    repoId: NotRequired[str]
    replayOf: NotRequired[int]
    vendor: str
    observationConfidence: str
    externalSessionId: NotRequired[str]
    runId: NotRequired[str]
    origin: NotRequired[str]
    simulated: bool
    entryHash: str
    previousHash: str
    inputDigest: NotRequired[str]
    inputRef: NotRequired[str]
    outputDigest: NotRequired[str]
    outputRef: NotRequired[str]
    blobKeyId: NotRequired[str]
    input: NotRequired[str]
    output: NotRequired[str]
    inputAvailable: bool
    outputAvailable: bool

class LedgerVerifyParams(TypedDict):
    upTo: NotRequired[int]  # Verify a prefix only; absent verifies the whole chain.

# FR-M11-01 integrity banner payload.
class LedgerVerifyResult(TypedDict):
    ok: bool
    entriesChecked: int
    firstDivergentSequence: int | None
    detail: str
    verifiedAt: str

# RFC 6962 audit path for one leaf; hex-encoded hashes, leaf-upwards order (verifier: RFC 9162 §2.1.3.2).
class LedgerInclusionProof(TypedDict):
    treeSize: int
    leafIndex: int
    leafHash: str
    rootHash: str
    path: list[str]

# RFC 6962/9162 consistency proof between two tree sizes; hex-encoded hashes (verifier: RFC 9162 §2.1.4.2).
class LedgerConsistencyProof(TypedDict):
    fromSize: int
    toSize: int
    fromRootHash: str
    toRootHash: str
    path: list[str]

class LedgerProofParams(TypedDict):
    sequence: NotRequired[int]  # Inclusion proof for this entry (1-based).
    fromSize: NotRequired[int]  # Consistency proof: the earlier tree size.
    toSize: NotRequired[int]  # Consistency proof: the later tree size.

class LedgerProofResult(TypedDict):
    inclusion: NotRequired[LedgerInclusionProof]
    consistency: NotRequired[LedgerConsistencyProof]

class LedgerExportBundleParams(TypedDict):
    fromSequence: NotRequired[int]  # Default 1.
    toSequence: NotRequired[int]  # Default the ledger tip.
    storyId: NotRequired[str]  # Optional filter within the range.
    agentId: NotRequired[str]  # Optional filter within the range.

# One entry in an audit bundle: the FR-M11-02 stream shape plus ciphertext refs and digests, so a third-party verifier can check the chain segment without any key.
class LedgerBundleEntry(TypedDict):
    sequence: int
    timestamp: str
    storyId: str
    phase: str
    loopId: str
    loopIteration: NotRequired[int]
    actorId: str
    actorVersion: str
    actorKind: str
    policyVersion: NotRequired[str]
    skillId: NotRequired[str]
    skillVersion: NotRequired[str]
    modelId: NotRequired[str]
    modelVersion: NotRequired[str]
    actionType: str
    decision: NotRequired[str]
    confidence: NotRequired[float]
    humanActor: NotRequired[str]
    humanRole: NotRequired[str]
    reworkReason: NotRequired[str]
    tokensIn: NotRequired[int]
    tokensOut: NotRequired[int]
    costUsd: NotRequired[float]
    latencyMs: NotRequired[int]
    worktreeRef: NotRequired[str]
    repoId: NotRequired[str]
    replayOf: NotRequired[int]
    runId: NotRequired[str]
    origin: NotRequired[str]
    vendor: str
    observationConfidence: str
    externalSessionId: NotRequired[str]
    simulated: bool
    entryHash: str
    previousHash: str
    hasInputBlob: NotRequired[bool]
    hasOutputBlob: NotRequired[bool]
    inputDigest: NotRequired[str]
    inputRef: NotRequired[str]
    outputDigest: NotRequired[str]
    outputRef: NotRequired[str]

class LedgerBundleSigner(TypedDict):
    algorithm: Literal["Ed25519"]
    publicKey: str  # Base64 raw public key; signature verification needs no trust in Meridian servers (SEC-29).

class LedgerRange(TypedDict):
    fromSequence: int
    toSequence: int

class LedgerBundleFilter(TypedDict):
    storyId: NotRequired[str]
    agentId: NotRequired[str]

class LedgerExportBundleResult(TypedDict):
    formatVersion: int  # Bundle format v1; the open ledger spec (FR-M36-06) will pin this.
    generatedAt: str
    signer: LedgerBundleSigner
    treeHead: NotRequired[TreeHead]  # Signed head covering at least the range end; absent only when the ledger has no head yet (task 25 anchors this into the full SSDF bundle).
    range: LedgerRange
    filter: LedgerBundleFilter
    entries: list[LedgerBundleEntry]

class HookInstallParams(TypedDict):
    workspaceDir: NotRequired[str]  # Repository root. Absent means the handshake workspaceDir.

class HookInstallResult(TypedDict):
    installed: bool
    hookPath: str
    chained: bool  # True when a foreign commit-msg hook was backed up and is invoked by the Meridian hook before its own trailer logic.
    alreadyInstalled: bool  # True when the hook was already Meridian's — install is idempotent.
    backupPath: NotRequired[str]

class HookStatusParams(TypedDict):
    workspaceDir: NotRequired[str]

class HookStatusResult(TypedDict):
    installed: bool  # A commit-msg hook exists and carries the Meridian marker.
    hookPath: NotRequired[str]
    chained: NotRequired[bool]
    foreignHook: bool  # A commit-msg hook exists that is NOT Meridian's — it is left untouched.
    backupPath: NotRequired[str]
    detail: NotRequired[str]

class HookRemoveParams(TypedDict):
    workspaceDir: NotRequired[str]

class HookRemoveResult(TypedDict):
    removed: bool  # False when there was no Meridian hook to remove; the repository is left untouched.
    restoredBackup: bool  # True when a chained foreign hook was restored to commit-msg.
    backupPath: NotRequired[str]
    detail: NotRequired[str]

class HookPendingParams(TypedDict):
    stagedHash: str  # The staged-content key: the hex of the tree object git write-tree produces for the index (`git write-tree`).
    fromSequence: int
    toSequence: int
    recordedAt: NotRequired[str]

class HookPendingResult(TypedDict):
    recorded: bool
    pendingPath: NotRequired[str]

# The six canonical loops (FR-M4-03).
LoopKind = Literal["L1-micro", "L2-task", "L3-phase", "L4-delivery", "L5-learning", "L6-organisation"]

LoopState = Literal["pending", "running", "paused", "blocked", "completed", "failed", "aborted"]

class LoopStartParams(TypedDict):
    loopId: str
    storyId: str
    kind: LoopKind

class LoopStopParams(TypedDict):
    loopId: str
    reason: NotRequired[str]

class LoopStatusParams(TypedDict):
    loopId: str

class LoopStatusResult(TypedDict):
    loopId: str
    kind: LoopKind
    state: LoopState
    iteration: int
    lastCheckpoint: NotRequired[str]  # Durable checkpoint id (FR-M4-05), present once the loop has checkpointed.

class CancelParams(TypedDict):
    id: RequestId

class GateEvaluateParams(TypedDict):
    storyId: str
    gate: str  # Gate name, e.g. security, review (FR-M12-01).

class GateEvaluateResult(TypedDict):
    decision: Literal["pass", "block"]
    reasons: NotRequired[list[str]]

class SteerSendParams(TypedDict):
    sessionId: str
    message: str

class SteerSendResult(TypedDict):
    accepted: bool

class TrustSummaryParams(TypedDict):
    agentId: NotRequired[str]

class TrustSummaryResult(TypedDict):
    entries: list[dict[str, Any]]

# FR-M35-02 observation confidence: direct (the agent's own telemetry/ACP session), telemetry (evidence the agent left behind: git trailers, SCM/PR API, OS process listing), inferred (filesystem/git inference — the floor, never silence).
ObservationConfidence = Literal["direct", "telemetry", "inferred"]

# SEC-27: observer-facing APIs accept NO credential parameters — the observation surface is one-way. Empty params; additionalProperties false keeps it that way.
class ObserveSessionsParams(TypedDict):
    pass

# X-29: one external agent session as shown in the Crown — vendor tag (FR-M35-03) + observation confidence (FR-M35-02), never indistinguishable from a Meridian-native pass.
class ObserveSession(TypedDict):
    sessionId: str
    vendor: str  # claude-code | copilot | cursor | codex | devin | gemini
    confidence: ObservationConfidence
    source: str  # process | otel | git-trailers | scm-api | filesystem
    detail: str
    pid: NotRequired[int | None]  # OS pid when detected by process inspection (X-29).
    startedAt: NotRequired[str | None]  # ISO 8601 UTC; null when unknown (process sessions).
    lastActivityAt: NotRequired[str | None]
    agentId: NotRequired[str | None]

class ObserveSessionsResult(TypedDict):
    sessions: list[ObserveSession]
    warnings: list[str]  # Sticky NFR-32 degradation warnings visible in the UI.

class ObserveHealthParams(TypedDict):
    pass

# FR-M35-08: one observer adapter's health — versioned against the vendor release.
class ObserverHealth(TypedDict):
    name: str
    vendor: NotRequired[str]
    status: Literal["ok", "degraded"]  # degraded means an NFR-32 downgrade warning is active — observation continues at lower confidence, never silence.
    detail: str
    vendorRelease: NotRequired[str]
    adapterVersion: NotRequired[str]
    warnings: list[str]

class ObserveHealthResult(TypedDict):
    observers: list[ObserverHealth]
    monitorRunning: bool  # True once the X-29 session monitor thread is polling.

class TierSetParams(TypedDict):
    tiers: list[TierName]

# Every request/response method on the bus.
MethodName = Literal["handshake", "ping", "shutdown", "health", "attrib/blame", "attrib/diff", "attrib/symbol", "attrib/classify", "observe/sessions", "observe/health", "doctor/run", "ledger.append", "ledger.query", "ledger.getEntry", "ledger.verify", "ledger.proof", "ledger.exportBundle", "hook/install", "hook/status", "hook/remove", "hook/pending", "loop.start", "loop.stop", "loop.status", "gate.evaluate", "steer.send", "trust.summary"]

# Every notification method on the bus.
NotificationName = Literal["tiers/set", "$/cancel"]

# JSON-RPC 2.0 request id. The extension allocates monotonically increasing integers; strings are accepted for forwards compatibility.
RequestId = int | str

# JSON-RPC 2.0 error object. code is one of ErrorCode; data carries structured detail (e.g. expected/actual for PROTOCOL_MISMATCH).
class ErrorObject(TypedDict):
    code: int
    message: str
    data: NotRequired[Any]

# A JSON-RPC 2.0 request on the wire.
class RequestEnvelope(TypedDict):
    jsonrpc: Literal["2.0"]
    id: RequestId
    method: MethodName
    params: NotRequired[Any]

# A JSON-RPC 2.0 response. Exactly one of result/error is present (asserted by both implementations, not expressible here without oneOf).
class ResponseEnvelope(TypedDict):
    jsonrpc: Literal["2.0"]
    id: RequestId
    result: NotRequired[Any]
    error: NotRequired[ErrorObject]

# A JSON-RPC 2.0 notification (no id, no response).
class NotificationEnvelope(TypedDict):
    jsonrpc: Literal["2.0"]
    method: NotificationName
    params: NotRequired[Any]

# One capability in the registry (FR-M36-05). rpcMethods are the bus methods the capability owns.
class CapabilityDefinition(TypedDict):
    id: str
    tier: TierName
    description: str
    rpcMethods: list[str]

# The three product tiers (FR-M36-05), base first.
TierName = Literal["flight-recorder", "governor", "orchestra"]

# FR-M36-05: all tiers, base first.
TIERS: tuple[str, ...] = ("flight-recorder", "governor", "orchestra")

# FR-M36-05: enabled tiers when nothing is configured — Flight Recorder only.
DEFAULT_ENABLED_TIERS: tuple[str, ...] = ("flight-recorder",)

# FR-M36-05: capability registry; every capability is owned by exactly one tier.
CAPABILITIES: tuple[CapabilityDefinition, ...] = (
    {"id": "recorder.lifecycle", "tier": "flight-recorder", "description": "Sidecar lifecycle: handshake, heartbeat, shutdown, health. Always enabled — the base tier cannot be turned off.", "rpcMethods": ["handshake", "ping", "shutdown", "health"]},
    {"id": "recorder.doctor", "tier": "flight-recorder", "description": "Self-diagnostic check registry (FR-M30-01).", "rpcMethods": ["doctor/run"]},
    {"id": "recorder.attribution", "tier": "flight-recorder", "description": "Deterministic git-native attribution: line blame, unified-diff attribution for worktree/staged/ranges, tree-sitter line→symbol naming, human-vs-agent change heuristics (FR-M33-02 subset, FR-M35-02 aid; F0 Workstream C tasks 13–15). Zero model calls (FR-M36-07).", "rpcMethods": ["attrib/blame", "attrib/diff", "attrib/symbol", "attrib/classify"]},
    {"id": "recorder.ledger", "tier": "flight-recorder", "description": "Append-only provenance ledger, query API and Chain Viewer backend (FR-M10-01/02/07/08/09/12, FR-M11-01..05; F0 Workstream B).", "rpcMethods": ["ledger.append", "ledger.query", "ledger.getEntry", "ledger.verify", "ledger.proof", "ledger.exportBundle"]},
    {"id": "recorder.observers", "tier": "flight-recorder", "description": "External-agent observers (FR-M35-02/03/08, X-29, NFR-32; F0 Workstream D tasks 17-22): session observation via the documented fallback chain with confidence downgrade, X-29 session detection behind the Crown, and observer health. Zero model calls (FR-M36-07); one-way isolation (SEC-27).", "rpcMethods": ["observe/sessions", "observe/health"]},
    {"id": "recorder.provenance-hooks", "tier": "flight-recorder", "description": "Git provenance trailers (FR-M36-03, D23; F0 Workstream E tasks 23-24): the opt-in commit-msg hook appending `Meridian-Ledger: <seq range>`, pending-commit linkage records keyed by staged content hash, and hook lifecycle (install/status/remove). Zero model calls (FR-M36-07).", "rpcMethods": ["hook/install", "hook/status", "hook/remove", "hook/pending"]},
    {"id": "governor.gates", "tier": "governor", "description": "Policy gates over external and hosted agent work (FR-M12-01; F1). Stub RPC until F1 lands it.", "rpcMethods": ["gate.evaluate"]},
    {"id": "governor.steer", "tier": "governor", "description": "Steer and clarifying questions into running sessions (FR-M25-01/02; F1). Stub RPC until F1 lands it.", "rpcMethods": ["steer.send"]},
    {"id": "governor.trust", "tier": "governor", "description": "Trust and rejection analytics (FR-M37-*; F0 subset/F1 full). Stub RPC until it lands.", "rpcMethods": ["trust.summary"]},
    {"id": "orchestra.loops", "tier": "orchestra", "description": "The six canonical loops (FR-M4-03; F3). Stub RPCs until F3 lands them.", "rpcMethods": ["loop.start", "loop.stop", "loop.status"]},
)

REQUEST_METHODS: tuple[str, ...] = ("handshake", "ping", "shutdown", "health", "attrib/blame", "attrib/diff", "attrib/symbol", "attrib/classify", "observe/sessions", "observe/health", "doctor/run", "ledger.append", "ledger.query", "ledger.getEntry", "ledger.verify", "ledger.proof", "ledger.exportBundle", "hook/install", "hook/status", "hook/remove", "hook/pending", "loop.start", "loop.stop", "loop.status", "gate.evaluate", "steer.send", "trust.summary")
NOTIFICATION_METHODS: tuple[str, ...] = ("tiers/set", "$/cancel")

# Runtime pairing of method name -> params/result TypedDicts.
METHOD_CONTRACT: dict[str, dict[str, Any]] = {
    "handshake": {"params": HandshakeParams, "result": HandshakeResult},
    "ping": {"params": PingParams, "result": PingResult},
    "shutdown": {"params": ShutdownParams, "result": ShutdownResult},
    "health": {"params": HealthParams, "result": HealthResult},
    "attrib/blame": {"params": AttribBlameParams, "result": AttribBlameResult},
    "attrib/diff": {"params": AttribDiffParams, "result": AttribDiffResult},
    "attrib/symbol": {"params": AttribSymbolParams, "result": AttribSymbolResult},
    "attrib/classify": {"params": AttribClassifyParams, "result": AttribClassifyResult},
    "observe/sessions": {"params": ObserveSessionsParams, "result": ObserveSessionsResult},
    "observe/health": {"params": ObserveHealthParams, "result": ObserveHealthResult},
    "doctor/run": {"params": DoctorRunParams, "result": DoctorRunResult},
    "ledger.append": {"params": LedgerAppendParams, "result": LedgerAppendResult},
    "ledger.query": {"params": LedgerQueryParams, "result": LedgerQueryResult},
    "ledger.getEntry": {"params": LedgerGetEntryParams, "result": LedgerGetEntryResult},
    "ledger.verify": {"params": LedgerVerifyParams, "result": LedgerVerifyResult},
    "ledger.proof": {"params": LedgerProofParams, "result": LedgerProofResult},
    "ledger.exportBundle": {"params": LedgerExportBundleParams, "result": LedgerExportBundleResult},
    "hook/install": {"params": HookInstallParams, "result": HookInstallResult},
    "hook/status": {"params": HookStatusParams, "result": HookStatusResult},
    "hook/remove": {"params": HookRemoveParams, "result": HookRemoveResult},
    "hook/pending": {"params": HookPendingParams, "result": HookPendingResult},
    "loop.start": {"params": LoopStartParams, "result": LoopStatusResult},
    "loop.stop": {"params": LoopStopParams, "result": LoopStatusResult},
    "loop.status": {"params": LoopStatusParams, "result": LoopStatusResult},
    "gate.evaluate": {"params": GateEvaluateParams, "result": GateEvaluateResult},
    "steer.send": {"params": SteerSendParams, "result": SteerSendResult},
    "trust.summary": {"params": TrustSummaryParams, "result": TrustSummaryResult},
}
