# Generated by scripts/generate-bus-types.mjs from shared/schema/. DO NOT EDIT.
# FR-M32-09: the Simulation Core, the production sidecar and the extension
# consume these types; npm run check:contracts fails on drift.
from __future__ import annotations

from typing import Any, Literal, TypedDict
from typing import NotRequired

PROTOCOL_VERSION: Literal[1] = 1

# Standard JSON-RPC 2.0 codes plus the Meridian -320xx range.
PARSE_ERROR: int = -32700
INVALID_REQUEST: int = -32600
METHOD_NOT_FOUND: int = -32601
INVALID_PARAMS: int = -32602
INTERNAL_ERROR: int = -32603
NOT_IMPLEMENTED: int = -32001
PROTOCOL_MISMATCH: int = -32002
TIER_DISABLED: int = -32003

class HandshakeParams(TypedDict):
    protocolVersion: int  # Must equal PROTOCOL_VERSION or the sidecar refuses with PROTOCOL_MISMATCH.
    client: str  # e.g. meridian-loom-extension
    tiers: NotRequired[list[TierName]]  # FR-M36-05: tiers enabled in this workspace (from the meridian.tiers setting). Absent means the sidecar default: flight-recorder only. The base tier is always enabled regardless.

class Capabilities(TypedDict):
    methods: list[str]
    framing: Literal["ndjson"]

class HandshakeResult(TypedDict):
    protocolVersion: int
    coreVersion: str
    pythonVersion: str
    capabilities: Capabilities

class PingParams(TypedDict):
    pass

class PingResult(TypedDict):
    pong: Literal[True]
    seq: int  # Monotonic per-process ping counter.
    uptimeSeconds: float

class ShutdownParams(TypedDict):
    reason: NotRequired[str]

class ShutdownResult(TypedDict):
    ok: Literal[True]

class HealthParams(TypedDict):
    pass

class HealthResult(TypedDict):
    status: Literal["ok", "degraded", "shutting-down"]
    uptimeSeconds: float
    pid: int
    activeLoops: int

# Outcome of one doctor check. warn means usable but degraded or not yet installed; fail means broken and actionable.
DoctorCheckStatus = Literal["pass", "warn", "fail"]

class DoctorCheck(TypedDict):
    id: str  # Stable machine id, e.g. interpreter, sidecar, ledger.
    name: str  # Human-readable check name.
    status: DoctorCheckStatus
    detail: str  # What was found, in one line.
    remediation: NotRequired[str]  # Actionable fix; always present on warn and fail.

class DoctorRunParams(TypedDict):
    checks: NotRequired[list[str]]  # Subset of check ids to run; absent runs the whole registry.
    workspaceDir: NotRequired[str]  # Absolute path of the workspace folder; the git-hooks check needs it.

class DoctorRunResult(TypedDict):
    status: DoctorCheckStatus  # Worst status across all checks: fail > warn > pass.
    checks: list[DoctorCheck]

class LedgerAppendParams(TypedDict):
    entryType: str
    payload: dict[str, Any]
    simulated: NotRequired[bool]  # Simulation Core marker (FR-M32-02); absent means false.

class LedgerAppendResult(TypedDict):
    sequence: int
    hash: str  # Hash of this entry, chained from the previous (FR-M10-02).

class LedgerQueryParams(TypedDict):
    entryType: NotRequired[str]
    fromSequence: NotRequired[int]
    limit: NotRequired[int]

class LedgerEntry(TypedDict):
    sequence: int
    entryType: str
    hash: str
    previousHash: str
    timestamp: str  # ISO 8601 UTC.
    simulated: bool
    payload: dict[str, Any]

class LedgerQueryResult(TypedDict):
    entries: list[LedgerEntry]

# The six canonical loops (FR-M4-03).
LoopKind = Literal["L1-micro", "L2-task", "L3-phase", "L4-delivery", "L5-learning", "L6-organisation"]

LoopState = Literal["pending", "running", "paused", "blocked", "completed", "failed", "aborted"]

class LoopStartParams(TypedDict):
    loopId: str
    storyId: str
    kind: LoopKind

class LoopStopParams(TypedDict):
    loopId: str
    reason: NotRequired[str]

class LoopStatusParams(TypedDict):
    loopId: str

class LoopStatusResult(TypedDict):
    loopId: str
    kind: LoopKind
    state: LoopState
    iteration: int
    lastCheckpoint: NotRequired[str]  # Durable checkpoint id (FR-M4-05), present once the loop has checkpointed.

class CancelParams(TypedDict):
    id: RequestId

class GateEvaluateParams(TypedDict):
    storyId: str
    gate: str  # Gate name, e.g. security, review (FR-M12-01).

class GateEvaluateResult(TypedDict):
    decision: Literal["pass", "block"]
    reasons: NotRequired[list[str]]

class SteerSendParams(TypedDict):
    sessionId: str
    message: str

class SteerSendResult(TypedDict):
    accepted: bool

class TrustSummaryParams(TypedDict):
    agentId: NotRequired[str]

class TrustSummaryResult(TypedDict):
    entries: list[dict[str, Any]]

class TierSetParams(TypedDict):
    tiers: list[TierName]

# Every request/response method on the bus.
MethodName = Literal["handshake", "ping", "shutdown", "health", "doctor/run", "ledger.append", "ledger.query", "loop.start", "loop.stop", "loop.status", "gate.evaluate", "steer.send", "trust.summary"]

# Every notification method on the bus.
NotificationName = Literal["tiers/set", "$/cancel"]

# JSON-RPC 2.0 request id. The extension allocates monotonically increasing integers; strings are accepted for forwards compatibility.
RequestId = int | str

# JSON-RPC 2.0 error object. code is one of ErrorCode; data carries structured detail (e.g. expected/actual for PROTOCOL_MISMATCH).
class ErrorObject(TypedDict):
    code: int
    message: str
    data: NotRequired[Any]

# A JSON-RPC 2.0 request on the wire.
class RequestEnvelope(TypedDict):
    jsonrpc: Literal["2.0"]
    id: RequestId
    method: MethodName
    params: NotRequired[Any]

# A JSON-RPC 2.0 response. Exactly one of result/error is present (asserted by both implementations, not expressible here without oneOf).
class ResponseEnvelope(TypedDict):
    jsonrpc: Literal["2.0"]
    id: RequestId
    result: NotRequired[Any]
    error: NotRequired[ErrorObject]

# A JSON-RPC 2.0 notification (no id, no response).
class NotificationEnvelope(TypedDict):
    jsonrpc: Literal["2.0"]
    method: NotificationName
    params: NotRequired[Any]

# One capability in the registry (FR-M36-05). rpcMethods are the bus methods the capability owns.
class CapabilityDefinition(TypedDict):
    id: str
    tier: TierName
    description: str
    rpcMethods: list[str]

# The three product tiers (FR-M36-05), base first.
TierName = Literal["flight-recorder", "governor", "orchestra"]

# FR-M36-05: all tiers, base first.
TIERS: tuple[str, ...] = ("flight-recorder", "governor", "orchestra")

# FR-M36-05: enabled tiers when nothing is configured — Flight Recorder only.
DEFAULT_ENABLED_TIERS: tuple[str, ...] = ("flight-recorder",)

# FR-M36-05: capability registry; every capability is owned by exactly one tier.
CAPABILITIES: tuple[CapabilityDefinition, ...] = (
    {"id": "recorder.lifecycle", "tier": "flight-recorder", "description": "Sidecar lifecycle: handshake, heartbeat, shutdown, health. Always enabled — the base tier cannot be turned off.", "rpcMethods": ["handshake", "ping", "shutdown", "health"]},
    {"id": "recorder.doctor", "tier": "flight-recorder", "description": "Self-diagnostic check registry (FR-M30-01).", "rpcMethods": ["doctor/run"]},
    {"id": "recorder.ledger", "tier": "flight-recorder", "description": "Append-only provenance ledger and queries (FR-M10-01, FR-M10-12; F0 Workstream B).", "rpcMethods": ["ledger.append", "ledger.query"]},
    {"id": "governor.gates", "tier": "governor", "description": "Policy gates over external and hosted agent work (FR-M12-01; F1). Stub RPC until F1 lands it.", "rpcMethods": ["gate.evaluate"]},
    {"id": "governor.steer", "tier": "governor", "description": "Steer and clarifying questions into running sessions (FR-M25-01/02; F1). Stub RPC until F1 lands it.", "rpcMethods": ["steer.send"]},
    {"id": "governor.trust", "tier": "governor", "description": "Trust and rejection analytics (FR-M37-*; F0 subset/F1 full). Stub RPC until it lands.", "rpcMethods": ["trust.summary"]},
    {"id": "orchestra.loops", "tier": "orchestra", "description": "The six canonical loops (FR-M4-03; F3). Stub RPCs until F3 lands them.", "rpcMethods": ["loop.start", "loop.stop", "loop.status"]},
)

REQUEST_METHODS: tuple[str, ...] = ("handshake", "ping", "shutdown", "health", "doctor/run", "ledger.append", "ledger.query", "loop.start", "loop.stop", "loop.status", "gate.evaluate", "steer.send", "trust.summary")
NOTIFICATION_METHODS: tuple[str, ...] = ("tiers/set", "$/cancel")

# Runtime pairing of method name -> params/result TypedDicts.
METHOD_CONTRACT: dict[str, dict[str, Any]] = {
    "handshake": {"params": HandshakeParams, "result": HandshakeResult},
    "ping": {"params": PingParams, "result": PingResult},
    "shutdown": {"params": ShutdownParams, "result": ShutdownResult},
    "health": {"params": HealthParams, "result": HealthResult},
    "doctor/run": {"params": DoctorRunParams, "result": DoctorRunResult},
    "ledger.append": {"params": LedgerAppendParams, "result": LedgerAppendResult},
    "ledger.query": {"params": LedgerQueryParams, "result": LedgerQueryResult},
    "loop.start": {"params": LoopStartParams, "result": LoopStatusResult},
    "loop.stop": {"params": LoopStopParams, "result": LoopStatusResult},
    "loop.status": {"params": LoopStatusParams, "result": LoopStatusResult},
    "gate.evaluate": {"params": GateEvaluateParams, "result": GateEvaluateResult},
    "steer.send": {"params": SteerSendParams, "result": SteerSendResult},
    "trust.summary": {"params": TrustSummaryParams, "result": TrustSummaryResult},
}
