# Generated by scripts/generate-bus-types.mjs from shared/schema/. DO NOT EDIT.
# FR-M32-09: the Simulation Core, the production sidecar and the extension
# consume these types; npm run check:contracts fails on drift.
from __future__ import annotations

from typing import Any, Literal, TypedDict
from typing import NotRequired

PROTOCOL_VERSION: Literal[1] = 1

# Standard JSON-RPC 2.0 codes plus the Meridian -320xx range.
PARSE_ERROR: int = -32700
INVALID_REQUEST: int = -32600
METHOD_NOT_FOUND: int = -32601
INVALID_PARAMS: int = -32602
INTERNAL_ERROR: int = -32603
NOT_IMPLEMENTED: int = -32001
PROTOCOL_MISMATCH: int = -32002

class HandshakeParams(TypedDict):
    protocolVersion: int  # Must equal PROTOCOL_VERSION or the sidecar refuses with PROTOCOL_MISMATCH.
    client: str  # e.g. meridian-loom-extension

class Capabilities(TypedDict):
    methods: list[str]
    framing: Literal["ndjson"]

class HandshakeResult(TypedDict):
    protocolVersion: int
    coreVersion: str
    pythonVersion: str
    capabilities: Capabilities

class PingParams(TypedDict):
    pass

class PingResult(TypedDict):
    pong: Literal[True]
    seq: int  # Monotonic per-process ping counter.
    uptimeSeconds: float

class ShutdownParams(TypedDict):
    reason: NotRequired[str]

class ShutdownResult(TypedDict):
    ok: Literal[True]

class HealthParams(TypedDict):
    pass

class HealthResult(TypedDict):
    status: Literal["ok", "degraded", "shutting-down"]
    uptimeSeconds: float
    pid: int
    activeLoops: int

class LedgerAppendParams(TypedDict):
    entryType: str
    payload: dict[str, Any]
    simulated: NotRequired[bool]  # Simulation Core marker (FR-M32-02); absent means false.

class LedgerAppendResult(TypedDict):
    sequence: int
    hash: str  # Hash of this entry, chained from the previous (FR-M10-02).

class LedgerQueryParams(TypedDict):
    entryType: NotRequired[str]
    fromSequence: NotRequired[int]
    limit: NotRequired[int]

class LedgerEntry(TypedDict):
    sequence: int
    entryType: str
    hash: str
    previousHash: str
    timestamp: str  # ISO 8601 UTC.
    simulated: bool
    payload: dict[str, Any]

class LedgerQueryResult(TypedDict):
    entries: list[LedgerEntry]

# The six canonical loops (FR-M4-03).
LoopKind = Literal["L1-micro", "L2-task", "L3-phase", "L4-delivery", "L5-learning", "L6-organisation"]

LoopState = Literal["pending", "running", "paused", "blocked", "completed", "failed", "aborted"]

class LoopStartParams(TypedDict):
    loopId: str
    storyId: str
    kind: LoopKind

class LoopStopParams(TypedDict):
    loopId: str
    reason: NotRequired[str]

class LoopStatusParams(TypedDict):
    loopId: str

class LoopStatusResult(TypedDict):
    loopId: str
    kind: LoopKind
    state: LoopState
    iteration: int
    lastCheckpoint: NotRequired[str]  # Durable checkpoint id (FR-M4-05), present once the loop has checkpointed.

class CancelParams(TypedDict):
    id: RequestId

# Every request/response method on the bus.
MethodName = Literal["handshake", "ping", "shutdown", "health", "ledger.append", "ledger.query", "loop.start", "loop.stop", "loop.status"]

# Every notification method on the bus.
NotificationName = Literal["$/cancel"]

# JSON-RPC 2.0 request id. The extension allocates monotonically increasing integers; strings are accepted for forwards compatibility.
RequestId = int | str

# JSON-RPC 2.0 error object. code is one of ErrorCode; data carries structured detail (e.g. expected/actual for PROTOCOL_MISMATCH).
class ErrorObject(TypedDict):
    code: int
    message: str
    data: NotRequired[Any]

# A JSON-RPC 2.0 request on the wire.
class RequestEnvelope(TypedDict):
    jsonrpc: Literal["2.0"]
    id: RequestId
    method: MethodName
    params: NotRequired[Any]

# A JSON-RPC 2.0 response. Exactly one of result/error is present (asserted by both implementations, not expressible here without oneOf).
class ResponseEnvelope(TypedDict):
    jsonrpc: Literal["2.0"]
    id: RequestId
    result: NotRequired[Any]
    error: NotRequired[ErrorObject]

# A JSON-RPC 2.0 notification (no id, no response).
class NotificationEnvelope(TypedDict):
    jsonrpc: Literal["2.0"]
    method: NotificationName
    params: NotRequired[Any]

REQUEST_METHODS: tuple[str, ...] = ("handshake", "ping", "shutdown", "health", "ledger.append", "ledger.query", "loop.start", "loop.stop", "loop.status",)
NOTIFICATION_METHODS: tuple[str, ...] = ("$/cancel",)

# Runtime pairing of method name -> params/result TypedDicts.
METHOD_CONTRACT: dict[str, dict[str, Any]] = {
    "handshake": {"params": HandshakeParams, "result": HandshakeResult},
    "ping": {"params": PingParams, "result": PingResult},
    "shutdown": {"params": ShutdownParams, "result": ShutdownResult},
    "health": {"params": HealthParams, "result": HealthResult},
    "ledger.append": {"params": LedgerAppendParams, "result": LedgerAppendResult},
    "ledger.query": {"params": LedgerQueryParams, "result": LedgerQueryResult},
    "loop.start": {"params": LoopStartParams, "result": LoopStatusResult},
    "loop.stop": {"params": LoopStopParams, "result": LoopStatusResult},
    "loop.status": {"params": LoopStatusParams, "result": LoopStatusResult},
}
