// Generated by scripts/generate-bus-types.mjs from shared/schema/. DO NOT EDIT.
// FR-M32-09: extension, webview, Simulation Core and the production
// sidecar all consume these types; npm run check:contracts fails on drift.

export const PROTOCOL_VERSION = 1 as const;

/** Standard JSON-RPC 2.0 codes plus the Meridian -320xx range. */
export const ErrorCode = {
  PARSE_ERROR: -32700,
  INVALID_REQUEST: -32600,
  METHOD_NOT_FOUND: -32601,
  INVALID_PARAMS: -32602,
  INTERNAL_ERROR: -32603,
  NOT_IMPLEMENTED: -32001,
  PROTOCOL_MISMATCH: -32002,
} as const;
export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface HandshakeParams {
  /** Must equal PROTOCOL_VERSION or the sidecar refuses with PROTOCOL_MISMATCH. */
  "protocolVersion": number;
  /** e.g. meridian-loom-extension */
  "client": string;
}

export interface Capabilities {
  "methods": string[];
  "framing": "ndjson";
}

export interface HandshakeResult {
  "protocolVersion": number;
  "coreVersion": string;
  "pythonVersion": string;
  "capabilities": Capabilities;
}

export type PingParams = Record<string, never>;

export interface PingResult {
  "pong": true;
  /** Monotonic per-process ping counter. */
  "seq": number;
  "uptimeSeconds": number;
}

export interface ShutdownParams {
  "reason"?: string;
}

export interface ShutdownResult {
  "ok": true;
}

export type HealthParams = Record<string, never>;

export interface HealthResult {
  "status": "ok" | "degraded" | "shutting-down";
  "uptimeSeconds": number;
  "pid": number;
  "activeLoops": number;
}

export interface LedgerAppendParams {
  "entryType": string;
  "payload": Record<string, unknown>;
  /** Simulation Core marker (FR-M32-02); absent means false. */
  "simulated"?: boolean;
}

export interface LedgerAppendResult {
  "sequence": number;
  /** Hash of this entry, chained from the previous (FR-M10-02). */
  "hash": string;
}

export interface LedgerQueryParams {
  "entryType"?: string;
  "fromSequence"?: number;
  "limit"?: number;
}

export interface LedgerEntry {
  "sequence": number;
  "entryType": string;
  "hash": string;
  "previousHash": string;
  /** ISO 8601 UTC. */
  "timestamp": string;
  "simulated": boolean;
  "payload": Record<string, unknown>;
}

export interface LedgerQueryResult {
  "entries": LedgerEntry[];
}

/** The six canonical loops (FR-M4-03). */
export type LoopKind = "L1-micro" | "L2-task" | "L3-phase" | "L4-delivery" | "L5-learning" | "L6-organisation";

export type LoopState = "pending" | "running" | "paused" | "blocked" | "completed" | "failed" | "aborted";

export interface LoopStartParams {
  "loopId": string;
  "storyId": string;
  "kind": LoopKind;
}

export interface LoopStopParams {
  "loopId": string;
  "reason"?: string;
}

export interface LoopStatusParams {
  "loopId": string;
}

export interface LoopStatusResult {
  "loopId": string;
  "kind": LoopKind;
  "state": LoopState;
  "iteration": number;
  /** Durable checkpoint id (FR-M4-05), present once the loop has checkpointed. */
  "lastCheckpoint"?: string;
}

export interface CancelParams {
  "id": RequestId;
}

/** Every request/response method on the bus. */
export type MethodName = "handshake" | "ping" | "shutdown" | "health" | "ledger.append" | "ledger.query" | "loop.start" | "loop.stop" | "loop.status";

/** Every notification method on the bus. */
export type NotificationName = "$/cancel";

/** JSON-RPC 2.0 request id. The extension allocates monotonically increasing integers; strings are accepted for forwards compatibility. */
export type RequestId = number | string;

/** JSON-RPC 2.0 error object. code is one of ErrorCode; data carries structured detail (e.g. expected/actual for PROTOCOL_MISMATCH). */
export interface ErrorObject {
  "code": number;
  "message": string;
  "data"?: unknown;
}

/** A JSON-RPC 2.0 request on the wire. */
export interface RequestEnvelope {
  "jsonrpc": "2.0";
  "id": RequestId;
  "method": MethodName;
  "params"?: unknown;
}

/** A JSON-RPC 2.0 response. Exactly one of result/error is present (asserted by both implementations, not expressible here without oneOf). */
export interface ResponseEnvelope {
  "jsonrpc": "2.0";
  "id": RequestId;
  "result"?: unknown;
  "error"?: ErrorObject;
}

/** A JSON-RPC 2.0 notification (no id, no response). */
export interface NotificationEnvelope {
  "jsonrpc": "2.0";
  "method": NotificationName;
  "params"?: unknown;
}

/** Params/result pairing for every request method. */
export interface MethodMap {
  "handshake": { params: HandshakeParams; result: HandshakeResult };
  "ping": { params: PingParams; result: PingResult };
  "shutdown": { params: ShutdownParams; result: ShutdownResult };
  "health": { params: HealthParams; result: HealthResult };
  "ledger.append": { params: LedgerAppendParams; result: LedgerAppendResult };
  "ledger.query": { params: LedgerQueryParams; result: LedgerQueryResult };
  "loop.start": { params: LoopStartParams; result: LoopStatusResult };
  "loop.stop": { params: LoopStopParams; result: LoopStatusResult };
  "loop.status": { params: LoopStatusParams; result: LoopStatusResult };
}
export type RequestMethod = keyof MethodMap;

export interface NotificationMap {
  "$/cancel": CancelParams;
}
