// Generated by scripts/generate-bus-types.mjs from shared/schema/. DO NOT EDIT.
// FR-M32-09: extension, webview, Simulation Core and the production
// sidecar all consume these types; npm run check:contracts fails on drift.

export const PROTOCOL_VERSION = 1 as const;

/** Standard JSON-RPC 2.0 codes plus the Meridian -320xx range. */
export const ErrorCode = {
  PARSE_ERROR: -32700,
  INVALID_REQUEST: -32600,
  METHOD_NOT_FOUND: -32601,
  INVALID_PARAMS: -32602,
  INTERNAL_ERROR: -32603,
  NOT_IMPLEMENTED: -32001,
  PROTOCOL_MISMATCH: -32002,
  TIER_DISABLED: -32003,
  LEDGER_UNAVAILABLE: -32004,
} as const;
export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface HandshakeParams {
  /** Must equal PROTOCOL_VERSION or the sidecar refuses with PROTOCOL_MISMATCH. */
  "protocolVersion": number;
  /** e.g. meridian-loom-extension */
  "client": string;
  /** FR-M36-05: tiers enabled in this workspace (from the meridian.tiers setting). Absent means the sidecar default: flight-recorder only. The base tier is always enabled regardless. */
  "tiers"?: TierName[];
  /** Absolute workspace path. The ledger lives at <workspaceDir>/.meridian/ledger (FR-M10-01). Absent: ledger RPCs answer LEDGER_UNAVAILABLE until configured. */
  "workspaceDir"?: string;
  /** Base64-encoded 32-byte Ed25519 seed (FR-M10-04), sourced from the extension host's OS-keychain-backed SecretStorage (SEC-06) and provisioned over this handshake. Held in memory only; never persisted to disk or written into the ledger. Absent: the sidecar signs tree heads with an ephemeral key and doctor reports the missing keychain key. */
  "ledgerSigningKey"?: string;
}

export interface Capabilities {
  "methods": string[];
  "framing": "ndjson";
}

export interface HandshakeResult {
  "protocolVersion": number;
  "coreVersion": string;
  "pythonVersion": string;
  "capabilities": Capabilities;
}

export type PingParams = Record<string, never>;

export interface PingResult {
  "pong": true;
  /** Monotonic per-process ping counter. */
  "seq": number;
  "uptimeSeconds": number;
}

export interface ShutdownParams {
  "reason"?: string;
}

export interface ShutdownResult {
  "ok": true;
}

export type HealthParams = Record<string, never>;

export interface HealthResult {
  "status": "ok" | "degraded" | "shutting-down";
  "uptimeSeconds": number;
  "pid": number;
  "activeLoops": number;
}

/** Outcome of one doctor check. warn means usable but degraded or not yet installed; fail means broken and actionable. */
export type DoctorCheckStatus = "pass" | "warn" | "fail";

export interface DoctorCheck {
  /** Stable machine id, e.g. interpreter, sidecar, ledger. */
  "id": string;
  /** Human-readable check name. */
  "name": string;
  "status": DoctorCheckStatus;
  /** What was found, in one line. */
  "detail": string;
  /** Actionable fix; always present on warn and fail. */
  "remediation"?: string;
}

export interface DoctorRunParams {
  /** Subset of check ids to run; absent runs the whole registry. */
  "checks"?: string[];
  /** Absolute path of the workspace folder; the git-hooks check needs it. */
  "workspaceDir"?: string;
}

export interface DoctorRunResult {
  /** Worst status across all checks: fail > warn > pass. */
  "status": DoctorCheckStatus;
  "checks": DoctorCheck[];
}

export interface LedgerAppendParams {
  "entryType": string;
  "payload": Record<string, unknown>;
  /** Simulation Core marker (FR-M32-02); absent means false. */
  "simulated"?: boolean;
}

export interface LedgerAppendResult {
  "sequence": number;
  /** Hash of this entry, chained from the previous (FR-M10-02). */
  "hash": string;
}

export interface LedgerQueryParams {
  "entryType"?: string;
  "fromSequence"?: number;
  "limit"?: number;
}

export interface LedgerEntry {
  "sequence": number;
  "entryType": string;
  "hash": string;
  "previousHash": string;
  /** ISO 8601 UTC. */
  "timestamp": string;
  "simulated": boolean;
  "payload": Record<string, unknown>;
}

export interface LedgerQueryResult {
  "entries": LedgerEntry[];
}

/** The six canonical loops (FR-M4-03). */
export type LoopKind = "L1-micro" | "L2-task" | "L3-phase" | "L4-delivery" | "L5-learning" | "L6-organisation";

export type LoopState = "pending" | "running" | "paused" | "blocked" | "completed" | "failed" | "aborted";

export interface LoopStartParams {
  "loopId": string;
  "storyId": string;
  "kind": LoopKind;
}

export interface LoopStopParams {
  "loopId": string;
  "reason"?: string;
}

export interface LoopStatusParams {
  "loopId": string;
}

export interface LoopStatusResult {
  "loopId": string;
  "kind": LoopKind;
  "state": LoopState;
  "iteration": number;
  /** Durable checkpoint id (FR-M4-05), present once the loop has checkpointed. */
  "lastCheckpoint"?: string;
}

export interface CancelParams {
  "id": RequestId;
}

export interface GateEvaluateParams {
  "storyId": string;
  /** Gate name, e.g. security, review (FR-M12-01). */
  "gate": string;
}

export interface GateEvaluateResult {
  "decision": "pass" | "block";
  "reasons"?: string[];
}

export interface SteerSendParams {
  "sessionId": string;
  "message": string;
}

export interface SteerSendResult {
  "accepted": boolean;
}

export interface TrustSummaryParams {
  "agentId"?: string;
}

export interface TrustSummaryResult {
  "entries": Record<string, unknown>[];
}

export interface TierSetParams {
  "tiers": TierName[];
}

/** Every request/response method on the bus. */
export type MethodName = "handshake" | "ping" | "shutdown" | "health" | "doctor/run" | "ledger.append" | "ledger.query" | "loop.start" | "loop.stop" | "loop.status" | "gate.evaluate" | "steer.send" | "trust.summary";

/** Every notification method on the bus. */
export type NotificationName = "tiers/set" | "$/cancel";

/** JSON-RPC 2.0 request id. The extension allocates monotonically increasing integers; strings are accepted for forwards compatibility. */
export type RequestId = number | string;

/** JSON-RPC 2.0 error object. code is one of ErrorCode; data carries structured detail (e.g. expected/actual for PROTOCOL_MISMATCH). */
export interface ErrorObject {
  "code": number;
  "message": string;
  "data"?: unknown;
}

/** A JSON-RPC 2.0 request on the wire. */
export interface RequestEnvelope {
  "jsonrpc": "2.0";
  "id": RequestId;
  "method": MethodName;
  "params"?: unknown;
}

/** A JSON-RPC 2.0 response. Exactly one of result/error is present (asserted by both implementations, not expressible here without oneOf). */
export interface ResponseEnvelope {
  "jsonrpc": "2.0";
  "id": RequestId;
  "result"?: unknown;
  "error"?: ErrorObject;
}

/** A JSON-RPC 2.0 notification (no id, no response). */
export interface NotificationEnvelope {
  "jsonrpc": "2.0";
  "method": NotificationName;
  "params"?: unknown;
}

/** One capability in the registry (FR-M36-05). rpcMethods are the bus methods the capability owns. */
export interface CapabilityDefinition {
  "id": string;
  "tier": TierName;
  "description": string;
  "rpcMethods": string[];
}

/** The three product tiers (FR-M36-05), base first. */
export type TierName = "flight-recorder" | "governor" | "orchestra";

/** FR-M36-05: all tiers, base first. */
export const TIERS = ["flight-recorder","governor","orchestra"] as const;

/** FR-M36-05: enabled tiers when nothing is configured — Flight Recorder only. */
export const DEFAULT_ENABLED_TIERS: readonly TierName[] = ["flight-recorder"];

/** FR-M36-05: capability registry; every capability is owned by exactly one tier. */
export const CAPABILITIES: readonly CapabilityDefinition[] = [{"id":"recorder.lifecycle","tier":"flight-recorder","description":"Sidecar lifecycle: handshake, heartbeat, shutdown, health. Always enabled — the base tier cannot be turned off.","rpcMethods":["handshake","ping","shutdown","health"]},{"id":"recorder.doctor","tier":"flight-recorder","description":"Self-diagnostic check registry (FR-M30-01).","rpcMethods":["doctor/run"]},{"id":"recorder.ledger","tier":"flight-recorder","description":"Append-only provenance ledger and queries (FR-M10-01, FR-M10-12; F0 Workstream B).","rpcMethods":["ledger.append","ledger.query"]},{"id":"governor.gates","tier":"governor","description":"Policy gates over external and hosted agent work (FR-M12-01; F1). Stub RPC until F1 lands it.","rpcMethods":["gate.evaluate"]},{"id":"governor.steer","tier":"governor","description":"Steer and clarifying questions into running sessions (FR-M25-01/02; F1). Stub RPC until F1 lands it.","rpcMethods":["steer.send"]},{"id":"governor.trust","tier":"governor","description":"Trust and rejection analytics (FR-M37-*; F0 subset/F1 full). Stub RPC until it lands.","rpcMethods":["trust.summary"]},{"id":"orchestra.loops","tier":"orchestra","description":"The six canonical loops (FR-M4-03; F3). Stub RPCs until F3 lands them.","rpcMethods":["loop.start","loop.stop","loop.status"]}];

/** Params/result pairing for every request method. */
export interface MethodMap {
  "handshake": { params: HandshakeParams; result: HandshakeResult };
  "ping": { params: PingParams; result: PingResult };
  "shutdown": { params: ShutdownParams; result: ShutdownResult };
  "health": { params: HealthParams; result: HealthResult };
  "doctor/run": { params: DoctorRunParams; result: DoctorRunResult };
  "ledger.append": { params: LedgerAppendParams; result: LedgerAppendResult };
  "ledger.query": { params: LedgerQueryParams; result: LedgerQueryResult };
  "loop.start": { params: LoopStartParams; result: LoopStatusResult };
  "loop.stop": { params: LoopStopParams; result: LoopStatusResult };
  "loop.status": { params: LoopStatusParams; result: LoopStatusResult };
  "gate.evaluate": { params: GateEvaluateParams; result: GateEvaluateResult };
  "steer.send": { params: SteerSendParams; result: SteerSendResult };
  "trust.summary": { params: TrustSummaryParams; result: TrustSummaryResult };
}
export type RequestMethod = keyof MethodMap;

/** Runtime list of every request method (for tier/ownership checks). */
export const REQUEST_METHODS = ["handshake","ping","shutdown","health","doctor/run","ledger.append","ledger.query","loop.start","loop.stop","loop.status","gate.evaluate","steer.send","trust.summary"] as const;

/** Runtime list of every notification method. */
export const NOTIFICATION_METHODS = ["tiers/set","$/cancel"] as const;

export interface NotificationMap {
  "tiers/set": TierSetParams;
  "$/cancel": CancelParams;
}
