import { useMemo, useState } from 'react';
import type { AttribBlameResult, AttribDiffResult, AttribSymbolResult } from '../../../../shared/ts/bus-types';
import { GraphCanvas } from './GraphCanvas';
import { svgExport, type DiagramModel } from './model';
import type { ModelingStudioProps } from './types';
import s from './modeling.module.css';

/** File membership and commit authorship are factual; call relationships are not inferred from blame. */
export function attributionModel(data: AttribBlameResult, detail: 'modules'|'files', author: string): DiagramModel {
  const paths = [...new Set(data.lines.filter(line=>!author||line.authorName===author).map(line=>line.path))];
  const folders = [...new Set(paths.map(path=>path.includes('/')?path.slice(0,path.lastIndexOf('/')):'(root)'))];
  const nodes: DiagramModel['nodes'] = folders.slice(0,100).map((folder,index)=>({id:`folder:${folder}`,label:folder,kind:'directory',detail:`Tracked source grouping at ${data.ref}.`,x:30+index%3*240,y:50+Math.floor(index/3)*140}));
  const edges: DiagramModel['edges'] = [];
  if(detail==='files') for(const path of paths.slice(0,Math.max(0,300-nodes.length))){
    const folder=path.includes('/')?path.slice(0,path.lastIndexOf('/')):'(root)'; if(!nodes.some(node=>node.id===`folder:${folder}`))continue;
    const lines=data.lines.filter(line=>line.path===path);const recent=[...lines].sort((a,b)=>b.authorTime.localeCompare(a.authorTime))[0];
    const index=nodes.length;nodes.push({id:`file:${path}`,label:path.split('/').at(-1)!,kind:'file',source:path,owner:recent?.authorName,detail:`${lines.length} recorded lines · ${new Set(lines.map(line=>line.commit)).size} introducing commits · most recent line introduction ${recent?.authorTime ?? 'unknown'}`,x:30+index%3*240,y:50+Math.floor(index/3)*140});
    edges.push({id:`membership:${path}`,from:`folder:${folder}`,to:`file:${path}`,label:'contains',kind:'relation'});
  }
  return {schemaVersion:1,type:'Repository attribution map',nodes,edges,notes:`Source: attrib/blame at ${data.ref}. Edges show directory membership, not dependencies. Rendered subset: ${nodes.length} nodes.`};
}
export function CodeMapStudio({client,ready,workspaceDir,onNavigate}:ModelingStudioProps){
  const [paths,setPaths]=useState('');const [ref,setRef]=useState('HEAD');const [data,setData]=useState<AttribBlameResult>();const [diff,setDiff]=useState<AttribDiffResult>();
  const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [level,setLevel]=useState<'modules'|'files'>('files');const [author,setAuthor]=useState('');const [query,setQuery]=useState('');const [selected,setSelected]=useState<string|null>(null);const [impact,setImpact]=useState(false);const [line,setLine]=useState(1);const [symbol,setSymbol]=useState<AttribSymbolResult>();
  const model=useMemo(()=>data?attributionModel(data,level,author):{schemaVersion:1 as const,type:'Repository attribution map',nodes:[],edges:[],notes:''},[data,level,author]);
  const node=model.nodes.find(node=>node.id===selected);
  const changed=new Set(diff?.files.map(file=>file.path)??[]);
  const shown=model.nodes.filter(node=>(!query||`${node.label} ${node.source??''} ${node.owner??''}`.toLowerCase().includes(query.toLowerCase()))&&(!impact||!!node.source&&changed.has(node.source)));
  const load=async()=>{setBusy(true);setError('');setSymbol(undefined);try{if(!workspaceDir)throw new Error('Open a repository to load source attribution.');const result=await client.request('attrib/blame',{repoPath:workspaceDir,ref:ref.trim()||'HEAD',...(paths.trim()?{paths:paths.split(/[,\n]/).map(value=>value.trim()).filter(Boolean)}:{})});setData(result);setSelected(null);setAuthor('');setDiff(undefined);setImpact(false);}catch(cause){setError(cause instanceof Error?cause.message:String(cause));}finally{setBusy(false);}};
  const request=async(action:()=>Promise<void>)=>{setBusy(true);setError('');try{await action();}catch(cause){setError(cause instanceof Error?cause.message:String(cause));}finally{setBusy(false);}};
  return <div className={s.page}><header className={s.header}><div><p className={s.eyebrow}>Intelligence / CodeMap</p><h1>A map with the source attached.</h1><p>Explore repository structure and line authorship, isolate an author, inspect introducing commits, and look up the symbol at an exact source line.</p></div><button className={s.button} onClick={()=>onNavigate('comprehension')}>Create a handover note</button></header>
    <div className={s.notice}>This map is built from real Git attribution. Relationships show directory membership. Semantic dependency extraction, predicted blast radius, reuse detection, and rework heat require a CodeMap service that is not connected.</div>
    <form className={s.toolbar} onSubmit={event=>{event.preventDefault();void load();}}><label className={`${s.field} ${s.wide}`}>Source paths<input className={s.input} value={paths} onChange={event=>setPaths(event.target.value)} placeholder="src/app.ts, src/domain.ts · blank includes tracked files"/></label><label className={s.field}>Git reference<input className={s.input} value={ref} onChange={event=>setRef(event.target.value)} placeholder="HEAD"/></label><button className={s.primary} disabled={busy||!ready||!workspaceDir}>{busy?'Loading…':'Load repository map'}</button></form>
    {error&&<div className={s.error} role="alert">{error}</div>}
    {!data?<div className={`${s.panel} ${s.empty}`}>Choose the source paths and reference to map. A smaller path selection keeps exploration focused.</div>:<>
      <div className={s.toolbar}><label className={`${s.field} ${s.wide}`}>Search map<input className={s.input} value={query} onChange={event=>setQuery(event.target.value)} placeholder="File, directory, author…"/></label><label className={s.field}>Detail level<select className={s.select} value={level} onChange={event=>{setLevel(event.target.value as typeof level);setSelected(null);}}><option value="modules">Directories</option><option value="files">Files</option></select></label><label className={s.field}>Author overlay<select className={s.select} value={author} onChange={event=>{setAuthor(event.target.value);setSelected(null);}}><option value="">All authors</option>{[...new Set(data.lines.map(line=>line.authorName))].sort().map(name=><option key={name}>{name}</option>)}</select></label><button className={s.button} disabled={busy||!workspaceDir} onClick={()=>void request(async()=>{setDiff(await client.request('attrib/diff',{repoPath:workspaceDir!,base:data.ref,...(paths.trim()?{paths:paths.split(/[,\n]/).map(value=>value.trim()).filter(Boolean)}:{})}));setImpact(true);})}>Overlay worktree changes</button><button className={s.button} onClick={()=>client.notify({type:'download',fileName:'meridian-attribution-map.svg',mimeType:'image/svg+xml',content:svgExport(model)})}>Export SVG</button></div>
      <p className={s.muted}>{data.repoPath} · {data.ref} · {data.lines.length.toLocaleString()} attributed lines · {new Set(data.lines.map(line=>line.path)).size} files. Canvas displays up to 100 directories and 300 total nodes; narrow paths to explore omitted files.</p>
      {diff&&<div className={s.notice}>{diff.files.length} changed files relative to {diff.base??'HEAD'}. This is an observed change overlay, not predicted impact. <button className={s.button} aria-pressed={impact} onClick={()=>setImpact(value=>!value)}>{impact?'Show all nodes':'Highlight changed files'}</button></div>}
      <div className={s.workspace}><GraphCanvas model={model} selected={selected} onSelect={id=>{setSelected(id);setLine(1);setSymbol(undefined);}} highlighted={query||impact?new Set(shown.map(node=>node.id)):undefined}/><aside className={`${s.panel} ${s.inspector}`}><h2>Source inspector</h2>{node?<><strong>{node.label}</strong><p className={s.muted}>{node.source??node.kind}</p><p className={s.muted}>{node.detail}</p>{node.source&&<><label className={s.field}>Source line<input className={s.input} type="number" min="1" value={line} onChange={event=>setLine(Number(event.target.value))}/></label><button className={s.button} disabled={busy||!Number.isInteger(line)||line<1} onClick={()=>void request(async()=>{setSymbol(await client.request('attrib/symbol',{repoPath:workspaceDir!,path:node.source!,line}));})}>Inspect current symbol</button>{symbol&&<div className={s.notice}><strong>{symbol.symbol??'No enclosing symbol detected'}</strong><p>{symbol.language??'Unsupported language'} · Current workspace source. Symbol lookup is not pinned to {data.ref}.</p></div>}{data.lines.filter(item=>item.path===node.source&&item.line===line).map(item=><div className={s.notice} key={item.line}><strong>{item.authorName}</strong><p>{item.authorTime}</p><code>{item.commit.slice(0,12)}</code><pre className={s.pre}>{item.content}</pre></div>)}</>}</>:<p className={s.muted}>Select a file or directory in the canvas or the list below.</p>}</aside></div>
      <section className={s.panel}><h2>Map index · {shown.length} visible nodes</h2>{shown.map(item=><div className={s.row} key={item.id}><div><strong>{item.source??item.label}</strong><p>{item.kind}{item.owner?` · ${item.owner}`:''}{item.source&&changed.has(item.source)?' · Worktree changed':''}</p></div><button className={s.button} aria-label={`Inspect ${item.source??item.label}`} onClick={()=>{setSelected(item.id);setSymbol(undefined);}}>Inspect</button></div>)}{!shown.length&&<p className={s.empty}>No nodes match these filters.</p>}</section>
    </>}
  </div>;
}
