import { useState } from 'react';
import type { AttribBlameResult, AttribSymbolResult } from '../../../../shared/ts/bus-types';
import type { StudioDocument } from '../../../../shared/ts/studio';
import { Dialog } from '../Dialog';
import type { ModelingStudioProps } from './types';
import s from './modeling.module.css';
interface ComprehensionNote {schemaVersion:1;path:string;ref:string;line:number;symbol:string;purpose:string;contracts:string;risks:string;questions:string;handover:string;owner:string;evidence:string;review:'draft'|'reviewed'}
const empty=():ComprehensionNote=>({schemaVersion:1,path:'',ref:'HEAD',line:1,symbol:'',purpose:'',contracts:'',risks:'',questions:'',handover:'',owner:'',evidence:'',review:'draft'});
export function ComprehensionStudio({client,ready,workspaceDir,controller,onNavigate}:ModelingStudioProps){
  const [note,setNote]=useState(empty);const [title,setTitle]=useState('');const [document,setDocument]=useState<StudioDocument>();const [data,setData]=useState<AttribBlameResult>();const [symbol,setSymbol]=useState<AttribSymbolResult>();const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [query,setQuery]=useState('');const [dirty,setDirty]=useState(false);const [confirm,setConfirm]=useState<StudioDocument|'new'|'remove'>();
  const docs=(controller.snapshot?.documents??[]).filter(item=>item.kind==='comprehension'&&`${item.title} ${item.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase()));
  const update=(patch:Partial<ComprehensionNote>)=>{setNote({...note,...patch});setDirty(true);setNotice('');};
  const load=(item:StudioDocument)=>{try{const value=JSON.parse(item.body) as ComprehensionNote;if(value.schemaVersion!==1||Object.keys(empty()).some(key=>key!=='schemaVersion'&&typeof value[key as keyof ComprehensionNote]!==typeof empty()[key as keyof ComprehensionNote]))throw new Error('This document is not a supported comprehension note.');setNote(value);setDocument(item);setTitle(item.title);setData(undefined);setSymbol(undefined);setDirty(false);setNotice(`Loaded revision ${item.version}. Source evidence can be refreshed below.`);setError('');}catch(cause){setError(String(cause));}};
  const reset=()=>{setNote(empty());setTitle('');setDocument(undefined);setData(undefined);setSymbol(undefined);setDirty(false);setNotice('');};
  const inspect=async()=>{setBusy(true);setError('');try{if(!workspaceDir)throw new Error('Open a repository to inspect source.');if(!note.path.trim())throw new Error('Enter a repository-relative source path.');if(!Number.isInteger(note.line)||note.line<1)throw new Error('Source line must be a positive integer.');const [blame,enclosing]=await Promise.allSettled([client.request('attrib/blame',{repoPath:workspaceDir,paths:[note.path.trim()],ref:note.ref.trim()||'HEAD'}),client.request('attrib/symbol',{repoPath:workspaceDir,path:note.path.trim(),line:note.line})]);if(blame.status==='fulfilled')setData(blame.value);if(enclosing.status==='fulfilled'){setSymbol(enclosing.value);if(enclosing.value.symbol)update({symbol:enclosing.value.symbol});}const errors=[blame,enclosing].filter(item=>item.status==='rejected').map(item=>(item as PromiseRejectedResult).reason?.message??String((item as PromiseRejectedResult).reason));if(errors.length)setError(errors.join(' · '));}finally{setBusy(false);}};
  const save=async()=>{setError('');try{if(!title.trim()||!note.purpose.trim())throw new Error('Add a title and a purpose before saving.');if(note.review==='reviewed'&&!note.evidence.trim())throw new Error('A reviewed note needs explicit evidence references.');const next=await controller.execute('document/save',{document:{id:document?.id,kind:'comprehension',title:title.trim(),body:JSON.stringify(note),tags:[note.review,...(note.path?[note.path]:[])],expectedVersion:document?.version}});const stored=next.documents?.find(item=>document?item.id===document.id:item.kind==='comprehension'&&item.body===JSON.stringify(note));if(stored)setDocument(stored);setDirty(false);setNotice('Comprehension note saved with its evidence and review state.');}catch(cause){setError(cause instanceof Error?cause.message:String(cause));}};
  const markdown=()=>[`# ${title||'Code comprehension'}`,`Source: ${note.path||'Not linked'} @ ${note.ref}, line ${note.line}`,`Symbol: ${note.symbol||'Not identified'}`,`Owner: ${note.owner||'Unassigned'}`,`Review: ${note.review}`,`## Purpose\n${note.purpose}`,`## Contracts and dependencies\n${note.contracts}`,`## Risks and constraints\n${note.risks}`,`## Open questions\n${note.questions}`,`## Handover checklist\n${note.handover}`,`## Evidence\n${note.evidence}`].join('\n\n');
  return <div className={s.page}><header className={s.header}><div><p className={s.eyebrow}>Intelligence / Comprehension studio</p><h1>Turn understanding into a useful handover.</h1><p>Inspect source ownership and symbols. Keep a reviewed explanation of purpose, contracts, risks, questions, and the next maintainer’s checklist.</p></div><span className={s.badge}>{dirty?'Unsaved changes':document?`Revision ${document.version}`:'New note'}</span></header>
    <div className={s.notice}>Source evidence comes from Git and symbol lookup. Explanations and review states are authored by you. Automated comprehension, semantic memory retrieval, and freshness scoring are not connected.</div>
    {error&&<div className={s.error} role="alert">{error}</div>}{notice&&<div className={s.notice} role="status">{notice}</div>}
    <div className={s.toolbar}><label className={`${s.field} ${s.wide}`}>Search handover notes<input className={s.input} value={query} onChange={event=>setQuery(event.target.value)} placeholder="Title, source, review state…"/></label><label className={`${s.field} ${s.wide}`}>Saved handover<select className={s.select} value={document?.id??''} onChange={event=>{const item=docs.find(item=>item.id===event.target.value);if(item){if(dirty)setConfirm(item);else load(item);}}}><option value="">Choose a note…</option>{docs.map(item=><option key={item.id} value={item.id}>{item.title} · v{item.version}</option>)}</select></label><button className={s.button} onClick={()=>dirty?setConfirm('new'):reset()}>New handover</button><button className={s.primary} disabled={controller.busy||!controller.snapshot?.capabilities.workspaceOpen} onClick={()=>void save()}>Save handover</button><button className={s.button} onClick={()=>client.notify({type:'download',fileName:'meridian-comprehension.md',mimeType:'text/plain',content:markdown()})}>Export Markdown</button>{document&&<button className={s.danger} onClick={()=>setConfirm('remove')}>Delete handover</button>}</div>
    <section className={s.panel}><h2>Start with the source</h2><div className={s.grid}><label className={s.field}>Source path<input className={s.input} value={note.path} onChange={event=>{update({path:event.target.value});setData(undefined);setSymbol(undefined);}} placeholder="src/domain/service.ts"/></label><label className={s.field}>Source reference<input className={s.input} value={note.ref} onChange={event=>update({ref:event.target.value})}/></label><label className={s.field}>Source line<input className={s.input} type="number" min="1" value={note.line} onChange={event=>update({line:Number(event.target.value)})}/></label></div><div className={s.toolbar} style={{marginTop:15}}><button className={s.button} disabled={busy||!ready||!workspaceDir} onClick={()=>void inspect()}>{busy?'Inspecting…':'Inspect source evidence'}</button><button className={s.button} onClick={()=>onNavigate('codemap')}>Explore CodeMap</button><button className={s.button} onClick={()=>onNavigate('learning')}>Review learning memory</button></div>
      {symbol&&<p className={s.notice}>Current workspace symbol: <strong>{symbol.symbol??'Not detected'}</strong> · {symbol.language??'Language unsupported'}. Symbol lookup uses the current file; attribution uses {data?.ref??note.ref}.</p>}
      {data&&<div className={s.two} style={{marginTop:20}}><div><h3>Introducing line authors</h3>{Array.from(new Set(data.lines.map(line=>line.authorName))).map(name=><div key={name} className={s.row}><div><strong>{name}</strong><p>{data.lines.filter(line=>line.authorName===name).length} attributed lines</p></div><button className={s.button} aria-label={`Assign ${name} as handover owner`} onClick={()=>update({owner:name})}>Set owner</button></div>)}{!data.lines.length&&<p className={s.muted}>No tracked source lines were returned for this path and reference.</p>}<p className={s.muted}>Line authorship does not prove current maintenance responsibility.</p></div><div><h3>Source context · {data.ref}</h3><pre className={s.pre}>{data.lines.filter(line=>line.path===note.path&&Math.abs(line.line-note.line)<=8).map(line=>`${line.line}  ${line.content}`).join('\n')||'No source context at this line.'}</pre><button className={s.button} style={{marginTop:10}} onClick={()=>{const commits=[...new Set(data.lines.filter(line=>Math.abs(line.line-note.line)<=8).map(line=>line.commit))];update({evidence:[note.evidence,`${data.repoPath}: ${note.path} @ ${data.ref}, line ${note.line}. Introducing commits: ${commits.join(', ')||'none returned'}.`].filter(Boolean).join('\n')});}}>Attach this source evidence</button></div></div>}
    </section>
    <div className={s.two}><label className={s.field}>Handover title<input className={s.input} maxLength={160} value={title} onChange={event=>{setTitle(event.target.value);setDirty(true);}} placeholder="How checkout idempotency works"/></label><label className={s.field}>Responsible owner<input className={s.input} value={note.owner} onChange={event=>update({owner:event.target.value})} placeholder="Person or team"/></label></div>
    <div className={s.grid}>{([
      ['purpose','Purpose and behavior','What does this module do? What are its invariants?'],['contracts','Contracts and dependencies','Inputs, outputs, failure modes, dependencies, and caller expectations.'],['risks','Risks and constraints','Security boundaries, concurrency, performance, migrations, and fragile assumptions.'],['questions','Open questions','Unknown behavior, missing evidence, and decisions needing an owner.'],['handover','Handover checklist','How to run, test, diagnose, and change this code safely.'],['evidence','Evidence references','Source references, tests, ADRs, ledger sequences, and reviewed memory.'],
    ] as const).map(([key,label,placeholder])=><label className={s.field} key={key}>{label}<textarea className={s.textarea} value={note[key]} onChange={event=>update({[key]:event.target.value})} placeholder={placeholder}/></label>)}</div>
    <div className={s.two}><label className={s.field}>Linked symbol<input className={s.input} value={note.symbol} onChange={event=>update({symbol:event.target.value})}/></label><label className={s.field}>Human review state<select className={s.select} value={note.review} onChange={event=>update({review:event.target.value as 'draft'|'reviewed'})}><option value="draft">Draft · needs review</option><option value="reviewed">Reviewed with cited evidence</option></select></label></div>
    {confirm&&<Dialog title={confirm==='remove'?'Delete this handover?':'Discard unsaved handover changes?'} onClose={()=>setConfirm(undefined)}><div className={s.toolbar}><button className={s.button} onClick={()=>setConfirm(undefined)}>Keep editing</button><button className={s.danger} onClick={()=>void(async()=>{try{if(confirm==='remove'&&document){await controller.execute('document/remove',{id:document.id,expectedVersion:document.version});reset();}else if(confirm==='new')reset();else if(typeof confirm==='object')load(confirm);setConfirm(undefined);}catch(cause){setError(String(cause));}})()}>{confirm==='remove'?'Delete saved handover':'Discard and continue'}</button></div></Dialog>}
  </div>;
}
