import { useState } from 'react';
import type { StudioDocument } from '../../../../shared/ts/studio';
import { Dialog } from '../Dialog';
import { GraphCanvas } from './GraphCanvas';
import { DIAGRAM_TYPES, layoutModel, mermaidExport, parseModel, svgExport, template, tracePath, type DiagramKind, type DiagramModel } from './model';
import type { ModelingStudioProps } from './types';
import s from './modeling.module.css';

const HEADINGS = {
  architecture: ['Architecture & C4', 'Give the system a shared shape.', 'Move from context to containers and components. Attach contracts, decisions, owners, and source paths to the model.'],
  uml: ['UML studio', 'Make relationships visible.', 'Seven diagram types share an editable model, explicit relationships, a keyboard-accessible canvas, and portable exports.'],
  flow: ['Flow diagrams', 'Follow every possible outcome.', 'Describe acceptance criteria, data movement, delivery, and escalation. Mark evidenced coverage and expose unverified branches.'],
  loop: ['Loop graph', 'Understand the bounds of the work.', 'Inspect the six canonical loops and author their relationships, escalation paths, ownership, and budget notes.'],
} as const;

export function DiagramStudio({ kind, controller, client, onNavigate }: ModelingStudioProps & { kind: DiagramKind }) {
  const [document, setDocument] = useState<StudioDocument>();
  const [title, setTitle] = useState(`Untitled ${HEADINGS[kind][0].toLowerCase()}`);
  const [model, setModel] = useState<DiagramModel>(()=>template(DIAGRAM_TYPES[kind][0]));
  const [selected, setSelected] = useState<string|null>(null);
  const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [dirty, setDirty] = useState(false); const [query, setQuery] = useState('');
  const [importing, setImporting] = useState(false); const [raw, setRaw] = useState('');
  const [confirm, setConfirm] = useState<'new'|'remove'|StudioDocument>();
  const [routing, setRouting] = useState<'curved'|'orthogonal'>('curved');
  const [edge, setEdge] = useState({from:'',to:'',label:'',kind:'relation' as 'relation'|'contract'|'rework'});
  const [pathTo, setPathTo] = useState('');
  const documents = (controller.snapshot?.documents ?? []).filter(item=>item.kind===kind);
  const node = model.nodes.find(item=>item.id===selected);
  const shown = model.nodes.filter(item=>`${item.label} ${item.kind} ${item.source ?? ''} ${item.owner ?? ''}`.toLowerCase().includes(query.toLowerCase()));
  const highlighted = selected && pathTo ? tracePath(model,selected,pathTo) : query ? new Set(shown.map(item=>item.id)) : undefined;
  const edit = (next: DiagramModel) => {setModel(next);setDirty(true);setNotice('');};
  const changeNode = (patch: Partial<NonNullable<typeof node>>) => node && edit({...model,nodes:model.nodes.map(item=>item.id===node.id?{...item,...patch}:item)});
  const act = async (action: ()=>Promise<void>)=>{setError('');try{await action();}catch(cause){setError(cause instanceof Error?cause.message:String(cause));}};
  const load = (item: StudioDocument) => {try{setModel(parseModel(item.body));setTitle(item.title);setDocument(item);setSelected(null);setDirty(false);setNotice(`Loaded revision ${item.version}.`);setError('');}catch(cause){setError(String(cause));}};
  const reset = ()=>{setDocument(undefined);setModel(template(DIAGRAM_TYPES[kind][0]));setTitle(`Untitled ${HEADINGS[kind][0].toLowerCase()}`);setSelected(null);setDirty(false);setNotice('New authored model.');};
  const save = ()=>act(async()=>{
    if(!title.trim())throw new Error('Give this model a title.');
    const next=await controller.execute('document/save',{document:{id:document?.id,kind,title:title.trim(),body:JSON.stringify(model),tags:[model.type],expectedVersion:document?.version}});
    const saved=next.documents?.find(item=>document?item.id===document.id:item.kind===kind&&item.title===title.trim()&&item.body===JSON.stringify(model));
    if(saved)setDocument(saved);setDirty(false);setNotice('Model saved to this workspace.');
  });
  const exportFile=(format:'json'|'svg'|'mmd')=>{const content=format==='json'?JSON.stringify(model,null,2):format==='svg'?svgExport(model):mermaidExport(model);client.notify({type:'download',fileName:`${title.replace(/[^a-z0-9_-]/gi,'-').slice(0,90)||'diagram'}.${format}`,mimeType:format==='json'?'application/json':format==='svg'?'image/svg+xml':'text/plain',content});};
  return <div className={s.page}>
    <header className={s.header}><div><p className={s.eyebrow}>Design / {HEADINGS[kind][0]}</p><h1>{HEADINGS[kind][1]}</h1><p>{HEADINGS[kind][2]}</p></div><span className={s.badge}>{dirty?'Unsaved changes':document?`Revision ${document.version}`:'Authored template'}</span></header>
    <div className={s.notice}>{kind==='loop'?'Loop runtime endpoints are not implemented by the current sidecar. This is an editable planning model, not live execution.': 'Models are authored and source-linked. Automated repository extraction, drift detection, and diagram approval services are not connected.'} {kind==='architecture'&&<button className={s.button} onClick={()=>onNavigate('codemap')}>Explore code evidence</button>}</div>
    {error&&<div className={s.error} role="alert">{error}</div>}{notice&&<div className={s.notice} role="status">{notice}</div>}
    <div className={s.toolbar}><label className={`${s.field} ${s.wide}`}>Saved models<select className={s.select} value={document?.id??''} onChange={event=>{const item=documents.find(item=>item.id===event.target.value);if(item){if(dirty)setConfirm(item);else load(item);}}}><option value="">Choose a model…</option>{documents.map(item=><option value={item.id} key={item.id}>{item.title} · v{item.version}</option>)}</select></label><button className={s.button} onClick={()=>dirty?setConfirm('new'):reset()}>New model</button><button className={s.button} onClick={()=>{setRaw('');setImporting(true);}}>Import JSON</button><button className={s.primary} disabled={controller.busy||!controller.snapshot?.capabilities.workspaceOpen} onClick={()=>void save()}>Save model</button>{document&&<button className={s.danger} disabled={controller.busy} onClick={()=>setConfirm('remove')}>Delete model</button>}</div>
    <div className={s.two}><label className={s.field}>Model title<input className={s.input} value={title} maxLength={160} onChange={event=>{setTitle(event.target.value);setDirty(true);}}/></label><label className={s.field}>Diagram type<select className={s.select} value={model.type} onChange={event=>edit({...model,type:event.target.value})}>{DIAGRAM_TYPES[kind].map(type=><option key={type}>{type}</option>)}</select></label></div>
    <div className={s.toolbar}><button className={s.button} disabled={model.nodes.length>=300} onClick={()=>{const id=crypto.randomUUID();edit({...model,nodes:[...model.nodes,{id,label:'New node',kind:kind==='flow'?'step':'component',detail:'',x:60+model.nodes.length%3*220,y:50+Math.floor(model.nodes.length/3)*130,coverage:'unknown'}]});setSelected(id);}}>Add node</button><label className={s.field}>Layout<select aria-label="Diagram layout" className={s.select} defaultValue="" onChange={event=>{if(event.target.value)edit(layoutModel(model,event.target.value as 'grid'|'circle'|'vertical'));event.target.value='';}}><option value="">Arrange nodes…</option><option value="grid">Grid</option><option value="circle">Circle</option><option value="vertical">Vertical</option></select></label><label className={s.field}>Edge routing<select className={s.select} value={routing} onChange={event=>setRouting(event.target.value as typeof routing)}><option value="curved">Curved</option><option value="orthogonal">Orthogonal</option></select></label><button className={s.button} onClick={()=>exportFile('json')}>Export JSON</button><button className={s.button} onClick={()=>exportFile('svg')}>Export SVG</button><button className={s.button} onClick={()=>exportFile('mmd')}>Export Mermaid</button></div>
    <div className={s.workspace}><GraphCanvas model={model} selected={selected} onSelect={setSelected} onChange={edit} highlighted={highlighted} routing={routing}/><aside className={`${s.panel} ${s.inspector}`} aria-label="Node inspector"><h2>{node?'Edit node':'Select a node'}</h2>{node?<><label className={s.field}>Node label<input className={s.input} value={node.label} maxLength={200} onChange={event=>changeNode({label:event.target.value})}/></label><label className={s.field}>Node kind<select className={s.select} value={node.kind} onChange={event=>changeNode({kind:event.target.value})}>{Array.from(new Set([node.kind,'person','system','container','component','class','entity','participant','state','step','decision','store','boundary','human','loop'])).map(value=><option key={value}>{value}</option>)}</select></label><label className={s.field}>Source path or ADR<input className={s.input} value={node.source??''} onChange={event=>changeNode({source:event.target.value})} placeholder="src/module.ts or docs/adr-001.md"/></label><label className={s.field}>Owner or agent<input className={s.input} value={node.owner??''} onChange={event=>changeNode({owner:event.target.value})}/></label><label className={s.field}>Evidence coverage<select className={s.select} value={node.coverage??'unknown'} onChange={event=>changeNode({coverage:event.target.value as 'unknown'|'covered'|'gap'})}><option value="unknown">Unverified</option><option value="covered">Evidence attached</option><option value="gap">Gap identified</option></select></label><label className={s.field}>{kind==='loop'?'Bounds and escalation policy':'Details, contracts, and evidence'}<textarea className={s.textarea} value={node.detail} onChange={event=>changeNode({detail:event.target.value})}/></label><label className={s.field}>Trace directed path to<select className={s.select} value={pathTo} onChange={event=>setPathTo(event.target.value)}><option value="">No path filter</option>{model.nodes.filter(item=>item.id!==node.id).map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label>{pathTo&&<p className={s.muted} role="status">{highlighted?.size?`${highlighted.size} nodes on this path.`:'No directed path connects these nodes.'}</p>}<button className={s.danger} onClick={()=>{edit({...model,nodes:model.nodes.filter(item=>item.id!==node.id),edges:model.edges.filter(item=>item.from!==node.id&&item.to!==node.id)});setSelected(null);setPathTo('');}}>Remove node and its relationships</button></>:<p className={s.muted}>Click the canvas or a row below. Drag a node to move it, or focus it and use arrow keys. Shift moves in larger steps.</p>}</aside></div>
    <div className={s.grid}><section className={s.panel}><h2>Nodes · accessible list</h2><label className={s.field}>Search nodes<input className={s.input} value={query} onChange={event=>setQuery(event.target.value)} placeholder="Name, kind, owner, source…"/></label><div className={s.list}>{shown.map(item=><div className={s.row} key={item.id}><div><strong>{item.label}</strong><p>{item.kind}{item.source?` · ${item.source}`:''}{item.owner?` · ${item.owner}`:''}</p><p>{item.detail}</p></div><button className={s.button} aria-label={`Inspect ${item.label}`} onClick={()=>setSelected(item.id)}>Inspect</button></div>)}{!shown.length&&<p className={s.empty}>No matching nodes.</p>}</div></section><section className={s.panel}><h2>Relationships</h2><form className={s.form} onSubmit={event=>{event.preventDefault();if(!edge.from||!edge.to||!edge.label.trim())return;edit({...model,edges:[...model.edges,{...edge,id:crypto.randomUUID(),label:edge.label.trim()}]});setEdge({...edge,label:''});}}><div className={s.two}><label className={s.field}>From<select className={s.select} required value={edge.from} onChange={event=>setEdge({...edge,from:event.target.value})}><option value="">Choose node…</option>{model.nodes.map(item=><option value={item.id} key={item.id}>{item.label}</option>)}</select></label><label className={s.field}>To<select className={s.select} required value={edge.to} onChange={event=>setEdge({...edge,to:event.target.value})}><option value="">Choose node…</option>{model.nodes.map(item=><option value={item.id} key={item.id}>{item.label}</option>)}</select></label></div><label className={s.field}>Relationship label<input className={s.input} required value={edge.label} onChange={event=>setEdge({...edge,label:event.target.value})}/></label><label className={s.field}>Relationship kind<select className={s.select} value={edge.kind} onChange={event=>setEdge({...edge,kind:event.target.value as typeof edge.kind})}><option value="relation">Relation</option><option value="contract">Contract</option><option value="rework">Rework / escalation</option></select></label><button className={s.button} disabled={model.edges.length>=1200}>Add relationship</button></form><div className={s.list}>{model.edges.map(item=><div className={s.row} key={item.id}><div><strong>{item.label}</strong><p>{model.nodes.find(node=>node.id===item.from)?.label} → {model.nodes.find(node=>node.id===item.to)?.label} · {item.kind}</p></div><button className={s.danger} aria-label={`Remove relationship ${item.label}`} onClick={()=>edit({...model,edges:model.edges.filter(edge=>edge.id!==item.id)})}>Remove</button></div>)}</div></section></div>
    <label className={s.field}>Model notes and review context<textarea className={s.textarea} value={model.notes} onChange={event=>edit({...model,notes:event.target.value})}/></label>
    {importing&&<Dialog title="Import diagram JSON" description="Only the versioned node and relationship schema is accepted. Imported models stay unsaved until you save them." onClose={()=>setImporting(false)} wide><form className={s.form} onSubmit={event=>{event.preventDefault();try{const next=parseModel(raw);if(!DIAGRAM_TYPES[kind].includes(next.type as never))throw new Error(`Choose a ${HEADINGS[kind][0]} diagram type.`);edit(next);setDocument(undefined);setSelected(null);setImporting(false);setError('');}catch(cause){setError(String(cause));}}}><label className={s.field}>Diagram JSON<textarea className={s.textarea} value={raw} onChange={event=>setRaw(event.target.value)} required/></label>{error&&<p role="alert">{error}</p>}<button className={s.primary}>Import model</button></form></Dialog>}
    {confirm&&<Dialog title={confirm==='remove'?'Delete this saved model?':'Discard unsaved model changes?'} description={confirm==='remove'?'This removes the workspace document. Export a copy first if you need to keep it.':'Your current unsaved edits will be replaced.'} onClose={()=>setConfirm(undefined)}><div className={s.toolbar}><button className={s.button} onClick={()=>setConfirm(undefined)}>Keep editing</button><button className={s.danger} onClick={()=>void act(async()=>{if(confirm==='remove'&&document){await controller.execute('document/remove',{id:document.id,expectedVersion:document.version});reset();}else if(confirm==='new')reset();else if(typeof confirm==='object')load(confirm);setConfirm(undefined);})}>{confirm==='remove'?'Delete saved model':'Discard and continue'}</button></div></Dialog>}
  </div>;
}
