import { useState } from 'react';
import type { AttribDiffResult } from '../../../../shared/ts/bus-types';
import type { StudioDocument } from '../../../../shared/ts/studio';
import { Dialog } from '../Dialog';
import type { ModelingStudioProps } from './types';
import s from './modeling.module.css';
interface HunkReview { state: 'accepted'|'rework'|'edited'; reason: string; edited?: string; evidence: string }
interface DiffReview { schemaVersion:1; kind:'diff-review'; source:AttribDiffResult; hunks:Record<string,HunkReview> }
/** A workspace document is editable JSON, so validate restored evidence before rendering it. */
export function parseDiffReview(text:string):DiffReview {
  const value=JSON.parse(text) as DiffReview;
  const invalid=()=>new Error('This document is not a supported diff review.');
  if(value.schemaVersion!==1||value.kind!=='diff-review'||!value.source||typeof value.source.repoPath!=='string'||!Array.isArray(value.source.files)||!value.hunks||Array.isArray(value.hunks)||typeof value.hunks!=='object')throw invalid();
  for(const file of value.source.files){
    if(!file||typeof file.path!=='string'||!['added','modified','deleted','renamed'].includes(file.status)||!Array.isArray(file.hunks))throw invalid();
    for(const hunk of file.hunks){
      if(!hunk||![hunk.oldStart,hunk.oldCount,hunk.newStart,hunk.newCount].every(item=>Number.isInteger(item)&&item>=0)||!Array.isArray(hunk.lines))throw invalid();
      for(const line of hunk.lines)if(!line||!['added','removed','context'].includes(line.kind)||typeof line.content!=='string'||(line.commit!=null&&typeof line.commit!=='string')||(line.authorName!=null&&typeof line.authorName!=='string'))throw invalid();
    }
  }
  for(const review of Object.values(value.hunks))if(!review||!['accepted','rework','edited'].includes(review.state)||typeof review.reason!=='string'||typeof review.evidence!=='string'||(review.edited!==undefined&&typeof review.edited!=='string'))throw invalid();
  return value;
}
export function DiffStudio({client,ready,workspaceDir,controller,onNavigate}:ModelingStudioProps){
  const [base,setBase]=useState('HEAD');const [compare,setCompare]=useState('');const [path,setPath]=useState('');const [staged,setStaged]=useState(false);const [data,setData]=useState<AttribDiffResult>();const [reviews,setReviews]=useState<Record<string,HunkReview>>({});const [record,setRecord]=useState<StudioDocument>();const [fileIndex,setFileIndex]=useState(0);const [layout,setLayout]=useState<'unified'|'split'>('unified');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
  const [editing,setEditing]=useState<{key:string;state:HunkReview['state'];reason:string;edited:string;evidence:string;original:string}>();
  const saved=(controller.snapshot?.documents??[]).filter(item=>item.kind==='verification'&&item.tags.includes('diff-review'));
  const file=data?.files[fileIndex];
  const counts=(state:HunkReview['state'])=>Object.values(reviews).filter(item=>item.state===state).length;
  const load=async()=>{setBusy(true);setError('');setNotice('');try{if(!workspaceDir)throw new Error('Open a Git workspace to inspect changes.');if(compare.trim()&&staged)throw new Error('Select either a commit range or the staged index.');const result=await client.request('attrib/diff',{repoPath:workspaceDir,base:base.trim()||undefined,compare:compare.trim()||undefined,staged,paths:path.trim()?[path.trim()]:undefined});setData(result);setReviews({});setRecord(undefined);setFileIndex(0);}catch(cause){setError(cause instanceof Error?cause.message:String(cause));}finally{setBusy(false);}};
  const save=async()=>{if(!data)return;setError('');try{const body:DiffReview={schemaVersion:1,kind:'diff-review',source:data,hunks:reviews};const next=await controller.execute('document/save',{document:{id:record?.id,kind:'verification',title:`Diff review · ${data.base??'HEAD'} → ${data.compare??(data.staged?'index':'worktree')}`,body:JSON.stringify(body),tags:['diff-review'],expectedVersion:record?.version}});const stored=next.documents?.find(item=>record?item.id===record.id:item.body===JSON.stringify(body));if(stored)setRecord(stored);setNotice('Review annotations saved. Source files and Git index have not been changed.');}catch(cause){setError(cause instanceof Error?cause.message:String(cause));}};
  const restore=(id:string)=>{const item=saved.find(item=>item.id===id);if(!item)return;try{const body=parseDiffReview(item.body);setData(body.source);setReviews(body.hunks);setRecord(item);setFileIndex(0);setError('');setNotice('Review snapshot loaded. Reload changes to inspect the current workspace.');}catch(cause){setError(String(cause));}};
  return <div className={s.page}><header className={s.header}><div><p className={s.eyebrow}>Review / Diff theater</p><h1>Read the change. Capture the decision.</h1><p>Inspect real Git hunks with line attribution. Mark acceptance, request rework with a reason, or draft a correction alongside evidence references.</p></div><button className={s.button} onClick={()=>onNavigate('ledger')}>Open evidence ledger</button></header>
    <div className={s.notice}>Hunk decisions are saved review annotations. Applying edits, staging hunks, submitting rework, and committing require a source-write service that is not connected.</div>
    {error&&<div className={s.error} role="alert">{error}</div>}{notice&&<div className={s.notice} role="status">{notice}</div>}
    <form className={s.form} onSubmit={event=>{event.preventDefault();void load();}}><div className={s.grid}><label className={s.field}>Base reference<input className={s.input} value={base} onChange={event=>setBase(event.target.value)}/></label><label className={s.field}>Compare reference<input className={s.input} value={compare} onChange={event=>setCompare(event.target.value)} placeholder="Blank compares workspace"/></label><label className={s.field}>File path filter<input className={s.input} value={path} onChange={event=>setPath(event.target.value)} placeholder="Optional repository-relative path"/></label></div><div className={s.toolbar}><label className={s.muted}><input type="checkbox" checked={staged} onChange={event=>setStaged(event.target.checked)}/> Compare staged index</label><button className={s.primary} disabled={!ready||!workspaceDir||busy}>{busy?'Loading changes…':'Load changes'}</button><label className={`${s.field} ${s.wide}`}>Saved review<select className={s.select} value={record?.id??''} onChange={event=>restore(event.target.value)}><option value="">Choose a review snapshot…</option>{saved.map(item=><option value={item.id} key={item.id}>{item.title} · v{item.version}</option>)}</select></label></div></form>
    {!data?<div className={`${s.panel} ${s.empty}`}>Load a worktree, staged index, or commit range to begin a review.</div>:<><div className={s.toolbar}><span className={s.badge}>{data.files.length} changed files</span><span className={s.badge}>{counts('accepted')} accepted · {counts('rework')} rework · {counts('edited')} edited drafts</span><button className={s.button} aria-pressed={layout==='unified'} onClick={()=>setLayout('unified')}>Unified</button><button className={s.button} aria-pressed={layout==='split'} onClick={()=>setLayout('split')}>Side by side</button><button className={s.primary} disabled={controller.busy||!controller.snapshot?.capabilities.workspaceOpen} onClick={()=>void save()}>Save review</button><button className={s.button} onClick={()=>client.notify({type:'download',fileName:'meridian-diff-review.json',mimeType:'application/json',content:JSON.stringify({schemaVersion:1,kind:'diff-review',source:data,hunks:reviews},null,2)})}>Export review</button></div>
      {data.files.length===0?<div className={`${s.panel} ${s.empty}`}>No changes match this comparison.</div>:<><label className={s.field}>Changed file<select className={s.select} value={fileIndex} onChange={event=>setFileIndex(Number(event.target.value))}>{data.files.map((item,index)=><option key={item.path} value={index}>{item.path} · {item.status} · {item.hunks.length} hunks</option>)}</select></label><section className={s.panel}><h2>{file?.path}</h2><p className={s.muted}>{file?.oldPath?`Renamed from ${file.oldPath}. `:''}{data.base??'HEAD'} → {data.compare??(data.staged?'Staged index':'Current worktree')}</p>{file?.hunks.map((hunk,index)=>{const key=`${file.path}:${index}`;const review=reviews[key];const original=hunk.lines.filter(line=>line.kind!=='removed').map(line=>line.content).join('\n');return <section className={s.form} key={key} style={{marginTop:22}} aria-label={`Hunk ${index+1}`}><div className={s.toolbar}><span className={s.badge}>@@ −{hunk.oldStart},{hunk.oldCount} +{hunk.newStart},{hunk.newCount} @@</span>{review&&<span className={s.badge}>{review.state}</span>}</div>{layout==='unified'?<div className={s.diff}>{hunk.lines.map((line,lineIndex)=><div className={s.diffLine} data-kind={line.kind} key={lineIndex} title={line.commit?`${line.authorName??'Unknown author'} · ${line.commit} · ${line.authorTime??''}`:'No introducing commit for this worktree/index line'}><span>{line.oldLine??''}</span><span>{line.newLine??''}</span><span>{line.kind==='added'?'+':line.kind==='removed'?'−':' '} {line.content}</span></div>)}</div>:<div className={s.sideBySide}><pre aria-label={`Hunk ${index+1} before`}>{hunk.lines.filter(line=>line.kind!=='added').map(line=>`${line.oldLine??''}  ${line.content}`).join('\n')}</pre><pre aria-label={`Hunk ${index+1} after`}>{hunk.lines.filter(line=>line.kind!=='removed').map(line=>`${line.newLine??''}  ${line.content}`).join('\n')}</pre></div>}
        <p className={s.muted}>{Array.from(new Set(hunk.lines.filter(line=>line.commit).map(line=>`${line.authorName??'Unknown'} · ${line.commit!.slice(0,12)}`))).join(' / ')||'No commit attribution for current worktree/index changes. Prompt, covering tests, and ledger linkage must be supplied as evidence.'}</p><div className={s.toolbar}>{(['accepted','rework','edited'] as const).map(state=><button key={state} className={s.button} aria-label={`${state==='accepted'?'Accept':state==='rework'?'Request rework for':'Draft edit for'} hunk ${index+1}`} onClick={()=>setEditing({key,state,reason:review?.reason??'',evidence:review?.evidence??'',edited:review?.edited??original,original})}>{state==='accepted'?'Accept':state==='rework'?'Rework':'Edit draft'}</button>)}{review&&<button className={s.button} aria-label={`Clear review for hunk ${index+1}`} onClick={()=>setReviews(current=>Object.fromEntries(Object.entries(current).filter(([id])=>id!==key)))}>Clear decision</button>}</div>{review&&<div className={s.notice}><strong>{review.reason||'Accepted by reviewer'}</strong><p>{review.evidence||'No evidence reference supplied.'}</p>{review.edited!==undefined&&<pre className={s.pre}>{review.edited}</pre>}</div>}</section>;})}</section></>}
    </>}
    {editing&&<Dialog wide title={editing.state==='accepted'?'Accept hunk for review':editing.state==='rework'?'Request rework':'Draft a human correction'} description="This records a review decision; it does not modify the source or dispatch an agent." onClose={()=>setEditing(undefined)}><form className={s.form} onSubmit={event=>{event.preventDefault();if(editing.state!=='accepted'&&!editing.reason.trim())return;setReviews(current=>({...current,[editing.key]:{state:editing.state,reason:editing.reason.trim(),evidence:editing.evidence.trim(),...(editing.state==='edited'?{edited:editing.edited}:{})}}));setEditing(undefined);setNotice('Decision added to the review. Save the review to persist it.');}}><label className={s.field}>{editing.state==='accepted'?'Acceptance note':'Reason (required)'}<textarea className={s.textarea} required={editing.state!=='accepted'} value={editing.reason} onChange={event=>setEditing({...editing,reason:event.target.value})} placeholder="Correctness, security, missing requirement, style, performance, or other…"/></label><label className={s.field}>Prompt, test, and ledger references<textarea className={s.textarea} value={editing.evidence} onChange={event=>setEditing({...editing,evidence:event.target.value})} placeholder="Ledger #42; tests/unit/example.test.ts; prompt context…"/></label>{editing.state==='edited'&&<><label className={s.field}>Proposed hunk content<textarea className={s.textarea} value={editing.edited} onChange={event=>setEditing({...editing,edited:event.target.value})}/></label><div className={s.two}><div><h3>Recorded after</h3><pre className={s.pre}>{editing.original}</pre></div><div><h3>Your proposed correction</h3><pre className={s.pre}>{editing.edited}</pre></div></div></>}<button className={s.primary}>Record review decision</button></form></Dialog>}
  </div>;
}
