import { useEffect, useRef, useState } from 'react';
import type { LedgerEntry, LedgerGetEntryResult, LedgerVerifyResult } from '../../../../shared/ts/bus-types';
import type { ModelingStudioProps } from './types';
import s from './modeling.module.css';

export function ReplayStudio({client,ready,onNavigate}:ModelingStudioProps){
  const [story,setStory]=useState('');const [entries,setEntries]=useState<LedgerEntry[]>([]);const [position,setPosition]=useState(0);const [loaded,setLoaded]=useState(false);const [playing,setPlaying]=useState(false);const [detail,setDetail]=useState<LedgerGetEntryResult>();const [verified,setVerified]=useState<LedgerVerifyResult>();const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [speed,setSpeed]=useState(1200);
  const generation=useRef(0);const entry=entries[position];
  useEffect(()=>{setDetail(undefined);setVerified(undefined);++generation.current;},[entry?.sequence]);
  useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setPosition(current=>{if(current>=entries.length-1){setPlaying(false);return current;}return current+1;}),speed);return()=>clearInterval(timer);},[playing,entries.length,speed]);
  useEffect(()=>()=>{++generation.current;},[]);
  const load=async()=>{setBusy(true);setPlaying(false);setError('');try{const result=await client.request('ledger.query',{storyId:story.trim()||undefined,limit:1000});setEntries([...result.entries].sort((a,b)=>a.sequence-b.sequence));setPosition(0);setLoaded(true);setDetail(undefined);setVerified(undefined);}catch(cause){setError(cause instanceof Error?cause.message:String(cause));}finally{setBusy(false);}};
  const inspect=async()=>{if(!entry)return;setPlaying(false);setBusy(true);setError('');const mine=++generation.current;try{const result=await client.request('ledger.getEntry',{sequence:entry.sequence});if(mine===generation.current)setDetail(result);}catch(cause){if(mine===generation.current)setError(cause instanceof Error?cause.message:String(cause));}finally{setBusy(false);}};
  const verify=async()=>{if(!entry)return;setPlaying(false);setBusy(true);setError('');const mine=++generation.current;try{const result=await client.request('ledger.verify',{upTo:entry.sequence});if(mine===generation.current)setVerified(result);}catch(cause){if(mine===generation.current)setError(cause instanceof Error?cause.message:String(cause));}finally{setBusy(false);}};
  const prefix=entries.slice(0,position+1);const cost=prefix.reduce((sum,item)=>sum+(item.costUsd??0),0);const costCoverage=prefix.filter(item=>item.costUsd!==undefined).length;
  return <div className={s.page}><header className={s.header}><div><p className={s.eyebrow}>Evidence / Replay & time travel</p><h1>Return to the moment of a decision.</h1><p>Scrub recorded events, inspect the original prompt and output when available, and verify the chain up to the selected sequence.</p></div><button className={s.button} onClick={()=>onNavigate('ledger')}>Open full ledger</button></header>
    <div className={s.notice}>Playback browses recorded evidence. It does not re-execute models, restore a workspace, or rewind other screens. Deterministic cassette replay and historical checkout are not connected.</div>
    <form className={s.toolbar} onSubmit={event=>{event.preventDefault();void load();}}><label className={`${s.field} ${s.wide}`}>Story filter<input className={s.input} value={story} onChange={event=>setStory(event.target.value)} placeholder="Story ID · blank includes recorded stories"/></label><button className={s.primary} disabled={!ready||busy}>{busy?'Loading…':'Load timeline'}</button></form>
    {error&&<div className={s.error} role="alert">{error}</div>}
    {!loaded?<div className={`${s.panel} ${s.empty}`}>Load ledger evidence to inspect a recorded journey.</div>:!entries.length?<div className={`${s.panel} ${s.empty}`}>No recorded events match this story filter.</div>:<>
      <section className={s.panel} aria-label="Replay controls"><div className={s.toolbar}><button className={s.button} disabled={position===0} onClick={()=>{setPlaying(false);setPosition(0);}}>First</button><button className={s.button} disabled={position===0} onClick={()=>{setPlaying(false);setPosition(value=>value-1);}}>Previous</button><button className={s.primary} onClick={()=>{if(position===entries.length-1)setPosition(0);setPlaying(value=>!value);}}>{playing?'Pause playback':'Play timeline'}</button><button className={s.button} disabled={position===entries.length-1} onClick={()=>{setPlaying(false);setPosition(value=>value+1);}}>Next</button><button className={s.button} disabled={position===entries.length-1} onClick={()=>{setPlaying(false);setPosition(entries.length-1);}}>Last</button><label className={s.field}>Playback speed<select className={s.select} value={speed} onChange={event=>setSpeed(Number(event.target.value))}><option value={2400}>Slow · 2.4 seconds</option><option value={1200}>Normal · 1.2 seconds</option><option value={600}>Fast · 0.6 seconds</option></select></label><span className={s.badge} aria-live="polite">#{entry.sequence} · {position+1} of {entries.length}</span></div><label className={s.field} style={{marginTop:18}}>Recorded event<input className={s.timeline} type="range" min="0" max={entries.length-1} value={position} aria-valuetext={`Sequence ${entry.sequence}: ${entry.actionType} by ${entry.actorId}`} onChange={event=>{setPlaying(false);setPosition(Number(event.target.value));}}/></label><p className={s.muted}>Up to 1,000 returned events, sorted by sequence. Story filters may leave sequence gaps. {entries.length===1000?'The response reached its limit; narrow the story filter for a complete journey.':''}</p></section>
      <div className={s.grid}><section className={s.panel}><p className={s.eyebrow}>Recorded phases in selection</p><div className={s.metric}>{new Set(prefix.map(item=>item.phase)).size}</div><p className={s.muted}>{[...new Set(prefix.map(item=>item.phase))].join(' · ')}</p></section><section className={s.panel}><p className={s.eyebrow}>Recorded decisions in selection</p><div className={s.metric}>{prefix.filter(item=>item.decision).length}</div><p className={s.muted}>{prefix.filter(item=>item.decision==='reworked'||item.decision==='rejected').length} rework or rejection decisions</p></section><section className={s.panel}><p className={s.eyebrow}>Reported spend in selection</p><div className={s.metric}>{costCoverage?`$${cost.toFixed(4)}`:'Unreported'}</div><p className={s.muted}>Cost present on {costCoverage} of {prefix.length} entries. Not a billing total.</p></section></div>
      <div className={s.timelineList} aria-label="Recorded event index">{entries.slice(Math.max(0,position-15),position+16).map(item=><button className={s.button} aria-pressed={item.sequence===entry.sequence} key={item.sequence} onClick={()=>{setPlaying(false);setPosition(entries.findIndex(value=>value.sequence===item.sequence));}}>#{item.sequence} · {item.actionType}<small>{item.phase}</small>{item.simulated&&<small>Simulated record</small>}</button>)}</div>
      <section className={s.panel}><div className={s.header}><div><p className={s.eyebrow}>Sequence {entry.sequence} / {entry.phase}</p><h2>{entry.actionType} · {entry.actorId}</h2><p className={s.muted}>{entry.timestamp} · Story {entry.storyId} · Loop {entry.loopId || 'not recorded'} / iteration {entry.loopIteration}</p></div><span className={s.badge}>{entry.simulated?'Simulated evidence':entry.observationConfidence} · {entry.vendor}</span></div><div className={s.grid}><div><h3>Decision</h3><p className={s.muted}>{entry.decision??'No decision recorded'}{entry.humanActor?` · ${entry.humanActor}`:''}</p><p className={s.muted}>{entry.reworkReason}</p></div><div><h3>Model and policy</h3><p className={s.muted}>{entry.modelId??'Model not reported'} · Policy {entry.policyVersion}</p><p className={s.muted}>{entry.replayOf?`Replay of sequence ${entry.replayOf}`:'No replay linkage recorded'}</p></div><div><h3>Entry digest</h3><p className={s.muted}>{entry.entryHash}</p></div></div><div className={s.toolbar}><button className={s.button} disabled={busy} onClick={()=>void inspect()}>Inspect recorded payloads</button><button className={s.button} disabled={busy} onClick={()=>void verify()}>Verify chain to this event</button><button className={s.button} onClick={()=>client.notify({type:'download',fileName:`meridian-timeline-through-${entry.sequence}.json`,mimeType:'application/json',content:JSON.stringify({kind:'meridian-ledger-selection',filter:{story:story||null},through:entry.sequence,entries:prefix,verification:verified??null},null,2)})}>Export selected timeline</button></div></section>
      {verified&&<div className={verified.ok?s.notice:s.error} role="status"><strong>{verified.ok?'Chain verified':'Verification failed'}</strong> · {verified.entriesChecked} entries checked. {verified.detail} <p>Chain integrity does not establish output correctness.</p></div>}
      {detail&&<div className={s.two}><section className={s.panel}><h2>Recorded input</h2><pre className={s.pre}>{detail.inputAvailable?(detail.input??'Empty input'): 'Input is unavailable or its encryption key is no longer available.'}</pre></section><section className={s.panel}><h2>Recorded output</h2><pre className={s.pre}>{detail.outputAvailable?(detail.output??'Empty output'):'Output is unavailable or its encryption key is no longer available.'}</pre></section></div>}
    </>}
  </div>;
}
