import { useState } from 'react';
import type { WorkbenchDeliverable } from '../../../shared/ts/workbench';
import type { WorkbenchController } from './useWorkbench';
import { Dialog } from './Dialog';
import { Icon } from './Icon';
import s from './studio.module.css';
import d from './delivery.module.css';

const COLUMNS = [{ id: 'draft', label: 'Ready to weave', hint: 'Define the outcome' }, { id: 'running', label: 'In progress', hint: 'Active agents at work' }, { id: 'review', label: 'Your review', hint: 'Inspect and give feedback' }, { id: 'completed', label: 'Completed', hint: 'Carry the learning forward' }];
export function DeliveryStudio({ controller, onNavigate }: { controller: WorkbenchController; onNavigate?: (route: string) => void }) {
  const { snapshot, execute, busy } = controller;
  const [draft, setDraft] = useState<{ id?: string; title: string; brief: string }>();
  const [selectedId, setSelectedId] = useState<string>();
  const [feedback, setFeedback] = useState('');
  const [error, setError] = useState<string>();
  const [search, setSearch] = useState('');
  const [view, setView] = useState<'board' | 'list'>('board');
  const selected = snapshot?.deliverables.find(item => item.id === selectedId);
  const active = snapshot?.agents.filter(agent => agent.mode === 'active') ?? [];
  const deliverables = snapshot?.deliverables.filter(item => `${item.title} ${item.brief}`.toLowerCase().includes(search.toLowerCase())) ?? [];
  const perform = async (task: () => Promise<unknown>, done?: () => void) => { setError(undefined); try { await task(); done?.(); } catch (cause) { setError((cause as Error).message); } };
  const inspect = (item: WorkbenchDeliverable) => { setSelectedId(item.id); setFeedback(item.feedback ?? ''); setError(undefined); };
  const card = (item: WorkbenchDeliverable) => <button className={d.card} key={item.id} onClick={() => inspect(item)}><span className={d.cardMeta}>{item.id.slice(0, 8).toUpperCase()}<span className={s.badge} data-state={item.state}>{item.state}</span></span><h3>{item.title}</h3><p>{item.brief.slice(0, 160)}{item.brief.length > 160 ? '…' : ''}</p><div className={d.cardFooter}><span>{item.agentIds.length ? `${item.agentIds.length} agents` : 'Team assigned at dispatch'}</span><Icon name="arrow" size={14} /></div></button>;
  return <div className={s.studio}><header className={s.pageHeader}><div><span className={s.eyebrow}>WORKSPACE / DELIVERABLES</span><h1>Make the next thing matter.</h1><p className={s.subtitle}>Start with a clear brief. Bring in your active agents. Review the result before calling it done.</p></div><button className={s.primaryButton} disabled={!snapshot?.capabilities.workspaceOpen} onClick={() => { setDraft({ title: '', brief: '' }); setError(undefined); }}><Icon name="plus" size={16} /> New deliverable</button></header>
    <section className={d.teamBand}><div className={d.teamAvatars}>{active.slice(0, 5).map(agent => <span key={agent.id} className={s.avatar} title={agent.name}>{agent.name.slice(0, 2).toUpperCase()}</span>)}{active.length === 0 && <Icon name="agents" size={25} />}</div><div><strong>{active.length} active agents in your delivery team</strong><p>Dispatch assigns the current active roster. Agents in Learning do not receive delivery tasks.</p></div><button className={s.quietButton} onClick={() => onNavigate?.('agents')}>Manage team →</button></section>
    <div className={s.toolbar}><div className={s.filters}><button className={s.filter} aria-pressed={view === 'board'} onClick={() => setView('board')}>Board</button><button className={s.filter} aria-pressed={view === 'list'} onClick={() => setView('list')}>List</button></div><label className={s.search}><Icon name="search" size={15} /><input aria-label="Search deliverables" placeholder="Find a deliverable…" value={search} onChange={event => setSearch(event.target.value)} /></label></div>
    <div className={view === 'board' ? d.board : d.list}>{COLUMNS.map(column => { const items = deliverables.filter(item => item.state === column.id || (column.id === 'review' && item.state === 'failed')); return <section className={d.column} key={column.id} aria-label={column.label}><div className={d.columnHeading}><span className={d.columnDot} data-stage={column.id} /><h2>{column.label}</h2><span>{items.length}</span></div><p className={d.columnHint}>{column.hint}</p>{items.map(card)}{items.length === 0 && <div className={d.columnEmpty}>{column.id === 'draft' ? 'A clear brief is a good beginning.' : column.id === 'running' ? 'Work appears here after you dispatch.' : column.id === 'review' ? 'Completed turns and failed runs arrive here.' : 'Reviewed outcomes live here.'}</div>}{column.id === 'draft' && <button className={d.addDraft} disabled={!snapshot?.capabilities.workspaceOpen} onClick={() => { setDraft({ title: '', brief: '' }); setError(undefined); }}>+ Write a brief</button>}</section>; })}</div>
    <p className={s.footnote}><Icon name="layers" size={17} />Agents run sequentially in the open workspace. Each retains its own ACP session. Full isolated orchestration and automatic merge workflows remain separate capabilities.</p>
    {draft && <Dialog title={draft.id ? 'Refine the brief' : 'What should we build?'} description="Describe an outcome and the checks that will tell you it is ready. Saving a draft does not start an agent." wide onClose={() => setDraft(undefined)}><form className={s.form} onSubmit={event => { event.preventDefault(); void perform(() => execute('deliverable/save', draft), () => setDraft(undefined)); }}><label className={s.field}>Deliverable title<input autoFocus required maxLength={200} value={draft.title} onChange={event => setDraft({ ...draft, title: event.target.value })} placeholder="e.g. Make the checkout accessible" /></label><label className={s.field}>Brief and acceptance criteria<textarea required rows={12} maxLength={40000} value={draft.brief} onChange={event => setDraft({ ...draft, brief: event.target.value })} placeholder={'Outcome\nWhat should change, and for whom?\n\nScope\nWhich files or areas should the team focus on?\n\nAcceptance criteria\nWhat should be tested or verified?\n\nConstraints\nWhat must the team preserve?'} /></label>{error && <p className={s.error} role="alert">{error}</p>}<div className={s.dialogFooter}><button type="button" className={s.button} onClick={() => setDraft(undefined)}>Cancel</button><button className={s.primaryButton} disabled={busy}>Save draft</button></div></form></Dialog>}
    {selected && <Dialog title={selected.title} description={`Deliverable ${selected.id.slice(0, 8)} · ${selected.state}`} wide onClose={() => setSelectedId(undefined)}><pre className={s.code}>{selected.brief}</pre>{selected.state === 'draft' && <><div className={s.detailBlock}><h3>Dispatch preview</h3><p>{active.length ? active.map(agent => `${agent.name} (${agent.role})`).join(' · ') : 'No active agents. Activate at least one agent in the studio.'}</p><p>The roster is captured when you dispatch. Execution may request tool permissions.</p></div>{!snapshot?.capabilities.executionReady && <p className={s.notice}>{snapshot?.capabilities.executionBlockedReason}</p>}<div className={s.dialogFooter}><button className={s.button} onClick={() => { setDraft({ id: selected.id, title: selected.title, brief: selected.brief }); setSelectedId(undefined); }}>Edit brief</button><button className={s.primaryButton} disabled={busy || !active.length || !snapshot?.capabilities.executionReady} onClick={() => void perform(() => execute('deliverable/dispatch', { id: selected.id }))}><Icon name="play" size={14} /> Dispatch active team</button></div></>}
    {snapshot?.runs.filter(run => run.deliverableId === selected.id).map(run => <section className={s.detailBlock} key={run.id}><div className={s.sectionHeader}><h3>{run.agentName} · {run.state}</h3>{['running', 'queued'].includes(run.state) && <button className={s.dangerButton} disabled={busy} onClick={() => void perform(() => execute('run/cancel', { id: run.id }))}>Stop run</button>}</div>{run.output ? <pre className={s.code}>{run.output}</pre> : <p>{run.state === 'queued' ? 'Waiting for the preceding agent turn.' : 'No agent output recorded yet.'}</p>}{run.error && <p className={s.error}>{run.error}</p>}{run.stopReason && <p className={s.hint}>Agent stop reason: {run.stopReason}. A completed turn still requires your review.</p>}</section>)}
    {selected.state === 'review' && <form className={s.form} onSubmit={event => { event.preventDefault(); void perform(() => execute('deliverable/complete', { id: selected.id, feedback }), () => setSelectedId(undefined)); }}><label className={s.field}>Review feedback<textarea required rows={4} value={feedback} onChange={event => setFeedback(event.target.value)} placeholder="What did you inspect and verify? What should the team remember?" /></label><p className={s.hint}>Completing this review creates proposed memory notes for Learning agents with memory enabled.</p><button className={s.primaryButton} disabled={busy}>Complete and share feedback</button></form>}
    {selected.state === 'failed' && <div className={s.notice}>An agent turn failed or was stopped. Inspect the run details and actual workspace changes before starting another iteration.<button className={s.quietButton} onClick={() => { setDraft({ title: selected.title, brief: selected.brief }); setSelectedId(undefined); }}>Create another draft →</button></div>}{selected.feedback && <div className={s.detailBlock}><h3>Human review</h3><pre className={s.code}>{selected.feedback}</pre></div>}{error && <p className={s.error} role="alert">{error}</p>}</Dialog>}
  </div>;
}
