/** Navigation coverage is separate from full specification acceptance. */
export const SURFACE_COVERAGE: Array<[number, string, string, string]> = [
  [1, 'Command Center', 'overview', 'Workspace pulse, participating agents, delivery progress and next actions.'],
  [2, 'The Loom Floor', 'floor', 'Spatial and list views of working, ready and Learning agents, with live task details.'],
  [3, 'The Weave', 'weave', 'Delivery and independent-run trace, outcomes, source context and export.'],
  [4, 'Agents Watch', 'watch', 'Dense sortable roster, saved filters and columns, comparisons and confirmed bulk participation changes.'],
  [5, 'Agents Dojo', 'learning', 'Review feedback-derived memory for Learning agents. Accepted notes enter subsequent tasks; model training is separate.'],
  [6, 'Gate Room', 'gates', 'Inspect real gate profiles and criteria, evaluate evidence and inspect recorded verdicts.'],
  [7, 'Ledger / Selvage Viewer', 'ledger', 'Recorded entries, provenance, chain verification and signed evidence export.'],
  [8, 'CodeMap Viewer', 'codemap', 'Explore source attribution and authored code relationships, with native editor links.'],
  [9, 'Loop Graph Viewer', 'loops', 'Author versioned loop graphs, relationships and evidence. Autonomous loop execution depends on the runtime.'],
  [10, 'Architecture & C4 Viewer', 'architecture', 'Edit component relationships, source links and ownership; navigate, lay out and export diagrams.'],
  [11, 'UML Studio', 'uml', 'Create and revise typed UML diagrams with node and relationship editing and portable exports.'],
  [12, 'Flow Diagram Viewer', 'flows', 'Author flows, branches and evidence links with graph and accessible list representations.'],
  [13, 'Config Portal', 'configuration', 'Configuration navigation and versioned workspace notes, alongside native host settings.'],
  [14, 'Skill Forge', 'skills', 'Versioned skill drafts, target selection, instruction application previews and portable exchange.'],
  [15, 'Onboarding Wizard', 'onboarding', 'Guided portable profile creation/import, readiness and participation checks.'],
  [16, 'Agent Inspector', 'inspector', 'Inspect launch configuration, declared permissions, actual run history and profile details.'],
  [17, 'Diff Theater', 'diff', 'Inspect recorded attributed changes and their evidence. Applying hunks requires a host patch service.'],
  [18, 'Spec Studio', 'specifications', 'Edit requirements, acceptance criteria, ownership and delivery traceability in versioned specifications.'],
  [19, 'Work Packet Board', 'packets', 'Draft, dispatch, inspect, stop and review delivery work with an active-only roster.'],
  [20, 'Verification Board', 'verification', 'Author verification plans and inspect supplied evidence; manual claims are distinct from runtime verdicts.'],
  [21, 'Security Assurance', 'security', 'Track findings, severity, ownership, disposition and supporting evidence.'],
  [22, 'KPI Observatory', 'kpi', 'Actual run and delivery measures with recorded latency/cost coverage and CSV export.'],
  [23, 'Exchange', 'exchange', 'Import/export portable authored documents and agent profiles, with explicit review boundaries.'],
  [24, 'Focus Mode', 'focus', 'Distraction controls, persistent appearance and keyboard navigation.'],
  [25, 'Story Hub', 'stories', 'Versioned stories, priorities, acceptance criteria and links to local delivery work.'],
  [26, 'Portfolio', 'portfolio', 'Author project milestones, owners, work limits and dependencies in local portfolio documents.'],
  [27, 'Decision Stream', 'decisions', 'Filter actual ledger decisions and retain their recorded evidence context.'],
  [28, 'Steer & Clarify', 'steer', 'Ledger-recorded guidance to a hosted ACP session at its next turn, with immediate stop controls.'],
  [29, 'Replay & Time-Travel', 'replay', 'Browse recorded history at a selected point. Historical checkout and deterministic re-execution are separate capabilities.'],
  [30, 'Memory Studio', 'memory', 'Accept or dismiss candidate memory and inspect the lessons carried by each portable profile.'],
  [31, 'Model Routing', 'routing', 'Versioned routing policies and local selection simulations; provider execution uses configured host adapters.'],
  [32, 'Approval Inbox', 'approvals', 'Inspect governed role approval checks and decision evidence using available host services.'],
  [33, 'Connections', 'connectors', 'Connector configuration and mapping drafts with payload previews; remote synchronization needs an installed connector.'],
  [34, 'Pipeline Desk', 'pipeline', 'Versioned pipeline plans and available pull-request preflight/status actions.'],
  [35, 'Repository Constellation', 'repositories', 'Inspect real worktrees, conflicts and repository readiness.'],
  [36, 'Report Atelier', 'reports', 'Build portable reports from actual workspace snapshots and authored evidence.'],
  [37, 'Calibration Lab', 'calibration', 'Inspect available trust and rejection measurements with explicit input coverage.'],
  [38, 'Runtime & Diagnostics', 'runtime', 'Live connection health, execution prerequisites and host diagnostic reports.'],
  [39, 'Notification Centre', 'notifications', 'Filter real run and memory events, mark read and return to their source.'],
  [40, 'Guided Setup', 'setup', 'Host readiness and existing recorder setup actions.'],
  [41, 'Shortcuts & Coach', 'shortcuts', 'Search, focus, dialogs, evidence navigation and workflow guidance.'],
  [42, 'Editor-Resident Surfaces', 'editor', 'Inspect attribution at a source location and open it in the native editor.'],
  [43, 'Adapter Bay', 'adapters', 'Inspect and export each portable ACP runtime configuration and open its editable profile.'],
  [44, 'Instruction Library', 'instructions', 'Versioned instruction documents, target previews and explicit application to agent profiles.'],
  [45, 'Flight Recorder', 'flight-recorder', 'Live observer, provenance weave, any-line attribution, verification and export.'],
  [46, 'External Agents', 'external-agents', 'Observed external sessions with vendor, provenance and observation-confidence labels.'],
  [47, 'Trust Observatory', 'trust', 'Inspect real rejection classification and trust measurements with coverage context.'],
  [48, 'Comprehension Studio', 'comprehension', 'Author source-linked explanations, ownership and handover evidence.'],
  [49, 'Cross-Vendor Spend', 'spend', 'Analyze recorded spend and coverage; absent provider billing is shown as unavailable.'],
  [50, 'Unlock', 'unlock', 'Review tier capabilities, prerequisites and native settings.'],
  [51, 'Launch', 'launch', 'Brief and active-team selection, conflict preflight, explicit dispatch and follow-through.'],
];
