"""FR-M22-02 (audit TASK-340): interface contracts for multi-repo stories.

A story spanning more than one repository must declare the interface
contract both sides build against, generated by the Architect before
implementation. :func:`generate_interface_contract` produces an OpenAPI
skeleton from the story's repo targets; :func:`interface_contract_gate`
is the Review-gate check — a multi-repo story without a generated
contract is blocked, with the reason naming the missing artefact.

The skeleton is a real artefact (written under
``.meridian/contracts/<story>.yaml``), not a marker: it carries one path
per repo pair so both sides code against the same shape.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Sequence


class ContractError(ValueError):
    """An interface-contract rule violation. Carries FR-M22-02."""


@dataclass(frozen=True)
class ContractTarget:
    """One side of a multi-repo interface."""

    repo_id: str
    provides: str  # e.g. "payments-api"


def generate_interface_contract(
    story_id: str,
    targets: Sequence[ContractTarget],
    destination: Path,
) -> Path:
    """The Architect-generated OpenAPI skeleton. Refuses a single-repo
    story (no interface to contract) and a target list without at least
    two distinct repos."""
    repos = {t.repo_id for t in targets}
    if len(repos) < 2:
        raise ContractError(
            "FR-M22-02: interface contracts apply to multi-repo stories;"
            f" {story_id!r} declares {sorted(repos)}"
        )
    lines = [
        "openapi: 3.0.3",
        f"info:",
        f"  title: {story_id} cross-repository interface",
        "  version: 0.1.0",
        "paths:",
    ]
    ordered = sorted(targets, key=lambda t: t.repo_id)
    for target in ordered:
        lines.append(f"  /{target.repo_id}/{target.provides}:")
        lines.append("    get:")
        lines.append(f"      summary: provided by {target.repo_id}")
        lines.append('      responses:')
        lines.append('        "200":')
        lines.append("          description: contract surface")
    destination.mkdir(parents=True, exist_ok=True)
    path = destination / f"{story_id}.yaml"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def interface_contract_gate(
    story_id: str,
    *,
    repo_count: int,
    contracts_dir: Path,
) -> Mapping[str, Any]:
    """Review-gate check (FR-M22-02, FR-M29-02-adjacent): multi-repo
    stories block Review until the generated contract exists. Single-repo
    stories pass — there is no cross-service surface to pin."""
    if repo_count < 2:
        return {"gate": "review", "passed": True,
                "reason": "single-repository story: no interface contract required"}
    contract = contracts_dir / f"{story_id}.yaml"
    if contract.is_file():
        try:
            head = contract.read_text(encoding="utf-8", errors="replace")[:400]
        except OSError:
            head = ""
        # GP-018: the audit wrote "not an API contract" into the expected
        # file and the is_file gate passed. Presence is not validity: the
        # artefact must actually be an OpenAPI contract.
        if "openapi:" in head and "paths:" in head:
            return {"gate": "review", "passed": True,
                    "reason": f"interface contract present: {contract.name}"}
        return {
            "gate": "review",
            "passed": False,
            "reason": (
                "FR-M22-02: the contract file exists but is not an OpenAPI"
                " contract — regenerate it from the design artefacts"
            ),
        }
    return {
        "gate": "review",
        "passed": False,
        "reason": (
            "FR-M22-02: multi-repo story without a generated interface"
            " contract — the Architect must generate the OpenAPI skeleton"
            " both repositories build against before Review"
        ),
    }
