import { useState, type FormEvent } from 'react';
import type { StudioDocument, StudioDocumentInput } from '../../../../shared/ts/studio';
import type { WorkbenchSnapshot } from '../../../../shared/ts/workbench';
import { Dialog } from '../Dialog';
import { emptyContent, parseContent, validateContent, type OrganizationContent, type OrganizationKind } from './model';
import s from '../studio.module.css';
import o from './organization.module.css';

export function DocumentEditor({ kind, document, snapshot, busy, error, onSave, onClose }: {
  kind: OrganizationKind; document?: StudioDocument; snapshot: WorkbenchSnapshot; busy: boolean; error?: string;
  onSave: (value: StudioDocumentInput) => Promise<void>; onClose: () => void;
}) {
  const [title, setTitle] = useState(document?.title ?? '');
  const [tags, setTags] = useState(document?.tags.join(', ') ?? '');
  const [content, setContent] = useState<OrganizationContent>(() => document ? parseContent(document) : emptyContent(kind));
  const [validation, setValidation] = useState<string>();
  const change = (field: string, value: string) => setContent(previous => ({ ...previous, fields: { ...previous.fields, [field]: value } }));
  const field = (id: string, label: string, options?: string[], multiline = false, type = 'text') => <label className={s.field} key={id}>{label}{options ? <select value={content.fields[id] ?? ''} onChange={e => change(id, e.target.value)}>{options.map(option => <option key={option} value={option}>{option}</option>)}</select> : multiline ? <textarea rows={id === 'content' ? 12 : 3} value={content.fields[id] ?? ''} maxLength={100000} onChange={e => change(id, e.target.value)} spellCheck={id !== 'content'} /> : <input type={type} value={content.fields[id] ?? ''} maxLength={2000} onChange={e => change(id, e.target.value)} />}</label>;
  const submit = (event: FormEvent) => {
    event.preventDefault();
    const issue = validateContent(content);
    if (issue) { setValidation(issue); return; }
    if (!title.trim()) { setValidation('A title is required.'); return; }
    setValidation(undefined);
    void onSave({ ...(document ? { id: document.id, expectedVersion: document.version } : {}), kind, title: title.trim(), body: JSON.stringify(content), tags: [...new Set(tags.split(',').map(tag => tag.trim()).filter(Boolean))] });
  };
  const options = kind === 'portfolio' ? (snapshot.documents ?? []).filter(d => d.kind === 'story').map(d => ({ id: d.id, title: d.title })) : snapshot.deliverables;
  const linkLabel = kind === 'portfolio' ? 'Linked stories in priority order' : 'Linked deliverables';
  return <Dialog title={document ? `Edit ${document.title}` : `New ${kind}`} description="Saved in this workspace with version checks. These drafts do not change external systems or runtime policy." onClose={onClose} wide>
    <form className={s.form} onSubmit={submit}>
      <div className={s.formRow}><label className={s.field}>Title<input autoFocus required maxLength={160} value={title} onChange={e => setTitle(e.target.value)} /></label><label className={s.field}>Tags, separated by commas<input value={tags} maxLength={1000} onChange={e => setTags(e.target.value)} placeholder="accessibility, platform" /></label></div>
      {field('summary', 'Summary', undefined, true)}
      {kind === 'story' && <><div className={s.formRow}>{field('source', 'Source', ['Workspace', 'Jira Cloud', 'Jira DC', 'Rally', 'Azure DevOps', 'GitHub Issues', 'File'])}{field('externalId', 'External story ID')}</div><div className={s.formRow}>{field('state', 'Planning status', ['draft', 'ready', 'in-progress', 'review', 'done', 'paused'])}{field('priority', 'Priority', ['urgent', 'high', 'normal', 'low'])}</div><div className={s.formRow}>{field('owner', 'Owner')}{field('complexity', 'Complexity', ['small', 'standard', 'complex'])}</div><div className={s.formRow}>{field('branch', 'Branch reference')}{field('due', 'Target date', undefined, false, 'date')}</div></>}
      {kind === 'portfolio' && <><div className={s.formRow}>{field('owner', 'Team or owner')}{field('client', 'Client or cost centre')}</div><div className={s.formRow}>{field('wip', 'Work-in-progress limit', undefined, false, 'number')}{field('due', 'Target date', undefined, false, 'date')}</div><p className={s.hint}>The order below is the planning queue. The WIP limit is advisory and does not pause running deliverables.</p></>}
      {kind === 'specification' && <><div className={s.formRow}>{field('complexity', 'Complexity', ['small', 'standard', 'complex'])}{field('resolution', 'Ambiguity disposition', ['open', 'accepted', 'amended', 'escalated'])}</div>{field('ambiguities', 'Ambiguities and proposed resolutions', undefined, true)}<p className={s.hint}>Escalations stay in this specification until a human records a resolution. No agent-generated confidence is inferred.</p></>}
      {(kind === 'story' || kind === 'specification' || kind === 'portfolio') && <fieldset className={s.formSection}><legend>{linkLabel}</legend><div className={o.linkOptions}>{options.map(option => <label className={s.checkbox} key={option.id}><input type="checkbox" checked={content.links.includes(option.id)} onChange={e => setContent(previous => ({ ...previous, links: e.target.checked ? [...previous.links, option.id] : previous.links.filter(id => id !== option.id) }))} />{option.title}</label>)}{options.length === 0 && <p className={s.hint}>Create {kind === 'portfolio' ? 'a story' : 'a deliverable'} first, then link it here.</p>}</div>{kind === 'portfolio' && content.links.map((id, index) => <div className={o.queueRow} key={id}><span>{index + 1}. {options.find(option => option.id === id)?.title || `${id} (unavailable)`}</span><button type="button" className={s.button} disabled={index === 0} aria-label={`Move ${options.find(option => option.id === id)?.title || id} up`} onClick={() => setContent(previous => { const links = [...previous.links]; [links[index - 1], links[index]] = [links[index], links[index - 1]]; return { ...previous, links }; })}>Move up</button></div>)}</fieldset>}
      {(kind === 'story' || kind === 'specification') && <fieldset className={s.formSection}><legend>Acceptance criteria and traceability</legend><p className={s.hint}>Verification states are authored assertions. Include a concrete test or evidence reference when marking a criterion verified.</p>{content.criteria.map((criterion, index) => <div key={index} className={o.criterionEditor}><div className={s.formRow}><label className={s.field}>Criterion ID {index + 1}<input value={criterion.id} onChange={e => setContent(previous => ({ ...previous, criteria: previous.criteria.map((row, i) => i === index ? { ...row, id: e.target.value } : row) }))} /></label><label className={s.field}>Evidence status {index + 1}<select value={criterion.state} onChange={e => setContent(previous => ({ ...previous, criteria: previous.criteria.map((row, i) => i === index ? { ...row, state: e.target.value as typeof row.state } : row) }))}><option value="unverified">Unverified</option><option value="verified">Verified by author</option><option value="blocked">Blocked</option></select></label></div>{(['requirement', 'acceptance', 'evidence'] as const).map(key => <label className={s.field} key={key}>{key === 'requirement' ? 'Requirement' : key === 'acceptance' ? 'Acceptance condition' : 'Evidence reference'} {index + 1}<input value={criterion[key]} onChange={e => setContent(previous => ({ ...previous, criteria: previous.criteria.map((row, i) => i === index ? { ...row, [key]: e.target.value } : row) }))} /></label>)}<button type="button" className={s.dangerButton} onClick={() => setContent(previous => ({ ...previous, criteria: previous.criteria.filter((_, i) => i !== index) }))}>Remove criterion {index + 1}</button></div>)}<button type="button" className={s.button} onClick={() => setContent(previous => ({ ...previous, criteria: [...previous.criteria, { id: `AC-${previous.criteria.length + 1}`, requirement: '', acceptance: '', evidence: '', state: 'unverified' }] }))}>Add acceptance criterion</button></fieldset>}
      {kind === 'skill' && <><div className={s.formRow}>{field('packageVersion', 'Package version')}{field('stack', 'Target stack')}</div><div className={s.formRow}>{field('tools', 'Declared tools')}{field('source', 'Source attribution')}</div>{field('content', 'SKILL.md content', undefined, true)}<p className={s.hint}>Discovery estimate: approximately {Math.ceil(((content.fields.content.match(/^description:\s*(.+)$/m)?.[1] ?? '').length + title.length) / 4)} tokens (character heuristic, not a provider tokenizer). Scripts are never installed or executed by this editor.</p></>}
      {kind === 'instruction' && <><div className={s.formRow}>{field('scope', 'Draft scope', ['adapter', 'workspace', 'user', 'organisation'])}{field('path', 'Intended instruction path')}</div>{field('content', 'Instruction content', undefined, true)}{field('rationale', 'Change rationale', undefined, true)}<p className={s.hint}>Draft scope describes intent. Publishing governed files or opening a PR uses your repository workflow; saving here does not write AGENTS.md or change organisation policy.</p></>}
      {kind === 'connector' && <><div className={s.formRow}>{field('provider', 'Provider', ['Jira Cloud', 'Jira DC', 'Rally', 'Azure DevOps', 'GitHub Issues'])}{field('project', 'Project or repository')}</div>{field('endpoint', 'HTTPS endpoint')}<div className={s.formRow}>{field('titleField', 'Title field')}{field('bodyField', 'Body field')}</div><div className={s.formRow}>{field('stateField', 'State field')}{field('transition', 'Proposed transition')}</div>{field('template', 'Write-back template', undefined, true)}<p className={s.notice}>Available variables: {'{{title}}'}, {'{{brief}}'}, {'{{state}}'}. Credentials belong in the provider’s secure store. All write-back proposals require human review; this screen does not connect or send.</p></>}
      {kind === 'routing' && <>{field('region', 'Intended data-residency region')}{field('note', 'Routing rationale', undefined, true)}<fieldset className={s.formSection}><legend>Action-class routing matrix</legend><p className={s.hint}>Use * as a wildcard. Exact phase takes priority, followed by exact task class. Rules are drafts and do not change the runtime router.</p>{content.rules.map((rule, index) => <div key={index} className={o.criterionEditor}><div className={s.formRow}>{(['phase', 'task', 'engine', 'fallback'] as const).map(key => <label className={s.field} key={key}>{key === 'task' ? 'Task class' : key === 'engine' ? 'Engine or model' : key === 'fallback' ? 'Fallback engine' : 'Phase'} {index + 1}<input value={rule[key]} onChange={e => setContent(previous => ({ ...previous, rules: previous.rules.map((row, i) => i === index ? { ...row, [key]: e.target.value } : row) }))} /></label>)}</div><div className={s.formRow}><label className={s.field}>Execution mode {index + 1}<select value={rule.mode} onChange={e => setContent(previous => ({ ...previous, rules: previous.rules.map((row, i) => i === index ? { ...row, mode: e.target.value as typeof row.mode, ceiling: e.target.value === 'deterministic' ? 0 : row.ceiling } : row) }))}><option value="deterministic">deterministic</option><option value="assisted">assisted</option><option value="generative">generative</option></select></label><label className={s.field}>Model-call ceiling {index + 1}<input type="number" min="0" step="1" value={rule.ceiling} disabled={rule.mode === 'deterministic'} onChange={e => setContent(previous => ({ ...previous, rules: previous.rules.map((row, i) => i === index ? { ...row, ceiling: Number(e.target.value) } : row) }))} /></label></div><button type="button" className={s.dangerButton} onClick={() => setContent(previous => ({ ...previous, rules: previous.rules.filter((_, i) => i !== index) }))}>Remove rule {index + 1}</button></div>)}<button type="button" className={s.button} onClick={() => setContent(previous => ({ ...previous, rules: [...previous.rules, { phase: '*', task: '', mode: 'deterministic', engine: '', fallback: '', ceiling: 0 }] }))}>Add routing rule</button></fieldset></>}
      {kind === 'report' && field('content', 'Report Markdown', undefined, true)}
      {document && <details className={o.disclosure}><summary>Compare with saved version {document.version}</summary><div className={s.detailGrid}><div><h3>Saved content</h3><pre className={s.code}>{JSON.stringify(parseContent(document), null, 2)}</pre></div><div><h3>Proposed content</h3><pre className={s.code}>{JSON.stringify(content, null, 2)}</pre></div></div></details>}
      {(validation || error) && <p role="alert" className={s.error}>{validation || error}</p>}
      <div className={s.dialogFooter}><button type="button" className={s.button} onClick={onClose}>Cancel</button><button className={s.primaryButton} disabled={busy}>{busy ? 'Saving…' : document ? 'Save new version' : 'Save document'}</button></div>
    </form>
  </Dialog>;
}
