import { useState } from 'react';
import type { StudioDocument } from '../../../../shared/ts/studio';
import type { WorkbenchAgent, WorkbenchSnapshot } from '../../../../shared/ts/workbench';
import type { WebviewRpcClient } from '../../rpc/client';
import { useRpcQuery } from '../../hooks/useRpcQuery';
import { getVsCodeApi } from '../../host/vscode-api';
import type { WorkbenchController } from '../useWorkbench';
import { Dialog } from '../Dialog';
import { Icon } from '../Icon';
import { DocumentEditor } from './DocumentEditor';
import { DocumentDetail } from './DocumentDetail';
import { ExchangeStudio } from './ExchangeStudio';
import { ReportBuilder } from './ReportBuilder';
import { VIEW_META, parseContent, type OrganizationView } from './model';
import s from '../studio.module.css';
import o from './organization.module.css';

export interface OrganizationStudioProps {
  view: OrganizationView;
  client?: WebviewRpcClient;
  ready: boolean;
  controller: WorkbenchController;
  workspaceDir?: string;
  enabledTiers?: readonly string[];
  onNavigate: (view: string) => void;
}
export function OrganizationStudio(props: OrganizationStudioProps) {
  return props.view === 'exchange' ? <ExchangeStudio controller={props.controller} onNavigate={props.onNavigate} /> : <DocumentLibrary key={props.view} {...props} view={props.view} />;
}
function DocumentLibrary({ view, controller, client, ready, workspaceDir, onNavigate }: OrganizationStudioProps & { view: Exclude<OrganizationView, 'exchange'> }) {
  const meta = VIEW_META[view];
  const { snapshot, execute, busy } = controller;
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState('all');
  const [selectedId, setSelectedId] = useState<string>();
  const [editor, setEditor] = useState<{ document?: StudioDocument }>();
  const [removing, setRemoving] = useState<StudioDocument>();
  const [applying, setApplying] = useState<StudioDocument>();
  const [error, setError] = useState<string>();
  const [notice, setNotice] = useState<string>();
  const [buildReport, setBuildReport] = useState(false);
  const ledger = useRpcQuery(client, 'ledger.query', { limit: 200 }, ready && (view === 'reports' || view === 'routing'));
  const documents = (snapshot?.documents ?? []).filter(document => document.kind === meta.kind);
  const shown = documents.filter(document => `${document.title} ${document.tags.join(' ')} ${document.body}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || parseContent(document).fields[view === 'instructions' ? 'scope' : 'state'] === filter)).sort((a,b) => b.updatedAt.localeCompare(a.updatedAt));
  const selected = documents.find(document => document.id === selectedId);
  const perform = async (task: () => Promise<unknown>, done?: () => void) => { setError(undefined); setNotice(undefined); try { await task(); done?.(); } catch(cause) { setError(cause instanceof Error ? cause.message : String(cause)); } };
  const prepareExport = (document: StudioDocument) => void perform(async () => { const payload = await execute('document/export', { id: document.id }); getVsCodeApi().postMessage({ type: 'download', mimeType: 'application/json', ...payload }); setNotice('Document prepared. Choose a destination in the save dialog.'); });
  const filters = view === 'instructions' ? ['all', 'adapter', 'workspace', 'user', 'organisation'] : view === 'stories' ? ['all', 'draft', 'ready', 'in-progress', 'review', 'done', 'paused'] : ['all'];
  const entries = ledger.status === 'ready' ? ledger.data.entries : undefined;
  const calls = entries?.filter(entry => entry.modelId || entry.tokensIn !== undefined || entry.tokensOut !== undefined) ?? [];
  return <div className={s.studio}>
    <header className={s.pageHeader}><div><span className={s.eyebrow}>WORKSPACE / {meta.title}</span><h1>{meta.headline}</h1><p className={s.subtitle}>{meta.summary}</p></div><div className={s.headerActions}>{view === 'reports' && <button className={s.button} disabled={!snapshot} onClick={() => setBuildReport(true)}>Build journey report</button>}<button className={s.primaryButton} disabled={!snapshot?.capabilities.workspaceOpen} onClick={() => { setEditor({}); setError(undefined); }}><Icon name="plus" size={15} />{meta.add}</button></div></header>
    {view === 'instructions' && <section className={o.scope} aria-label="Instruction draft scopes">{['adapter', 'workspace', 'user', 'organisation'].map(scope => <div key={scope}><strong>{scope}</strong><span>{documents.filter(d => parseContent(d).fields.scope === scope).length}</span><p>{scope === 'adapter' ? 'Applied explicitly to one agent.' : 'Authored scope; publishing follows repository governance.'}</p></div>)}</section>}
    {view === 'specifications' && <section className={s.stats} aria-label="Specification statistics">{[['Specifications', documents.length], ['Criteria', documents.reduce((sum,d) => sum + parseContent(d).criteria.length,0)], ['Verified by author', documents.reduce((sum,d) => sum + parseContent(d).criteria.filter(c => c.state === 'verified').length,0)], ['Uncovered', documents.reduce((sum,d) => sum + parseContent(d).criteria.filter(c => !c.evidence).length,0)]].map(([label,value]) => <div className={s.stat} key={label}><span className={s.statLabel}>{label}</span><strong className={s.statValue}>{value}</strong></div>)}</section>}
    {view === 'connectors' && <p className={s.notice}>Connections are local configuration drafts. Field mapping and write-back previews use real workspace data; credentials, synchronization, and external posting require a connector transport.</p>}
    {view === 'routing' && <p className={s.notice}>Draft policies and local simulation are separate from live runtime routing. The recorded-call table below displays the fields that the ledger actually provides.</p>}
    {error && !editor && !removing && !applying && <p className={s.error} role="alert">{error}</p>}{notice && <p className={s.notice} role="status">{notice}</p>}
    <div className={s.toolbar}><label className={s.search}><Icon name="search" size={15} /><input aria-label={`Search ${meta.title}`} placeholder="Search title, tags, or content…" value={query} onChange={event => setQuery(event.target.value)} /></label>{filters.length > 1 && <label className={s.field}>Filter<select value={filter} onChange={e => setFilter(e.target.value)}>{filters.map(value => <option value={value} key={value}>{value === 'all' ? 'All documents' : value}</option>)}</select></label>}<span className={o.muted}>{shown.length} documents · versioned in this workspace</span></div>
    {view === 'stories' && shown.length > 0 ? <div className={o.board} aria-label="Story planning board">{['backlog', 'in-progress', 'review', 'done'].map(lane => { const cards = shown.filter(d => { const state = parseContent(d).fields.state; return lane === 'backlog' ? ['draft', 'ready', 'paused'].includes(state) : state === lane; }); return <section className={o.lane} key={lane}><h2>{lane === 'backlog' ? 'Backlog & paused' : lane.replace('-', ' ')}<span>{cards.length}</span></h2>{cards.map(document => { const c = parseContent(document); const deliveries = snapshot?.deliverables.filter(d => c.links.includes(d.id)) ?? []; return <button key={document.id} className={o.storyCard} onClick={() => setSelectedId(document.id)}><strong>{document.title}</strong><p>{c.fields.summary || 'No summary yet.'}</p><span>{c.fields.priority || 'normal'} · {c.criteria.length} criteria · {c.fields.state}</span>{deliveries.length > 0 && <><progress className={o.progress} value={deliveries.filter(d => d.state === 'completed').length} max={deliveries.length} aria-label={`${document.title} delivery completion`} /><span>{deliveries.filter(d => d.state === 'completed').length}/{deliveries.length} linked deliverables complete</span></>}</button>; })}{cards.length === 0 && <p className={o.muted}>No stories in this lane.</p>}</section>; })}</div> : <div className={s.grid}>{shown.map(document => { const c = parseContent(document); return <article className={s.card} key={document.id}><div className={s.cardTop}><span className={s.badge}>{document.kind === 'connector' ? 'Configuration draft' : document.kind === 'routing' ? 'Policy draft' : document.kind === 'instruction' ? c.fields.scope : 'Workspace document'}</span><span className={s.version}>v{document.version}</span></div><div className={s.cardTitle}><h2>{document.title}</h2></div><p className={s.role}>{document.kind === 'skill' ? `Package ${c.fields.packageVersion} · ${c.fields.stack || 'Any stack'}` : `Updated ${new Date(document.updatedAt).toLocaleDateString()}`}</p><p className={s.description}>{c.fields.summary || (document.kind === 'report' ? 'Review the saved Markdown report and its source notes.' : 'Open this document to review its content and linked scope.')}</p><div className={s.tags}>{document.tags.map(tag => <span className={s.tag} key={tag}>{tag}</span>)}{c.criteria.length > 0 && <span className={s.tag}>{c.criteria.length} criteria</span>}{c.links.length > 0 && <span className={s.tag}>{c.links.length} links</span>}{c.rules.length > 0 && <span className={s.tag}>{c.rules.length} rules</span>}</div><div className={s.cardFoot}><div className={s.cardActions}><button className={s.button} onClick={() => setSelectedId(document.id)} aria-label={`Inspect ${document.title}`}>Inspect <Icon name="arrow" size={14} /></button><button className={s.button} onClick={() => { setEditor({ document }); setError(undefined); }} aria-label={`Edit ${document.title}`}>Edit</button></div></div></article>; })}</div>}
    {shown.length === 0 && <section className={s.empty}><span className={s.emptyGlyph}>↗</span><h2>{query || filter !== 'all' ? 'No matching documents.' : `Your ${meta.title.toLowerCase()} starts here.`}</h2><p>{query || filter !== 'all' ? 'Change the search or filter to see more documents.' : 'Create a document to organise the work. Its content and revisions stay with this workspace.'}</p><button className={s.button} disabled={!snapshot?.capabilities.workspaceOpen} onClick={() => setEditor({})}>{meta.add}</button></section>}
    {view === 'routing' && <section className={o.panel}><div className={s.sectionHeader}><h2>Recorded model-call sample</h2><button className={s.button} onClick={ledger.refresh}>Refresh evidence</button></div>{ledger.status === 'error' ? <p role="alert" className={s.error}>Ledger unavailable: {ledger.error instanceof Error ? ledger.error.message : String(ledger.error)}</p> : ledger.status === 'loading' ? <p>Waiting for recorded evidence…</p> : calls.length ? <div className={o.tableWrap}><table className={o.table}><caption>Model-related entries within this query’s {entries?.length} entries; this is not complete provider billing.</caption><thead><tr><th>Sequence / actor</th><th>Model</th><th>Tokens in / out</th><th>Latency</th><th>Recorded USD</th></tr></thead><tbody>{calls.map(entry => <tr key={entry.sequence}><td>#{entry.sequence}<br />{entry.actorId}</td><td>{entry.modelId || 'Not recorded'}</td><td>{entry.tokensIn ?? '—'} / {entry.tokensOut ?? '—'}</td><td>{entry.latencyMs === undefined ? '—' : `${entry.latencyMs} ms`}</td><td>{entry.costUsd === undefined ? '—' : entry.costUsd.toFixed(4)}</td></tr>)}</tbody></table></div> : <p>No model-call evidence was found in this ledger sample. Provider health and rate-limit headroom are not inferred.</p>}</section>}
    {selected && snapshot && !editor && !applying && <Dialog title={selected.title} description={`${meta.title} · workspace document`} onClose={() => setSelectedId(undefined)} wide><div className={s.actions}><button className={s.button} onClick={() => { setEditor({ document: selected }); setError(undefined); }}>Edit document</button><button className={s.button} disabled={busy} onClick={() => prepareExport(selected)}>Export document</button>{['skill','instruction'].includes(selected.kind) && <button className={s.button} onClick={() => { setApplying(selected); setError(undefined); }}>Review agent application</button>}{selected.kind === 'report' && <button className={s.button} onClick={() => getVsCodeApi().postMessage({ type: 'download', fileName: `${selected.title.replace(/[^a-zA-Z0-9_-]/g, '-').slice(0,80) || 'journey-report'}.md`, content: parseContent(selected).fields.content, mimeType: 'text/markdown' })}>Export Markdown</button>}<button className={s.dangerButton} onClick={() => { setRemoving(selected); setSelectedId(undefined); }}>Remove document</button></div><DocumentDetail document={selected} snapshot={snapshot} onNavigate={onNavigate} /></Dialog>}
    {editor && snapshot && <DocumentEditor kind={meta.kind} document={editor.document} snapshot={snapshot} busy={busy} error={error} onClose={() => { setEditor(undefined); setError(undefined); }} onSave={value => perform(() => execute('document/save', { document: value }), () => { setEditor(undefined); setNotice('Document saved in this workspace.'); })} />}
    {removing && <Dialog title={`Remove ${removing.title}?`} description="This removes the saved document. References in other documents may need updating; linked deliverables and agents are retained." onClose={() => setRemoving(undefined)}>{error && <p role="alert" className={s.error}>{error}</p>}<div className={s.dialogFooter}><button className={s.button} onClick={() => setRemoving(undefined)}>Keep document</button><button className={s.dangerButton} disabled={busy} onClick={() => void perform(() => execute('document/remove', { id: removing.id, expectedVersion: removing.version }), () => setRemoving(undefined))}>Confirm removal</button></div></Dialog>}
    {applying && snapshot && <ApplyInstructions document={applying} snapshot={snapshot} busy={busy} error={error} onClose={() => setApplying(undefined)} onApply={(agent, instructions) => perform(() => execute('agent/save', { agent: { id: agent.id, name: agent.name, role: agent.role, description: agent.description, vendor: agent.vendor, version: agent.version, command: agent.command, args: agent.args, instructions, permissions: agent.permissions, trainable: agent.trainable } }), () => { setApplying(undefined); setNotice(`Reviewed version applied to ${agent.name}. It will be included in future tasks.`); })} />}
    {buildReport && snapshot && <ReportBuilder snapshot={snapshot} workspaceDir={workspaceDir} ledger={entries} ledgerStatus={ledger.status} busy={busy} error={error} onClose={() => setBuildReport(false)} onSave={document => perform(() => execute('document/save', { document }), () => { setBuildReport(false); setNotice('Journey report saved from the displayed workspace snapshot.'); })} />}
  </div>;
}

function ApplyInstructions({ document, snapshot, busy, error, onClose, onApply }: { document: StudioDocument; snapshot: WorkbenchSnapshot; busy: boolean; error?: string; onClose: () => void; onApply: (agent: WorkbenchAgent, instructions: string) => Promise<void> }) {
  const [agentId, setAgentId] = useState('');
  const [reviewed, setReviewed] = useState(false);
  const agent = snapshot.agents.find(item => item.id === agentId);
  const body = parseContent(document).fields.content ?? '';
  const start = `[Meridian document ${document.id}]`;
  const end = `[/Meridian document ${document.id}]`;
  const existing = agent?.instructions ?? '';
  const startIndex = existing.indexOf(start);
  const endIndex = existing.indexOf(end, startIndex);
  const base = startIndex >= 0 && endIndex >= startIndex ? `${existing.slice(0,startIndex)}${existing.slice(endIndex + end.length)}`.trim() : existing;
  const next = `${base}${base ? '\n\n' : ''}${start}\n${document.title} · reviewed document version ${document.version}\n${body}\n${end}`;
  return <Dialog title={`Apply ${document.title}`} description="Review the exact instruction change for one agent. This does not activate the agent or start a task." onClose={onClose} wide><div className={s.form}><label className={s.field}>Target agent<select value={agentId} onChange={e => { setAgentId(e.target.value); setReviewed(false); }}><option value="">Choose an agent</option>{snapshot.agents.map(item => <option key={item.id} value={item.id} disabled={item.runtime === 'running'}>{item.name} · {item.runtime === 'running' ? 'running; unavailable' : item.mode === 'learning' ? 'Learning' : 'Active'}</option>)}</select></label>{agent && <><div className={s.detailGrid}><section><h3>Current instructions</h3><pre className={s.code}>{existing || 'No instructions.'}</pre></section><section><h3>Proposed instructions</h3><pre className={s.code}>{next}</pre></section></div><p className={s.hint}>{startIndex >= 0 && endIndex >= startIndex ? 'The previously applied version of this document will be replaced.' : 'The reviewed document is appended to the agent’s existing instructions.'} Later document edits require another explicit application.</p><label className={s.checkbox}><input type="checkbox" checked={reviewed} onChange={e => setReviewed(e.target.checked)} />I reviewed the instruction changes for {agent.name}</label></>}{next.length > 40000 && <p role="alert" className={s.error}>The combined instructions exceed the 40,000-character agent limit.</p>}{error && <p role="alert" className={s.error}>{error}</p>}<div className={s.dialogFooter}><button className={s.button} onClick={onClose}>Cancel</button><button className={s.primaryButton} disabled={busy || !agent || !reviewed || !body.trim() || next.length > 40000} onClick={() => agent && void onApply(agent,next)}>Apply reviewed version</button></div></div></Dialog>;
}
