/**
 * Third-party notices — `MVP-R8.2`, `AC-70`, `NFR-48` (MV4-T09).
 *
 * `docs/SECURITY-AND-DATA.md` §7 tells a security reviewer that no runtime
 * dependency is copyleft. `check-licences.mjs` already makes that claim fail
 * the build when it stops being true. What was missing is the other half a
 * legal reviewer asks for: **the list itself**, with each licence named.
 *
 * Generated from the same sweep, in the same build step as the AI-BOM. Same
 * machinery, different manifest — which is the point. Two separately
 * maintained lists of the same dependencies would disagree, and the one that
 * disagreed would be the one nobody read.
 *
 * ## Why it is generated and then checked, rather than just generated
 *
 * A file regenerated on every build is not evidence of anything; it is
 * evidence that someone ran the generator. `--check` fails when the committed
 * notices no longer match the resolved dependencies, so adding a dependency
 * without regenerating stops the build (`NFR-48`, the same drift rule the
 * AI-BOM lives under).
 *
 * ## What it does not claim
 *
 * A dependency the sweep could not resolve is listed as **unresolved**, not
 * omitted and not assumed permissive. An absent row reads as "nothing there",
 * and a notices file that quietly drops what it could not read is worse than
 * one that says so — it is the same failure as a coverage figure rendered
 * blank (`P26`).
 *
 * Usage:
 *   node scripts/generate-notices.mjs            write THIRD-PARTY-NOTICES.md
 *   node scripts/generate-notices.mjs --check    fail when it is out of date
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { runLicenceSweep } from './check-licences.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const NOTICES = path.join(root, 'THIRD-PARTY-NOTICES.md');

const WORKSPACE_LABEL = {
  extension: 'Extension host (Node)',
  webview: 'Interface (browser)',
  core: 'Sidecar (Python)',
};

const VERDICT_NOTE = {
  permitted: 'permissive',
  font: 'font, attribution only',
  copyleft: 'COPYLEFT — this must not ship',
  unknown: 'licence not recognised',
  skipped: 'unresolved: the dependency was not installed when this was generated',
};

export function buildNotices() {
  const sweep = runLicenceSweep();
  const byWorkspace = new Map();
  for (const row of sweep.rows) {
    if (!byWorkspace.has(row.workspace)) byWorkspace.set(row.workspace, []);
    byWorkspace.get(row.workspace).push(row);
  }

  const lines = [
    '# Third-party notices',
    '',
    'Every third-party component that **ships** in the Meridian Loom package,',
    'with the licence each declares.',
    '',
    'Generated by `scripts/generate-notices.mjs` from the same licence sweep that',
    'backs the no-copyleft statement in `docs/SECURITY-AND-DATA.md` §7. It is not',
    'maintained by hand: `npm run check:notices` fails when this file no longer',
    'matches the resolved dependencies, so a dependency added without',
    'regenerating stops the build.',
    '',
    '**Runtime only.** Development dependencies — test runners, bundlers, type',
    'checkers — are not listed, because they are not in the package and their',
    'licences are a different and much weaker question. Conflating the two is',
    'how a notices file becomes either noisy or dishonest.',
    '',
    'A dependency this could not resolve is listed as **unresolved** rather than',
    'omitted or assumed permissive. An absent row would read as "nothing there".',
    '',
  ];

  for (const [workspace, rows] of [...byWorkspace.entries()].sort()) {
    lines.push(`## ${WORKSPACE_LABEL[workspace] ?? workspace}`, '');
    lines.push('| Component | Licence | Note |', '| --- | --- | --- |');
    for (const row of [...rows].sort((a, b) => a.name.localeCompare(b.name))) {
      lines.push(
        `| \`${row.name}\` | ${row.licence ?? '—'} | ${VERDICT_NOTE[row.verdict] ?? row.verdict} |`,
      );
    }
    lines.push('');
  }

  lines.push(
    '## Fonts',
    '',
    'The bundled JetBrains Mono faces are SIL Open Font License 1.1, which is an',
    'attribution licence and carries no obligation on the code that renders with',
    'them.',
    '',
  );

  return lines.join('\n');
}

export function checkNotices() {
  if (!existsSync(NOTICES)) {
    return {
      ok: false,
      problems: [
        'THIRD-PARTY-NOTICES.md does not exist. Run `npm run notices` — the ' +
          'no-copyleft claim in docs/SECURITY-AND-DATA.md §7 is not checkable ' +
          'without the list behind it.',
      ],
    };
  }
  const sweep = runLicenceSweep();
  const unresolved = sweep.rows.filter((row) => row.verdict === 'skipped');
  const expected = buildNotices().trimEnd();
  const actual = readFileSync(NOTICES, 'utf8').trimEnd();

  if (expected === actual) return { ok: true, problems: [], skipped: false };

  // The sweep reads Python licences out of installed distribution metadata,
  // so a checkout without the sidecar's environment resolves fewer rows than
  // the machine that generated the file. Reporting that as drift would fail
  // the build for a reason that has nothing to do with the dependencies, and
  // people would learn to ignore it. Reported as skipped, with the reason,
  // rather than passed: a check that could not look has not looked.
  if (unresolved.length) {
    return {
      ok: true,
      skipped: true,
      problems: [],
      note:
        `${unresolved.length} dependency licence(s) could not be resolved here ` +
        `(${unresolved.map((row) => row.name).join(', ')}), so the notices could ` +
        'not be compared. Install the sidecar environment to check them.',
    };
  }

  return {
    ok: false,
    skipped: false,
    problems: [
      'THIRD-PARTY-NOTICES.md is out of date with the resolved runtime ' +
        'dependencies. Run `npm run notices` and commit the result.',
    ],
  };
}

const invokedDirectly =
  process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (invokedDirectly) {
  if (process.argv.includes('--check')) {
    const result = checkNotices();
    for (const problem of result.problems) console.error(`  ${problem}`);
    if (result.note) console.log(`  ${result.note}`);
    console.log(
      result.skipped
        ? 'notices: skipped — not every licence could be resolved on this machine.'
        : result.ok
          ? 'notices: THIRD-PARTY-NOTICES.md matches the resolved runtime dependencies.'
          : 'notices: THIRD-PARTY-NOTICES.md is out of date.',
    );
    process.exit(result.ok ? 0 : 1);
  }
  writeFileSync(NOTICES, `${buildNotices()}`, 'utf8');
  const rows = runLicenceSweep().rows.length;
  console.log(`notices: ${rows} runtime components written to THIRD-PARTY-NOTICES.md`);
}
