import { useEffect, useMemo, useState } from 'react';
import type { LedgerEntry, TrustClassifyResult, TrustDetectRejectionsResult } from '../../../../shared/ts/bus-types';
import { useRpcQuery } from '../../hooks/useRpcQuery';
import { getVsCodeApi } from '../../host/vscode-api';
import { Confirm, Field, JsonDetail, Notice, Page, Panel, QueryFeedback, Result, money, number, object, pct, useAction, type GovernanceProps } from './common';
import s from './governance.module.css';

export function Trust(props: GovernanceProps) {
  const [actor, setActor] = useState(''); const [story, setStory] = useState(''); const [repo, setRepo] = useState('');
  const [scope, setScope] = useState<{ actorId?: string; storyId?: string; repoId?: string }>({});
  const rates = useRpcQuery(props.ready ? props.client : undefined, 'trust/rejectionRate', scope);
  const ledger = useRpcQuery(props.ready ? props.client : undefined, 'ledger.query', { ...scope, limit: 500 });
  const action = useAction(props.client);
  const [base, setBase] = useState(''); const [ref, setRef] = useState('HEAD');
  const [classification, setClassification] = useState<TrustClassifyResult>(); const [detected, setDetected] = useState<TrustDetectRejectionsResult>();
  const [confirm, setConfirm] = useState(false);
  const reasons = new Map<string, number>(); ledger.data?.entries.filter(entry => entry.actionType === 'rejection').forEach(entry => reasons.set(entry.reworkReason ?? 'Unclassified', (reasons.get(entry.reworkReason ?? 'Unclassified') ?? 0) + 1));
  return <Page title="Trust needs a denominator." eyebrow="INTELLIGENCE / TRUST OBSERVATORY" description="Compare rejection evidence with proposed changes, preserve the greenfield/brownfield distinction, and inspect why work was rejected." actions={<button onClick={() => props.onNavigate('calibration')}>Confidence & calibration</button>}>
    <Result action={action} />
    <Panel title="Measurement scope"><form className={s.form} onSubmit={event => { event.preventDefault(); setScope({ ...(actor.trim() ? { actorId: actor.trim() } : {}), ...(story.trim() ? { storyId: story.trim() } : {}), ...(repo.trim() ? { repoId: repo.trim() } : {}) }); }}><div className={s.three}><Field label="Agent ID filter"><input value={actor} onChange={event => setActor(event.target.value)} /></Field><Field label="Story ID filter"><input value={story} onChange={event => setStory(event.target.value)} /></Field><Field label="Repository ID filter"><input value={repo} onChange={event => setRepo(event.target.value)} /></Field></div><div className={s.actions}><button className={s.primary} disabled={!props.ready}>Apply scope</button><button type="button" disabled={!props.ready} onClick={() => { rates.refresh(); ledger.refresh(); }}>Refresh evidence</button></div></form></Panel>
    <Panel title="Proposed and rejected changes"><QueryFeedback query={rates} connected={props.ready} />{rates.data && <><div className={s.three}><div className={s.stat}><strong>{rates.data.proposed}</strong><span>Proposed changes</span></div><div className={s.stat}><strong>{rates.data.rejected}</strong><span>Rejected proposals</span></div><div className={s.stat}><strong>{rates.data.proposed ? pct(rates.data.rate) : 'No sample'}</strong><span>Recorded rejection rate</span></div></div><p className={s.muted}>{rates.data.proposed ? `${rates.data.rejected} of ${rates.data.proposed} proposals were linked to a recorded rejection in this scope.` : 'There are no proposed changes in this scope; no rate can be assessed.'}</p><div className={s.three}>{['greenfield', 'brownfield', 'unclassified'].map(label => { const bucket = object(rates.data.split[label]); const proposed = number(bucket.proposed) ?? 0; const rejected = number(bucket.rejected) ?? 0; const rate = number(bucket.rate); return <div className={s.card} key={label}><h3>{label}</h3><strong>{proposed && rate !== undefined ? pct(rate) : 'No sample'}</strong><div className={s.bar}><div className={s.barFill} style={{ width: `${Math.max(0, Math.min(1, rate ?? 0)) * 100}%` }} /></div><p>{rejected} rejected / {proposed} proposed. {proposed ? 'This is an observed rate, not a forecast.' : 'Classification requires story commit evidence.'}</p></div>; })}</div><div className={s.tableWrap}><table className={s.table}><thead><tr><th scope="col">Agent</th><th scope="col">Proposed</th><th scope="col">Rejected</th><th scope="col">Rejection rate</th></tr></thead><tbody>{Object.entries(rates.data.byAgent).map(([id, value]) => { const row = object(value); const count = number(row.proposed) ?? 0; return <tr key={id}><th scope="row">{id}</th><td>{count}</td><td>{number(row.rejected) ?? 'Unknown'}</td><td>{count && number(row.rate) !== undefined ? pct(number(row.rate)!) : 'No sample'}</td></tr>; })}</tbody></table></div></>}</Panel>
    <div className={s.row}><Panel title="Recorded rejection reasons"><QueryFeedback query={ledger} connected={props.ready} />{[...reasons].map(([reason, count]) => <div className={s.card} key={reason}><h3>{reason}</h3><p>{count} recorded rejection events in the latest 500 scoped entries.</p></div>)}{ledger.data && !reasons.size && <p className={s.empty}>No rejection reasons recorded in this sample.</p>}</Panel><Panel title="Classify and measure repository changes"><form className={s.form} onSubmit={event => { event.preventDefault(); if (!base.trim()) { action.setError('A base commit or branch is required for classification.'); return; } void action.run('trust/classify', { base: base.trim(), compare: ref.trim() }).then(result => { if (result) setClassification(result); }); }}><div className={s.row}><Field label="Base reference"><input value={base} onChange={event => setBase(event.target.value)} placeholder="main" /></Field><Field label="Comparison reference"><input required value={ref} onChange={event => setRef(event.target.value)} /></Field></div><div className={s.actions}><button disabled={!props.ready || action.busy}>Classify change range</button><button type="button" disabled={!props.ready || action.busy || !ref.trim()} onClick={() => setConfirm(true)}>Review rejection detection</button></div>{classification && <><p className={s.success}>{classification.classification}: {classification.newFiles} new files, {classification.modifiedFiles} modified files; touched-code median age {classification.medianTouchedCodeAgeDays ?? 'unknown'} days.</p><JsonDetail title="Classification thresholds and source" value={classification} /></>}{detected && <><p className={s.success}>{detected.recorded} rejection records appended; {detected.duplicatesSkipped} duplicates skipped.</p><JsonDetail title="Detected rejection evidence" value={detected} /></>}</form></Panel></div>
    <Notice>These metrics describe recorded changes. J-curve trends, module effectiveness, shadow comparisons, post-merge incidents, and causal trust decomposition require additional outcome datasets; a rejection rate alone does not justify autonomous promotion.</Notice>
    {confirm && <Confirm title="Detect and record rejections?" description="This scans repository history and appends newly detected rejection evidence to the ledger. Re-running skips existing records." onClose={() => setConfirm(false)} busy={action.busy} error={action.error} label="Detect and record" onConfirm={() => void action.run('trust/detectRejections', { ...(base.trim() ? { base: base.trim() } : {}), ref: ref.trim(), ...(repo.trim() ? { repoId: repo.trim() } : {}) }).then(result => { if (result) { setDetected(result); setConfirm(false); rates.refresh(); ledger.refresh(); } })}><pre className={s.pre}>{props.workspaceDir ?? 'Current workspace'}{'\n'}Range: {base.trim() || 'Full history'} → {ref.trim()}</pre></Confirm>}
  </Page>;
}

export interface CalibrationBin { low: number; high: number; count: number; confidence: number; outcome: number; }
export function calibrationBins(entries: LedgerEntry[]): CalibrationBin[] {
  return Array.from({ length: 5 }, (_, index) => {
    const sample = entries.filter(entry => !entry.simulated && typeof entry.confidence === 'number' && entry.confidence >= index / 5 && (index === 4 ? entry.confidence <= 1 : entry.confidence < (index + 1) / 5) && /^(pass|approved|accept|accepted|block|reject|rejected|fail)$/.test(entry.decision ?? ''));
    return { low: index / 5, high: (index + 1) / 5, count: sample.length, confidence: sample.length ? sample.reduce((sum, entry) => sum + entry.confidence!, 0) / sample.length : 0, outcome: sample.length ? sample.filter(entry => /^(pass|approved|accept|accepted)$/.test(entry.decision!)).length / sample.length : 0 };
  });
}
export function Calibration(props: GovernanceProps) {
  const [actor, setActor] = useState(''); const [actionType, setActionType] = useState('');
  const query = useRpcQuery(props.ready ? props.client : undefined, 'ledger.query', { ...(actor ? { actorId: actor } : {}), ...(actionType ? { actionType } : {}), limit: 1000 });
  const bins = calibrationBins(query.data?.entries ?? []); const count = bins.reduce((sum, bin) => sum + bin.count, 0);
  const error = count ? bins.reduce((sum, bin) => sum + bin.count * Math.abs(bin.outcome - bin.confidence), 0) / count : undefined;
  return <Page title="Confidence meets recorded outcomes." eyebrow="INTELLIGENCE / CALIBRATION & TRUST" description="Inspect confidence against explicit recorded decisions, keep sample sizes visible, and avoid promoting agents on unsupported certainty." actions={<button onClick={() => props.onNavigate('trust')}>Trust observatory</button>}>
    <Panel title="Calibration sample" action={<button disabled={!props.ready} onClick={query.refresh}>Refresh confidence evidence</button>}><div className={s.row}><Field label="Calibration agent ID"><input value={actor} onChange={event => setActor(event.target.value)} /></Field><Field label="Action class"><input value={actionType} onChange={event => setActionType(event.target.value)} placeholder="gate, review, diff…" /></Field></div><QueryFeedback query={query} connected={props.ready} /><div className={s.three}><div className={s.stat}><strong>{count}</strong><span>Confidence + decision pairs</span></div><div className={s.stat}><strong>{error === undefined ? 'Unavailable' : pct(error)}</strong><span>Mean binned confidence/decision gap</span></div><div className={s.stat}><strong>{query.data?.entries.length ?? '—'}</strong><span>Loaded entries (maximum 1,000)</span></div></div><Notice>Passing an immediate gate is not evidence of long-term correctness. This diagram pairs stated confidence with the same entry's explicit pass/accept versus block/reject decision, excludes simulated records, and is not a production calibration certification.</Notice></Panel>
    <Panel title="Confidence / decision reliability diagram"><svg className={s.svg} viewBox="0 0 600 300" role="img" aria-label={count ? `Reliability plot with ${count} recorded confidence and decision pairs; mean binned gap ${pct(error!)}.` : 'Reliability plot has no paired evidence.'}><line x1="60" y1="250" x2="570" y2="250" /><line x1="60" y1="250" x2="60" y2="20" /><line x1="60" y1="250" x2="570" y2="20" strokeDasharray="5 6" />{[0, .2, .4, .6, .8, 1].map(tick => <g key={tick}><text x={60 + 510 * tick} y="275" textAnchor="middle">{pct(tick)}</text><text x="49" y={254 - 230 * tick} textAnchor="end">{pct(tick)}</text></g>)}{bins.filter(bin => bin.count).map(bin => <circle key={bin.low} cx={60 + 510 * bin.confidence} cy={250 - 230 * bin.outcome} r={Math.min(15, 5 + Math.sqrt(bin.count))}><title>{pct(bin.confidence)} mean confidence; {pct(bin.outcome)} passing decisions; n={bin.count}</title></circle>)}</svg><p className={s.muted}>{count ? `${count} paired entries produce a ${pct(error!)} mean binned confidence/decision gap. The dashed diagonal represents matching confidence and passing-decision frequency.` : 'No confidence/decision pairs are available. Record explicit outcomes before interpreting confidence.'}</p><div className={s.tableWrap}><table className={s.table}><thead><tr><th scope="col">Confidence band</th><th scope="col">Sample</th><th scope="col">Mean confidence</th><th scope="col">Passing decision frequency</th></tr></thead><tbody>{bins.map(bin => <tr key={bin.low}><th scope="row">{pct(bin.low)}–{pct(bin.high)}</th><td>{bin.count}</td><td>{bin.count ? pct(bin.confidence) : 'No sample'}</td><td>{bin.count ? pct(bin.outcome) : 'No sample'}</td></tr>)}</tbody></table></div></Panel>
    <Panel title="Agent participation and authority"><div className={s.tableWrap}><table className={s.table}><thead><tr><th scope="col">Agent</th><th scope="col">Participation</th><th scope="col">Autonomy evidence</th><th scope="col">Review</th></tr></thead><tbody>{props.controller.snapshot?.agents.map(agent => <tr key={agent.id}><th scope="row">{agent.name}</th><td>{agent.mode === 'active' ? 'Active deliverables' : 'Learning'}</td><td>No per-task autonomy tier exposed</td><td><button onClick={() => { setActor(agent.id); }}>Inspect confidence</button></td></tr>)}</tbody></table></div><Notice>Active participation does not grant an autonomy tier. Promotion, demotion, task-class thresholds, and incident-linked trust require the autonomy policy service. Configure permitted tool actions in the host policy.</Notice></Panel>
  </Page>;
}

export function aggregateSpend(entries: LedgerEntry[], dimension: 'vendor' | 'modelId' | 'actorId' | 'storyId') {
  const groups = new Map<string, { cost: number; priced: number; unpriced: number; tokens: number }>();
  for (const entry of entries.filter(value => !value.simulated)) {
    const key = entry[dimension] || 'Unknown'; const row = groups.get(key) ?? { cost: 0, priced: 0, unpriced: 0, tokens: 0 };
    if (typeof entry.costUsd === 'number' && Number.isFinite(entry.costUsd) && entry.costUsd >= 0) { row.cost += entry.costUsd; row.priced++; } else row.unpriced++;
    row.tokens += Math.max(0, number(entry.tokensIn) ?? 0) + Math.max(0, number(entry.tokensOut) ?? 0); groups.set(key, row);
  }
  return [...groups].sort((a, b) => b[1].cost - a[1].cost);
}
export function Spend(props: GovernanceProps) {
  const now = new Date(); const [month, setMonth] = useState(`${now.getUTCFullYear()}-${String(now.getUTCMonth() + 1).padStart(2, '0')}`);
  const [dimension, setDimension] = useState<'vendor' | 'modelId' | 'actorId' | 'storyId'>('vendor'); const [filter, setFilter] = useState('');
  const validMonth = /^\d{4}-(0[1-9]|1[0-2])$/.test(month); const start = validMonth ? new Date(`${month}-01T00:00:00Z`) : undefined;
  const end = start ? new Date(Date.UTC(start.getUTCFullYear(), start.getUTCMonth() + 1, 1)) : undefined;
  const query = useRpcQuery(props.ready && validMonth ? props.client : undefined, 'ledger.query', { ...(start ? { fromTimestamp: start.toISOString(), toTimestamp: new Date(end!.getTime() - 1).toISOString() } : {}), limit: 1000 });
  const entries = (query.data?.entries ?? []).filter(entry => !entry.simulated); const groups = aggregateSpend(entries, dimension);
  const total = groups.reduce((sum, [, value]) => sum + value.cost, 0); const priced = groups.reduce((sum, [, value]) => sum + value.priced, 0); const unpriced = groups.reduce((sum, [, value]) => sum + value.unpriced, 0);
  const budgetDocument = props.controller.snapshot?.documents?.find(document => document.kind === 'configuration' && document.tags.includes('spend-budget'));
  const initialBudget = useMemo(() => { try { return String(object(JSON.parse(budgetDocument?.body ?? '{}')).monthlyUsd ?? ''); } catch { return ''; } }, [budgetDocument?.body]);
  const [budget, setBudget] = useState(initialBudget); const [budgetEdited, setBudgetEdited] = useState(false);
  useEffect(() => { if (!budgetEdited) setBudget(initialBudget); }, [initialBudget, budgetEdited]); const [error, setError] = useState<string>(); const [message, setMessage] = useState<string>();
  const budgetValue = Number(budget); const forecast = start && end && now >= start && now < end && priced && query.data?.entries.length !== 1000 ? total / Math.max(1, (now.getTime() - start.getTime()) / 86400000) * (end.getTime() - start.getTime()) / 86400000 : undefined;
  return <Page title="One view of recorded model spend." eyebrow="INTELLIGENCE / CROSS-VENDOR SPEND" description="Compare source-recorded costs across native and external agents, with missing prices visible beside the total.">
    <Panel title="Spend scope" action={<button disabled={!props.ready || !validMonth} onClick={query.refresh}>Refresh cost evidence</button>}><div className={s.three}><Field label="Spend month (UTC)"><input type="month" value={month} onChange={event => setMonth(event.target.value)} /></Field><Field label="Group spend by"><select value={dimension} onChange={event => setDimension(event.target.value as typeof dimension)}><option value="vendor">Vendor</option><option value="modelId">Model</option><option value="actorId">Agent</option><option value="storyId">Story</option></select></Field><Field label="Filter spend groups"><input value={filter} onChange={event => setFilter(event.target.value)} /></Field></div><QueryFeedback query={query} connected={props.ready && validMonth} /></Panel>
    <Panel title="Recorded cost and coverage"><div className={s.three}><div className={s.stat}><strong>{priced ? money(total) : 'Unavailable'}</strong><span>Recorded USD ({priced} priced entries)</span></div><div className={s.stat}><strong>{unpriced}</strong><span>Entries with no recorded cost</span></div><div className={s.stat}><strong>{forecast === undefined ? 'Unavailable' : money(forecast)}</strong><span>Linear monthly estimate from priced sample</span></div></div><Notice>Costs are ledger-reported amounts, not reconciled vendor invoices. Simulated entries are excluded. {query.data?.entries.length === 1000 ? 'The 1,000-entry limit was reached; totals are partial and forecasting is disabled.' : 'Unpriced activity may make totals and estimates incomplete.'} Forecasts extrapolate the current month's recorded sample without seasonality.</Notice><div className={s.tableWrap}><table className={s.table}><thead><tr><th scope="col">{dimension}</th><th scope="col">Recorded USD</th><th scope="col">Recorded tokens</th><th scope="col">Priced / unpriced entries</th></tr></thead><tbody>{groups.filter(([key]) => key.toLowerCase().includes(filter.toLowerCase())).map(([key, value]) => <tr key={key}><th scope="row">{key}</th><td>{value.priced ? money(value.cost) : 'Not reported'}</td><td>{value.tokens.toLocaleString()}</td><td>{value.priced} / {value.unpriced}</td></tr>)}</tbody></table></div>{!entries.length && query.data && <p className={s.empty}>No recorded activity in this month. An empty sample is not evidence of a zero vendor bill.</p>}<button disabled={!query.data} onClick={() => getVsCodeApi().postMessage({ type: 'download', mimeType: 'application/json', fileName: `meridian-spend-${month}.json`, content: JSON.stringify({ month, dimension, scope: 'Up to 1000 recorded ledger entries; simulated entries excluded', priced, unpriced, totalUsd: total, groups: Object.fromEntries(groups), entries }, null, 2) })}>Export recorded spend</button></Panel>
    <Panel title="Workspace planning budget"><form className={s.form} onSubmit={event => { event.preventDefault(); setError(undefined); setMessage(undefined); if (!Number.isFinite(budgetValue) || budgetValue <= 0) { setError('Enter a positive monthly USD amount.'); return; } void props.controller.execute('document/save', { document: { ...(budgetDocument ? { id: budgetDocument.id, expectedVersion: budgetDocument.version } : {}), kind: 'configuration', title: 'Workspace spend planning budget', tags: ['spend-budget'], body: JSON.stringify({ monthlyUsd: budgetValue, currency: 'USD', enforcement: 'planning-only' }) } }).then(() => setMessage('Workspace planning budget saved.')).catch(cause => setError(String(cause))); }}><Field label="Monthly budget (USD)"><input type="number" min="0.01" step="0.01" required value={budget} onChange={event => { setBudgetEdited(true); setBudget(event.target.value); }} /></Field><div className={s.actions}><button className={s.primary} disabled={props.controller.busy || !props.controller.snapshot?.capabilities.workspaceOpen}>Save planning budget</button><span className={s.muted}>{Number.isFinite(budgetValue) && budgetValue > 0 && priced ? `${pct(total / budgetValue)} of planning budget represented by priced records.` : 'Set a budget to compare against recorded spend.'}</span></div>{budgetValue > 0 && total > budgetValue && <p className={s.error} role="status">Recorded spend exceeds the planning budget by {money(total - budgetValue)}.</p>}{error && <p className={s.error} role="alert">{error}</p>}{message && <p className={s.success} role="status">{message}</p>}</form><Notice>This budget is a planning reference, not an enforced ceiling. Checkpoint cost stops, external-agent warnings, cost-centre allocation, and deterministic-path savings need runtime and billing telemetry before they can be enforced or measured.</Notice></Panel>
  </Page>;
}
