import { useState } from 'react';
import type { LedgerGetEntryResult, PrIngestResult, PrStatusResult } from '../../../../shared/ts/bus-types';
import { useRpcQuery } from '../../hooks/useRpcQuery';
import { Dialog } from '../Dialog';
import { EvidencePlans } from './EvidencePlans';
import { Confirm, Field, GovernanceNotice, JsonDetail, Notice, Page, Panel, QueryFeedback, Result, canGovern, parseObject, useAction, type GovernanceProps } from './common';
import s from './governance.module.css';

export function Verification(props: GovernanceProps) {
  const query = useRpcQuery(props.ready ? props.client : undefined, 'ledger.query', { actionType: 'test_run', limit: 100 });
  return <Page title="Every criterion needs evidence." eyebrow="QUALITY / VERIFICATION BOARD" description="Trace acceptance criteria to tests, inspect actual run records, and keep quarantined or failing checks visible." actions={<button onClick={() => props.onNavigate('gates')}>Evaluate policy gate</button>}><EvidencePlans controller={props.controller} kind="verification" /><Panel title="Recorded test runs" action={<button disabled={!props.ready} onClick={query.refresh}>Refresh test evidence</button>}><QueryFeedback query={query} connected={props.ready} />{query.data?.entries.length === 0 && <p className={s.empty}>No test-run entries have been recorded in the ledger.</p>}<div className={s.list}>{query.data?.entries.map(entry => <article key={entry.sequence} className={s.card}><h3>#{entry.sequence} · {entry.storyId}</h3><p>{entry.actorId} · {entry.decision ?? 'Outcome not recorded'} · {entry.timestamp}</p><JsonDetail title="Test run provenance" value={entry} /></article>)}</div><Notice>Mutation, performance, accessibility, contract, and environment evidence can be captured in the plan. Automated execution and quarantine enforcement require their corresponding backend runners.</Notice></Panel></Page>;
}
export function Security(props: GovernanceProps) {
  const [filter, setFilter] = useState(''); const [detail, setDetail] = useState<LedgerGetEntryResult>();
  const ledger = useRpcQuery(props.ready ? props.client : undefined, 'ledger.query', { limit: 500 });
  const action = useAction(props.client);
  const permissions = ['read', 'search', 'edit', 'delete', 'move', 'execute', 'think', 'unknown', 'other'];
  const entries = ledger.data?.entries.filter(entry => /permission|scan|denied|threat|security/.test(entry.actionType) && JSON.stringify(entry).toLowerCase().includes(filter.toLowerCase())) ?? [];
  return <Page title="Make the risk inspectable." eyebrow="QUALITY / SECURITY ASSURANCE" description="Review findings, tool access, and recorded agent actions with their source evidence." actions={<button onClick={() => props.onNavigate('gates')}>Open security gate</button>}><Result action={action} /><EvidencePlans controller={props.controller} kind="security" />
    <Panel title="Declared agent capability matrix"><div className={s.tableWrap} tabIndex={0} aria-label="Scrollable data table"><table className={s.table}><thead><tr><th scope="col">Agent</th>{permissions.map(permission => <th key={permission} scope="col">{permission}</th>)}</tr></thead><tbody>{props.controller.snapshot?.agents.map(agent => <tr key={agent.id}><th scope="row">{agent.name}</th>{permissions.map(permission => <td key={permission}>{(agent.permissions as string[]).includes(permission) ? 'Declared' : 'Not declared'}</td>)}</tr>)}</tbody></table></div><Notice>Source: portable agent manifests. A declared capability is not a permission grant; the workspace permission policy and human decision govern each tool invocation. Inspect recorded decisions below for effective outcomes.</Notice></Panel>
    <Panel title="Scans and agent permission evidence" action={<button disabled={!props.ready} onClick={ledger.refresh}>Refresh security events</button>}><Field label="Filter security events"><input value={filter} onChange={event => setFilter(event.target.value)} placeholder="Agent, story, decision, or vendor" /></Field><QueryFeedback query={ledger} connected={props.ready} /><div className={s.list}>{entries.map(entry => <article key={entry.sequence} className={s.card}><h3>#{entry.sequence} · {entry.actionType} <span className={s.badge}>{entry.decision ?? 'Recorded'}</span></h3><p>{entry.actorId} · {entry.storyId} · {entry.timestamp}</p><button disabled={action.busy} onClick={() => void action.run('ledger.getEntry', { sequence: entry.sequence }).then(result => { if (result) setDetail(result); })}>Inspect event #{entry.sequence}</button></article>)}</div>{ledger.data && entries.length === 0 && <p className={s.empty}>No matching security events in the latest 500 ledger entries.</p>}</Panel>
    {detail && <Dialog title={`Security evidence #${detail.sequence}`} description={`${detail.actorId} · ${detail.actionType} · ${detail.observationConfidence}`} onClose={() => setDetail(undefined)} wide><p className={s.muted}>Policy {detail.policyVersion} · {detail.timestamp}</p><h3>Attempted action / input</h3><pre className={s.pre}>{detail.inputAvailable ? detail.input ?? 'No input text recorded.' : 'Input unavailable or encrypted key no longer available.'}</pre><h3>Result / output</h3><pre className={s.pre}>{detail.outputAvailable ? detail.output ?? 'No output text recorded.' : 'Output unavailable or encrypted key no longer available.'}</pre><JsonDetail title="Full provenance and tool context" value={detail} /></Dialog>}
  </Page>;
}
export function Pipeline(props: GovernanceProps) {
  const action = useAction(props.client); const [subject, setSubject] = useState('');
  const [status, setStatus] = useState<PrStatusResult>(); const [ingested, setIngested] = useState<PrIngestResult>();
  const [payload, setPayload] = useState('{\n  "pr": {},\n  "evidence": [],\n  "approvals": []\n}');
  const [preview, setPreview] = useState<{ pr: Record<string, unknown>; evidence: Record<string, unknown>[]; approvals: Record<string, unknown>[]; linkedTicket?: string }>();
  const connected = props.ready && props.enabledTiers.includes('governor');
  return <Page title="From pull request to reviewed delivery." eyebrow="DELIVERY / PIPELINE" description="Ingest source PR evidence, inspect recorded gate outcomes, and track CI and review work." actions={<button onClick={() => props.onNavigate('gates')}>Human approval</button>}><GovernanceNotice props={props} /><Result action={action} />
    <Panel title="Inspect a recorded pull request"><form className={s.form} onSubmit={event => { event.preventDefault(); void action.run('pr/status', { subject: subject.trim() }).then(result => { if (result) setStatus(result); }); }}><Field label="PR subject"><input required placeholder="pr:owner/repository#42" value={subject} onChange={event => { setSubject(event.target.value); setStatus(undefined); }} /></Field><div className={s.actions}><button className={s.primary} disabled={!connected || action.busy}>Load PR status</button></div></form>{status && <><div className={s.three}><div className={s.stat}><strong>{status.ingested ? 'Recorded' : 'Not ingested'}</strong><span>PR intake</span></div><div className={s.stat}><strong>{status.gates.filter(gate => gate.decision === 'pass').length}/{status.gates.length}</strong><span>Recorded gates passed</span></div><div className={s.stat}><strong>{status.merge.status}</strong><span>Current merge approval</span></div></div><p className={s.muted}>{status.storyId} · {status.baseBranch} · head {status.headCommit ?? 'Unknown'}</p><ul className={s.criteria}>{status.gates.map(gate => <li key={`${gate.gate}-${gate.sequence}`}><span className={s.badge} data-state={gate.decision}>{gate.decision}</span><div><strong>{gate.gate}</strong><p>Ledger #{gate.sequence}</p></div></li>)}</ul>{status.merge.missing.map((reason, index) => <p key={index} className={s.error}>{reason}</p>)}<p className={s.muted}>{status.merge.approvalsReceived ?? 0} of {status.merge.requiredApprovals ?? 1} required approvals recorded.</p><JsonDetail title="Source PR status and merge requirements" value={status} /></>}</Panel>
    <Panel title="Ingest PR evidence"><Notice>Paste a provider PR payload including commits and changed files, plus check-run evidence and review approvals. This records intake and gate evaluations in the local ledger. It does not publish, comment on, or merge the PR.</Notice><form className={s.form} onSubmit={event => { event.preventDefault(); try { const value = parseObject(payload); const pr = value.pr; if (!pr || typeof pr !== 'object' || Array.isArray(pr)) throw new Error('The envelope must contain a pr object.'); const records = (name: string) => { const values = value[name] ?? []; if (!Array.isArray(values) || values.some(item => !item || typeof item !== 'object' || Array.isArray(item))) throw new Error(`${name} must be an array of objects.`); return values as Record<string, unknown>[]; }; setPreview({ pr: pr as Record<string, unknown>, evidence: records('evidence'), approvals: records('approvals'), ...(typeof value.linkedTicket === 'string' ? { linkedTicket: value.linkedTicket } : {}) }); } catch (cause) { action.setError(cause instanceof Error ? cause.message : String(cause)); } }}><Field label="PR evidence envelope (JSON)"><textarea rows={10} spellCheck={false} value={payload} onChange={event => setPayload(event.target.value)} /></Field><button disabled={!canGovern(props) || action.busy}>Review PR ingestion</button></form>{ingested && <><p className={s.success}>Ingested {ingested.subject} as {ingested.storyId}; origin ledger #{ingested.sequences.origin}.</p><JsonDetail title="Attributed hunks, observations, and gate evidence" value={ingested} /></>}</Panel>
    <EvidencePlans controller={props.controller} kind="pipeline" />
    <Notice>Live CI logs, CODEOWNERS lookup, provider comment ingestion, merge-queue position, and cross-repository merge execution require SCM/CI connector services. Capture their source evidence in a pipeline plan; no remote status is inferred from a local gate pass.</Notice>
    {preview && <Confirm title="Record this PR intake?" description="The supplied PR, check evidence, and approvals will be recorded and evaluated by the active governance policy." busy={action.busy} error={action.error} onClose={() => setPreview(undefined)} label="Ingest and evaluate PR" onConfirm={() => void action.run('pr/ingest', preview).then(result => { if (result) { setIngested(result); setSubject(result.subject); setPreview(undefined); setStatus(undefined); } })}><pre className={s.pre}>{JSON.stringify(preview, null, 2)}</pre></Confirm>}
  </Page>;
}
