import { useState } from 'react';
import type { StudioDocument, StudioDocumentKind } from '../../../../shared/ts/studio';
import type { WorkbenchController } from '../useWorkbench';
import { Dialog } from '../Dialog';
import { getVsCodeApi } from '../../host/vscode-api';
import { Confirm, Field, JsonDetail, Notice, Panel, object, string } from './common';
import s from './governance.module.css';

export interface EvidenceRecord { id: string; title: string; criterion: string; category: string; status: string; severity: string; evidence: string; retries: string; }
interface EvidencePlan { criteria: string[]; records: EvidenceRecord[]; notes: string; }
export function readPlan(document: StudioDocument): EvidencePlan {
  try {
    const value = object(JSON.parse(document.body));
    return { criteria: Array.isArray(value.criteria) ? value.criteria.filter((item): item is string => typeof item === 'string') : [], notes: string(value.notes), records: Array.isArray(value.records) ? value.records.map((entry, index) => { const row = object(entry); return { id: string(row.id) || `row-${index}`, title: string(row.title), criterion: string(row.criterion), category: string(row.category), status: string(row.status) || 'pending', severity: string(row.severity), evidence: string(row.evidence), retries: string(row.retries) }; }) : [] };
  } catch { return { criteria: [], records: [], notes: document.body }; }
}
export function evidenceGaps(plan: EvidencePlan) { return plan.criteria.filter(criterion => !plan.records.some(record => record.criterion === criterion && record.status === 'pass' && record.evidence.trim())); }
const categories: Record<string, string[]> = {
  verification: ['unit', 'integration', 'contract', 'accessibility', 'performance', 'mutation', 'end-to-end', 'environment'],
  security: ['SAST', 'SCA', 'secrets', 'SBOM', 'AI-BOM', 'attestation', 'output scan', 'agent threat'],
  pipeline: ['CI job', 'review', 'CODEOWNERS', 'merge dependency', 'environment', 'release'],
};
export function EvidencePlans({ controller, kind }: { controller: WorkbenchController; kind: Extract<StudioDocumentKind, 'verification' | 'security' | 'pipeline'> }) {
  const docs = (controller.snapshot?.documents ?? []).filter(document => document.kind === kind);
  const [filter, setFilter] = useState(''); const [selected, setSelected] = useState<string>();
  const [editor, setEditor] = useState<StudioDocument | 'new'>(); const [recordEditor, setRecordEditor] = useState<{ document: StudioDocument; record?: EvidenceRecord }>();
  const [removing, setRemoving] = useState<StudioDocument>(); const [error, setError] = useState<string>();
  const [status, setStatus] = useState('all');
  const active = docs.find(document => document.id === selected);
  const plan = active ? readPlan(active) : undefined;
  const mutate = async (work: () => Promise<unknown>) => { setError(undefined); try { await work(); return true; } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); return false; } };
  const savePlan = (document: StudioDocument, next: EvidencePlan) => controller.execute('document/save', { document: { id: document.id, expectedVersion: document.version, kind, title: document.title, tags: document.tags, body: JSON.stringify(next) } });
  return <>
    <Panel title={kind === 'verification' ? 'Criterion-to-test evidence plans' : kind === 'security' ? 'Security findings and assurance evidence' : 'CI, review, and release evidence'} action={<button className={s.primary} disabled={!controller.snapshot?.capabilities.workspaceOpen || controller.busy} onClick={() => { setError(undefined); setEditor('new'); }}>New {kind} plan</button>}>
      <Notice>These are workspace-authored evidence records. Saving a pass or releasing quarantine updates this plan only; backend gates independently evaluate supplied artifacts. No scanner, test runner, or CI deployment is started here.</Notice>
      {error && <p role="alert" className={s.error}>{error}</p>}
      <div className={s.toolbar}><Field label="Find an evidence plan"><input value={filter} onChange={event => setFilter(event.target.value)} placeholder="Title or tags" /></Field><Field label="Record state"><select value={status} onChange={event => setStatus(event.target.value)}>{['all', 'pending', 'pass', 'fail', 'quarantined'].map(value => <option key={value}>{value}</option>)}</select></Field></div>
      <div className={s.list}>{docs.filter(document => `${document.title} ${document.tags.join(' ')}`.toLowerCase().includes(filter.toLowerCase())).map(document => {
        const value = readPlan(document); const gaps = evidenceGaps(value);
        return <div className={s.card} key={document.id}><h3>{document.title}</h3><p>{value.records.length} evidence records · {value.criteria.length} criteria · {gaps.length} uncovered · v{document.version}</p><div className={s.actions}><button aria-pressed={selected === document.id} onClick={() => setSelected(document.id)}>Inspect {document.title}</button><button onClick={() => setEditor(document)}>Edit plan</button><button disabled={controller.busy} onClick={() => void mutate(async () => { const result = await controller.execute('document/export', { id: document.id }); getVsCodeApi().postMessage({ type: 'download', mimeType: 'application/json', fileName: result.fileName, content: result.content }); })}>Export</button><button disabled={controller.busy} onClick={() => setRemoving(document)}>Remove plan</button></div></div>;
      })}</div>{docs.length === 0 && <p className={s.empty}>Create a plan to connect acceptance criteria to evidence, retain review notes, and track unresolved work.</p>}
    </Panel>
    {active && plan && <Panel title={active.title} action={<button onClick={() => setRecordEditor({ document: active })}>Add evidence record</button>}>
      {plan.notes && <p className={s.muted}>{plan.notes}</p>}
      {plan.criteria.length > 0 && <><h3>Criterion traceability</h3><div className={s.tableWrap} tabIndex={0} aria-label="Scrollable data table"><table className={s.table}><thead><tr><th scope="col">Acceptance criterion</th><th scope="col">Linked records</th><th scope="col">Recorded coverage</th></tr></thead><tbody>{plan.criteria.map((criterion, index) => <tr key={`${criterion}-${index}`}><th scope="row">{criterion}</th><td>{plan.records.filter(record => record.criterion === criterion).map(record => record.title).join(', ') || 'No covering evidence'}</td><td><span className={s.badge} data-state={evidenceGaps(plan).includes(criterion) ? 'block' : 'pass'}>{evidenceGaps(plan).includes(criterion) ? 'Uncovered' : 'Evidence supplied'}</span></td></tr>)}</tbody></table></div><Notice>{evidenceGaps(plan).length ? `${evidenceGaps(plan).length} criteria lack a passing record with evidence. This plan is incomplete.` : 'Every criterion has passing, user-supplied evidence. Independent gate evaluation is still required.'}</Notice></>}
      <div className={s.list}>{plan.records.filter(record => status === 'all' || record.status === status).map(record => <article className={s.card} key={record.id}><h3>{record.title} <span className={s.badge} data-state={record.status === 'fail' ? 'block' : record.status}>{record.status}</span></h3><p>{record.category} · {record.severity || 'Severity unspecified'} · {record.criterion || 'No acceptance criterion linked'}</p><p>{record.evidence || 'No supporting evidence supplied.'}</p>{record.retries && <p>Retry / quarantine history: {record.retries}</p>}<div className={s.actions}><button onClick={() => setRecordEditor({ document: active, record })}>Edit {record.title}</button>{record.status === 'quarantined' && <button onClick={() => setRecordEditor({ document: active, record: { ...record, status: 'pending' } })}>Review quarantine release</button>}</div></article>)}</div>
      {!plan.records.length && <p className={s.empty}>No evidence has been recorded for this plan.</p>}<JsonDetail title="Portable evidence data" value={plan} />
    </Panel>}
    {editor && <PlanEditor document={editor === 'new' ? undefined : editor} kind={kind} controller={controller} onClose={() => setEditor(undefined)} onSaved={id => { setSelected(id); setEditor(undefined); }} />}
    {recordEditor && <RecordEditor document={recordEditor.document} record={recordEditor.record} kind={kind} busy={controller.busy} onClose={() => setRecordEditor(undefined)} onSave={async record => { const value = readPlan(recordEditor.document); const index = value.records.findIndex(item => item.id === record.id); if (index < 0) value.records.push(record); else value.records[index] = record; if (await mutate(() => savePlan(recordEditor.document, value))) setRecordEditor(undefined); else throw new Error('Evidence was not saved. Check the error on the page and reopen the latest plan if it changed.'); }} />}
    {removing && <Confirm title="Remove this evidence plan?" description="The current plan will be removed from this workspace. Ledger evidence remains in the audit record." busy={controller.busy} error={error} onClose={() => setRemoving(undefined)} label="Remove plan" onConfirm={() => void mutate(() => controller.execute('document/remove', { id: removing.id, expectedVersion: removing.version })).then(ok => { if (ok) { if (selected === removing.id) setSelected(undefined); setRemoving(undefined); } })}><p>{removing.title} · version {removing.version} · {readPlan(removing).records.length} evidence records</p></Confirm>}
  </>;
}
function PlanEditor({ document, kind, controller, onClose, onSaved }: { document?: StudioDocument; kind: 'verification' | 'security' | 'pipeline'; controller: WorkbenchController; onClose: () => void; onSaved: (id: string) => void }) {
  const initial = document ? readPlan(document) : { criteria: [], records: [], notes: '' };
  const [title, setTitle] = useState(document?.title ?? ''); const [criteria, setCriteria] = useState(initial.criteria.join('\n')); const [notes, setNotes] = useState(initial.notes); const [tags, setTags] = useState(document?.tags.join(', ') ?? ''); const [error, setError] = useState<string>();
  return <Dialog title={document ? 'Edit evidence plan' : `New ${kind} plan`} onClose={onClose}><form className={s.form} onSubmit={event => { event.preventDefault(); setError(undefined); void controller.execute('document/save', { document: { ...(document ? { id: document.id, expectedVersion: document.version } : {}), kind, title: title.trim(), tags: tags.split(',').map(value => value.trim()).filter(Boolean), body: JSON.stringify({ ...initial, criteria: [...new Set(criteria.split('\n').map(value => value.trim()).filter(Boolean))], notes }) } }).then(snapshot => { const saved = snapshot.documents?.find(value => document ? value.id === document.id : value.title === title.trim() && value.kind === kind); onSaved(saved?.id ?? document?.id ?? ''); }).catch(cause => setError(cause instanceof Error ? cause.message : String(cause))); }}><Field label="Plan title"><input required value={title} onChange={event => setTitle(event.target.value)} /></Field><Field label="Acceptance criteria (one per line)"><textarea rows={5} value={criteria} onChange={event => setCriteria(event.target.value)} /></Field><Field label="Review notes"><textarea value={notes} onChange={event => setNotes(event.target.value)} /></Field><Field label="Tags (comma separated)"><input value={tags} onChange={event => setTags(event.target.value)} /></Field>{error && <p className={s.error} role="alert">{error}</p>}<div className={s.actions}><button type="button" onClick={onClose}>Cancel</button><button className={s.primary} disabled={controller.busy}>Save plan</button></div></form></Dialog>;
}
function RecordEditor({ document, record, kind, busy, onClose, onSave }: { document: StudioDocument; record?: EvidenceRecord; kind: string; busy: boolean; onClose: () => void; onSave: (record: EvidenceRecord) => Promise<void> }) {
  const [value, setValue] = useState<EvidenceRecord>(record ?? { id: globalThis.crypto.randomUUID(), title: '', criterion: '', category: categories[kind][0], status: 'pending', severity: 'unspecified', evidence: '', retries: '' }); const [error, setError] = useState<string>();
  const update = (field: keyof EvidenceRecord, text: string) => setValue(previous => ({ ...previous, [field]: text }));
  return <Dialog title={record ? 'Edit evidence record' : 'Add evidence record'} description="Record the source and observed result. These notes do not execute or certify a test or scan." onClose={onClose}><form className={s.form} onSubmit={event => { event.preventDefault(); if (value.status === 'pass' && !value.evidence.trim()) { setError('A passing record requires supporting evidence.'); return; } void onSave(value).catch(cause => setError(String(cause))); }}><Field label="Record title"><input required value={value.title} onChange={event => update('title', event.target.value)} /></Field><Field label="Linked criterion"><select value={value.criterion} onChange={event => update('criterion', event.target.value)}><option value="">Unlinked</option>{readPlan(document).criteria.map(criterion => <option key={criterion}>{criterion}</option>)}</select></Field><div className={s.row}><Field label="Evidence category"><select value={value.category} onChange={event => update('category', event.target.value)}>{categories[kind].map(category => <option key={category}>{category}</option>)}</select></Field><Field label="Observed state"><select value={value.status} onChange={event => update('status', event.target.value)}>{['pending', 'pass', 'fail', 'quarantined'].map(status => <option key={status}>{status}</option>)}</select></Field></div><Field label="Severity"><select value={value.severity} onChange={event => update('severity', event.target.value)}>{['unspecified', 'info', 'low', 'medium', 'high', 'critical'].map(severity => <option key={severity}>{severity}</option>)}</select></Field><Field label="Evidence source and result" hint="Include the test/scan ID, artifact location, ledger sequence, measured score, and observed result when available."><textarea required={value.status === 'pass'} rows={5} value={value.evidence} onChange={event => update('evidence', event.target.value)} /></Field><Field label="Retry / quarantine history"><textarea value={value.retries} onChange={event => update('retries', event.target.value)} /></Field>{error && <p className={s.error} role="alert">{error}</p>}<div className={s.actions}><button type="button" onClick={onClose}>Cancel</button><button className={s.primary} disabled={busy}>Save evidence record</button></div></form></Dialog>;
}
