import { useState } from 'react';
import type { WorktreeConflictsResult, WorktreeInfo } from '../../../../shared/ts/bus-types';
import { useRpcQuery } from '../../hooks/useRpcQuery';
import { Confirm, Field, GovernanceNotice, JsonDetail, Notice, Page, Panel, QueryFeedback, Result, canGovern, useAction, type GovernanceProps } from './common';
import s from './governance.module.css';

export function Repositories(props: GovernanceProps) {
  const connected = props.ready && props.enabledTiers.includes('governor');
  const worktrees = useRpcQuery(connected ? props.client : undefined, 'worktree/list', {});
  const action = useAction(props.client);
  const [story, setStory] = useState(''); const [adapter, setAdapter] = useState(''); const [base, setBase] = useState('main');
  const [filter, setFilter] = useState(''); const [paths, setPaths] = useState('');
  const [conflicts, setConflicts] = useState<WorktreeConflictsResult>();
  const [confirm, setConfirm] = useState<{ kind: 'remove' | 'abort'; worktree: WorktreeInfo }>();
  const [reason, setReason] = useState(''); const [force, setForce] = useState(false);
  return <Page title="A workspace for every story." eyebrow="DELIVERY / REPOSITORIES & WORKTREES" description="Create isolated story branches, inspect uncommitted work, and check conflicts before a packet starts.">
    <GovernanceNotice props={props} /><Result action={action} />
    <Panel title="Current repository"><p className={s.muted}>{props.workspaceDir ?? 'No workspace open'}</p><Notice>Worktree actions target the current repository. A portable agent run currently uses its configured workspace; creating a story worktree here does not automatically reroute that agent's execution.</Notice></Panel>
    <div className={s.row}><Panel title="Create an isolated story worktree"><form className={s.form} onSubmit={event => { event.preventDefault(); void action.run('worktree/create', { storyId: story.trim(), adapterId: adapter.trim(), baseBranch: base.trim() }).then(result => { if (result) { action.setMessage(`Created ${result.worktree.branch} at ${result.worktree.path}.`); worktrees.refresh(); } }); }}><Field label="Story ID"><input required pattern="[A-Za-z0-9._-]+" value={story} onChange={event => setStory(event.target.value)} /></Field><div className={s.row}><Field label="Agent adapter ID"><input required pattern="[A-Za-z0-9._-]+" value={adapter} onChange={event => setAdapter(event.target.value)} list="repository-agents" /><datalist id="repository-agents">{props.controller.snapshot?.agents.map(agent => <option key={agent.id} value={agent.id}>{agent.name}</option>)}</datalist></Field><Field label="Base branch"><input required value={base} onChange={event => setBase(event.target.value)} /></Field></div><button className={s.primary} disabled={!canGovern(props) || action.busy}>Create story worktree</button></form></Panel>
    <Panel title="Packet conflict preflight"><form className={s.form} onSubmit={event => { event.preventDefault(); void action.run('worktree/conflicts', { ...(story.trim() ? { storyId: story.trim() } : {}), baseBranch: base.trim(), ...(paths.trim() ? { targetPaths: paths.split('\n').map(path => path.trim()).filter(Boolean) } : {}) }).then(result => { if (result) setConflicts(result); }); }}><Field label="Packet target paths (one per line)" hint="Uses the story and base branch selected alongside. An empty path list checks all dirty primary-tree files."><textarea value={paths} onChange={event => setPaths(event.target.value)} /></Field><button disabled={!connected || action.busy}>Check conflicts</button></form>{conflicts && <><p role="status" className={conflicts.blocked ? s.error : s.success}>{conflicts.blocked ? `${conflicts.conflicts.length} conflicts block the packet.` : 'No conflicts detected in the requested scope.'}</p>{conflicts.conflicts.map((conflict, index) => <div className={s.card} key={index}><h3>{conflict.path ?? 'Branch-level conflict'}</h3><p>{conflict.kind} · {conflict.detail}</p></div>)}<Notice>Resolve primary-tree changes with the editor's source control tools, then rerun this preflight. This view does not stash or commit the human's changes.</Notice></>}</Panel></div>
    <Panel title="Managed worktrees" action={<button disabled={!connected} onClick={worktrees.refresh}>Refresh worktrees</button>}><Field label="Filter worktrees"><input value={filter} onChange={event => setFilter(event.target.value)} placeholder="Story, branch, or adapter" /></Field><QueryFeedback query={worktrees} connected={connected} /><div className={s.list}>{worktrees.data?.worktrees.filter(tree => JSON.stringify(tree).toLowerCase().includes(filter.toLowerCase())).map(tree => <article className={s.card} key={tree.storyId}><h3>{tree.storyId} <span className={s.badge}>{tree.dirty ? 'Uncommitted changes' : 'Clean worktree'}</span></h3><p>{tree.branch} ← {tree.baseBranch} · {tree.unpushedCommits} commits beyond base · Agent {tree.adapterId}</p><p>{tree.path}</p><JsonDetail title="Inspect branch, identity, and commit digests" value={tree} /><div className={s.actions}><button onClick={() => { setStory(tree.storyId); setBase(tree.baseBranch); setAdapter(tree.adapterId); }}>Use for preflight</button><button disabled={!canGovern(props) || action.busy} onClick={() => { setReason(''); setForce(false); setConfirm({ kind: 'remove', worktree: tree }); }}>Remove worktree</button><button disabled={!canGovern(props) || action.busy} onClick={() => setConfirm({ kind: 'abort', worktree: tree })}>Abort story</button></div></article>)}</div>{worktrees.data?.worktrees.length === 0 && <p className={s.empty}>No Meridian-managed worktrees. Create one to keep a story's changes separate from the primary tree.</p>}</Panel>
    {confirm && <Confirm title={confirm.kind === 'abort' ? 'Abort this story?' : 'Remove this worktree?'} description={confirm.kind === 'abort' ? 'Removes the story worktree and its never-pushed branch. Pushed branches are retained by the backend. Uncommitted work in the story worktree may be discarded.' : 'Removes this story worktree. The story branch remains. Dirty work is refused unless you explicitly allow discarding it below.'} busy={action.busy} error={action.error} onClose={() => setConfirm(undefined)} label={confirm.kind === 'abort' ? 'Abort story' : 'Remove worktree'} onConfirm={() => { if (confirm.kind === 'abort') void action.run('worktree/abortStory', { storyId: confirm.worktree.storyId }).then(result => { if (result) { action.setMessage(`Removed ${result.worktreeRef}. ${result.branchDeleted ? 'Story branch deleted.' : result.branchKeptReason ?? 'Story branch retained.'}`); setConfirm(undefined); worktrees.refresh(); } }); else void action.run('worktree/remove', { storyId: confirm.worktree.storyId, force, reason: reason.trim() || 'Removed from Repositories & Worktrees' }).then(result => { if (result) { action.setMessage(`Removed ${result.worktreeRef}; branch ${result.branch} retained.`); setConfirm(undefined); worktrees.refresh(); } }); }}><pre className={s.pre}>{confirm.worktree.path}{'\n'}Story: {confirm.worktree.storyId}{'\n'}Branch: {confirm.worktree.branch}{'\n'}Uncommitted changes: {confirm.worktree.dirty ? 'YES' : 'No'}{'\n'}Commits beyond base: {confirm.worktree.unpushedCommits}</pre>{confirm.kind === 'remove' && <><Field label="Removal reason"><textarea value={reason} onChange={event => setReason(event.target.value)} /></Field><label className={s.check}><input type="checkbox" checked={force} onChange={event => setForce(event.target.checked)} />Discard uncommitted changes in this worktree if necessary.</label></>}</Confirm>}
  </Page>;
}
